### ISSUE TITLE
🍣

### ISSUE THREAD

**Issue by hoto17296** [ngineerxiv/dark#1]
行きましょう

備考： [神楽坂すしアカデミー](http://kagurazakasushi.com/)

**Comment by ara-ta3** [comment]
さあいつ行こう
調整さんかな

**Comment by gomayumax** [comment]
http://blog.livedoor.jp/dqnplus/archives/1873202.html

だいぶ前だけどこの記事見て  
ほんとうに大丈夫だろうかと心配になっていたが  
それ以上に寿司が食べたい  
🍣欲は何者にも変えられない

**Comment by gomayumax** [comment]
雑にみんなで回転🍣どうだろう

ていうか🍣食べたいだけなんだ、うおおおおお

**Comment by ara-ta3** [comment]
![進捗どうですか](http://typo.telulu.co.jp/i/ZHJBVw.u.png)

**Comment by acchanAlexander** [comment]
いま予約見た感じ、4人までなら今週土日とかで行けそうなのだが
どうだろう。
http://kagurazakasushi.com/

**Comment by gomayumax** [comment]
@acchanAlexander 今週は、ほとごま厳しいです(´・ω・｀)

**Comment by ara-ta3** [comment]
![image](https://cloud.githubusercontent.com/assets/2089153/20437833/d7403e2a-adf8-11e6-9d70-83c8407e06df.png)

**Comment by ara-ta3** [comment]
進捗なさそう
