### ISSUE TITLE
電脳コイル鑑賞会

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#10]
電脳コイルは教養です

**Comment by mihyaeru21** [comment]
全面的に同意

**Comment by stefafafan** [comment]
参加したい

とりあえず [dアニメストア](https://anime.dmkt-sp.jp/animestore/ci_pc?workId=20270) にありますね

**Comment by ara-ta3** [comment]
あとは日にちだけっぽいので調整さんを明日立てます

**Comment by ara-ta3** [comment]
11月にできたらいいな
https://chouseisan.com/s?h=162f27dcd2f24ad08f482604571c3207

**Comment by mrtry** [comment]
教養を身に着けたい

**Comment by acchanAlexander** [comment]
教養！

**Comment by gomayumax** [comment]
調整さん書いた(・∀・)

**Comment by stefafafan** [comment]
調整しました(´･_･`)

**Comment by ara-ta3** [comment]
26日の昼かなぁという気持ち

**Comment by stefafafan** [comment]
土曜日は気がついたらDJの予定が入ったので不参加でお願いします :bow:

**Comment by ara-ta3** [comment]
Dアニメストア登録して無料期間中
明日は14時からだが、みんなどれくらいに来るのだろう

**Comment by gomayumax** [comment]
14:00には到着するつもり

**Comment by ara-ta3** [comment]
13時集合の機運です

```

arata [11:22]  
ray ruby put (25 * 2 * 13 / 60).to_s

ray [11:22]  
NoMethodError: undefined method `put' for #<Ruboty::Handlers::Ruby:0x007fc1bb386178>

arata [11:23]  
ray ruby puts (25 * 2 * 13 / 60).to_s

[11:23]  
ray ruby p (25 * 2 * 13 / 60).to_s

ray [11:23]  
10

arata [11:23]  
2クールってことはこれ10時間くらいかかるのか

goma [11:24]  
1.5倍速したいけど無理かーーー

arata [11:25]  
OP EDは1話だけにしよう

[11:25]  
あと最終話

[11:26]  
え、これ13時集合とかじゃなくて大丈夫・・・？ｗ

goma [11:27]  
わかる。13時でも良いよ
```

**Comment by ara-ta3** [comment]
メモ
わっさん「電脳コイルの面白いところは、”なん・・・だと・・・”が出て来る回数を数えること」

**Comment by ara-ta3** [comment]
なんだと、となんだっての数

```
arata [23:52]  
dark score nanndato

darkBOT [23:52]  
nanndato has 8 points.

arata [23:52]  
dark score nanndatte

darkBOT [23:52]  
nanndatte has 6 points.
```

**Comment by ara-ta3** [comment]
とてもよかったです
https://anime.dmkt-sp.jp/animestore/ci_pc?workId=20270

今度はなにかの1クールアニメ見て、ゲームして飲んで解散みたいなことやりたい

dアニメストアの速度関連

- 1.25倍は余裕
- 1.5倍もまあ余裕
- 2倍も比較的いっかなっていう回につかうならちゃんとは聞こえるので良さげだった
  - 内容を理解できるかは置いといて

摂取したカロリー

![image](https://cloud.githubusercontent.com/assets/2089153/20641088/8ba2a4ee-b433-11e6-8fd8-09f1c1d33178.png)

解禁したボジョレー

![image](https://cloud.githubusercontent.com/assets/2089153/20641119/ab0f568c-b434-11e6-93b8-d05612fca937.png)
