### ISSUE TITLE
技術書典に行き、本を買い、ご飯を食べて、帰るだけ

### ISSUE THREAD

**Issue by acchanAlexander** [ngineerxiv/dark#100]
日時 2019/04/14 (日) 11:00〜17:00
場所 池袋サンシャインシティ2F 展示ホールD（文化会館ビル2F）

技術書典 6
https://techbookfest.org/event/tbf06

サークルリスト
https://techbookfest.org/event/tbf06/circle

**Comment by acchanAlexander** [comment]
一緒に行ってくれる人はコメントくれるなどしてくれると嬉しさ

お使いして欲しい人とかいれば、言ってくだしぁ

**Comment by haze-it** [comment]
いくかあ

**Comment by natsumican63** [comment]
いきたい

**Comment by nasa9084** [comment]
PR: https://techbookfest.org/event/tbf06/circle/52180003

**Comment by mom0tomo** [comment]
PR：https://techbookfest.org/event/tbf06/circle/58030001

**Comment by jp-taku2** [comment]
いくいく

**Comment by igayamaguchi** [comment]
行く！

**Comment by acchanAlexander** [comment]
10:00 に池袋駅集合でよい？

**Comment by haze-it** [comment]
よさそう

**Comment by natsumican63** [comment]
朝起きれなさそうなので、昼過ぎにぷらっと行きます 🙇

**Comment by mom0tomo** [comment]
11時〜13時の2時間のみ有料（雨天時無料）
だからお気をつけて！

**Comment by mom0tomo** [comment]
https://note.mu/mochikoastech/n/na42b154fd247
```
技術書典6に行くなら最寄り駅は池袋駅よりも

有楽町線の東池袋駅

の方が圧倒的に近い！

有楽町線「東池袋駅」の6,7番出口へ向かうと途中に「サンシャインシティ地下通路」の案内があり、池袋サンシャインシティ 文化会館まで地下通路で繋がっているそうですので、特に雨の場合は東池袋駅から行くのがよさそうです。
```

**Comment by acchanAlexander** [comment]
技術書展楽しかったですね！
（僕は寝坊して合流できなかったけど）
また次回行きましょう！
