### ISSUE TITLE
Goodbye すずたく サイゼ飲み

### ISSUE THREAD

**Issue by mrtry** [ngineerxiv/dark#101]
たく氏が引っ越す前にサイゼ飲みしたいと言ってたのでやっていくぞ

## 日程と調整さん

候補日(時間は仮)
- 4/19(金)
- 4/20(土)
- 4/21(日)
- 4/22(月)
- 4/23(火)
- 4/24(水)

調整さん
- https://chouseisan.com/s?h=8e9e3159c2b64e0a950d352c10cd2f2c

**Comment by mrtry** [comment]
集まりがアレなので `22(月)` - `24(水)` を追加

**Comment by sota1235** [comment]
行けたら行きたい

**Comment by mrtry** [comment]
決定で！！！！！！！！！！！！！！！

日程: 4/22(月) 20時集合
場所: [サイゼリヤ 渋谷新南口](https://tabelog.com/tokyo/A1303/A130301/13114080/
)

**Comment by haze-it** [comment]
（途中参加します🙏）

**Comment by mrtry** [comment]
誰も牢獄に入ることなく無事終わった

**Comment by mrtry** [comment]
:kan:
