### ISSUE TITLE
宇都宮に餃子を食べにいく会

### ISSUE THREAD

**Issue by haze-it** [ngineerxiv/dark#102]
<img width="314" alt="スクリーンショット 2019-04-12 13 18 00" src="https://user-images.githubusercontent.com/31850710/56012014-691a1180-5d25-11e9-9b27-75f9d6f4682b.png">

みんみん
http://www.minmin.co.jp/

ついでに栃木観光するとか温泉入るとかしても良いかも。日帰りで
5月〜後日調整

**Comment by igayamaguchi** [comment]
よい。最高。

**Comment by udayan28** [comment]
楽しみ〜〜〜

**Comment by Omega014** [comment]
え、栃木観光めっちゃ楽しそうなので参加したい。天気よかったら私はバイクで行きます！

**Comment by haze-it** [comment]
存在を忘れていた。
今週中に自分の予定見て調整さん立てる

**Comment by haze-it** [comment]
宇都宮、暑くなったら地獄っぽい気がするから10月〜11月にしたい。どう？
自分の予定が割と埋まってきたからっていうだけなんだけど。

**Comment by jp-taku2** [comment]
その時期なら俺も車で行こうかなｗ

**Comment by mihyaeru21** [comment]
餃子行きたい

**Comment by acchanAlexander** [comment]
その時期なら僕も行きたい

**Comment by aq-nozomi** [comment]
自分も、その時季なら行きたさあります。
個人的に、餃子にはレモンサワー

**Comment by Tackeyyyyyyyy** [comment]
実家栃木だし
予定合えば行こうかなー(笑)

**Comment by haze-it** [comment]
9月だしそろそろ調整さん建てるかな

**Comment by haze-it** [comment]
https://chouseisan.com/s?h=0a20296e73ac4e6099d87abbe95e7566

**Comment by haze-it** [comment]
日帰りでいける範囲の栃木観光スポット情報は随時募集しています

**Comment by haze-it** [comment]
11月かな

**Comment by haze-it** [comment]
11/23（土）でいい？？

**Comment by igayamaguchi** [comment]
OK 🙆

**Comment by aq-nozomi** [comment]
ごめんなさい！！！
予定勘違いしてて、23日は大阪におり、、、

**Comment by acchanAlexander** [comment]
すみません、23日行けなくなりそうです><
みなさんで楽しんできてください！

**Comment by jp-taku2** [comment]
すみません、予定を入れてしまっていた。。。。

**Comment by haze-it** [comment]
だめそうで草

**Comment by haze-it** [comment]
行く予定で予定空けている人どれぐらいいます？2〜3人なら別日にするか閉めるかしようかなと思っているんですが

**Comment by Tackeyyyyyyyy** [comment]
私は大丈夫

**Comment by mihyaeru21** [comment]
友達の結婚式が😇

**Comment by igayamaguchi** [comment]
空けてはある
別日ならそれもそれでよし

**Comment by haze-it** [comment]
別日かなー、23は都内で雑に餃子食べに行くだけにしてまた別途開催って感じでいいかなという気がしている。どうよ @igayamaguchi @Tackeyyyyyyyy

**Comment by Tackeyyyyyyyy** [comment]
@haze-it @igayamaguchi 
 🆗

都内で美味しい餃子が食べれるところはどこだ？

**Comment by acchanAlexander** [comment]
23 都内なら行けそうな感じなんすが、開催される感じかな？

**Comment by igayamaguchi** [comment]
開催されるけどお店決めてない

**Comment by haze-it** [comment]
PERFECT GYOZAしたい
https://tabelog.com/tokyo/A1303/A130301/13216233/

**Comment by igayamaguchi** [comment]
Perfectっぽい

**Comment by haze-it** [comment]
来年春先に行こうねってなった。餃子おいしかった
