### ISSUE TITLE
Belgian Beer Weekend 2019 @ 日比谷

### ISSUE THREAD

**Issue by rnitame** [ngineerxiv/dark#103]
https://belgianbeerweekend.jp/hibiya/tickets/

6月27日（木）〜7月7日（日）です！！！！！！1

6/29-30 か 7/6-7 かな

**Comment by Omega014** [comment]
開催日そろそろなので調整さんつくった！
https://chouseisan.com/s?h=43440be685ef4cbab4f8233e0734cc97

**Comment by Omega014** [comment]
6/30に決定だな　今んところ三人だけどラウンジ予約とかする？

**Comment by rnitame** [comment]
https://life-designs.jp/wp-content/uploads/2019/04/https___st4r.beer_storage_1060_BBW18_lounge3-1000x666.jpg
のんびりできそうでいいな、ラウンジ予約しよー

**Comment by mihyaeru21** [comment]
@rnitame まだ間に合いますか！？

**Comment by rnitame** [comment]
4 人目きたこれ、間に合いまっせ

**Comment by udayan28** [comment]
@rnitame まだ間に合いますか！？

**Comment by rnitame** [comment]
5 人になるとラウンジいけなくなる！！w

**Comment by mihyaeru21** [comment]
> 5 人になるとラウンジいけなくなる！！w

😱

**Comment by rnitame** [comment]
うだやんは来られないみたいなので 4 人で！
そしてラウンジ予約した、13:15 から 2 時間

**Comment by rnitame** [comment]
また来年！
![IMG_20190630_133510226_HDR](https://user-images.githubusercontent.com/4950792/60396815-efa1fa80-9b80-11e9-8368-a88d7226eb30.jpg)
