### ISSUE TITLE
ストロングゼロ飯会

### ISSUE THREAD

**Issue by mrtry** [ngineerxiv/dark#105]
ストロングゼロを調味料として利用した料理を食べながら、ストロングゼロを飲む会

## レシピ
- [ストロングゼロを使った『ストロングプリン』が危険すぎる味　食後に酔う不思議な感覚に – ニュースサイトしらべぇ](https://sirabee.com/2019/03/08/20162022059/)
- [ストロングゼロを使った『ストロングしゃぶしゃぶ』がストロンググルメ史上最高のウマさ – ニュースサイトしらべぇ](https://sirabee.com/2019/04/03/20162059342/)
- [しらべぇに載ってるストロングゼロを使った料理レシピ一覧（多分全部） \- とんとげのネガティブログ](https://tontoge.hatenablog.com/entry/2019/02/12/080039)

などなど

**Comment by mrtry** [comment]
3~5人集まったらやる(自宅のキャパ的に5人まで)

**Comment by haze-it** [comment]
はい

**Comment by udayan28** [comment]
はい

**Comment by mrtry** [comment]
今週末中に参加者増えなかったら、解散する

**Comment by ara-ta3** [comment]
土曜日か次の日休みなら参加したい

**Comment by acchanAlexander** [comment]
まだ人数キャパ大丈夫で、日程が合えば参加したひ

**Comment by mrtry** [comment]
調整さん立てたので、参加したい人はよろしく！！ (あと2名程度
(あらた氏が言う通り土曜に開催したい)
https://chouseisan.com/schedule/newEvent/complete?h=dcbc069914774a4fa183eb92b397017d

**Comment by ara-ta3** [comment]
そういえば季節限定系はAmazonだと買える

https://www.amazon.co.jp/%E3%82%B5%E3%83%B3%E3%83%88%E3%83%AA%E3%83%BC%E3%83%81%E3%83%A5%E3%83%BC%E3%83%8F%E3%82%A4-196%E2%84%83-%E3%82%B9%E3%83%88%E3%83%AD%E3%83%B3%E3%82%B0%E3%82%BC%E3%83%AD-%E8%91%A1%E8%90%84%E3%83%80%E3%83%96%E3%83%AB-350ml%C3%9724%E6%9C%AC/dp/B01N2YILR3/ref=sr_1_14?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&keywords=%E3%82%B9%E3%83%88%E3%83%AD%E3%83%B3%E3%82%B0%E3%82%BC%E3%83%AD&qid=1559291951&s=gateway&sr=8-14

Amazon freshでも買えることを今知った
https://www.amazon.co.jp/%E3%82%B5%E3%83%B3%E3%83%88%E3%83%AA%E3%83%BC-%E3%83%81%E3%83%A5%E3%83%BC%E3%83%8F%E3%82%A4-196%E2%84%83-%E3%82%B9%E3%83%88%E3%83%AD%E3%83%B3%E3%82%B0%E3%82%BC%E3%83%AD-%E8%91%A1%E8%90%84%E3%83%80%E3%83%96%E3%83%AB/dp/B01N7KQP50/ref=sr_1_32?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&fpw=fresh&keywords=%E3%82%B9%E3%83%88%E3%83%AD%E3%83%B3%E3%82%B0%E3%82%BC%E3%83%AD&qid=1559291951&s=gateway&sr=8-32

**Comment by mrtry** [comment]
なるほど感謝
参加者定まったら、テキトーにポチって我が家に送りつけよう 👌

**Comment by mrtry** [comment]
6/29(土) が濃厚

**Comment by mrtry** [comment]
来週じゃん
ストロングゼロは、近所のハナマサで調達する感じでいいんだろうかなーーー(ラインナップを確認しておく)
映えのために、リッターがあったほうがいいか？？

あと、料理のリクエストをおまちしております
ここを見ればストロングゼロレシピは網羅されているはず
- https://tontoge.hatenablog.com/entry/2019/02/12/080039

ストロングゼロレシピ以外のリクも可だし、自分でツマミつくって持参も大歓喜です
家に `お手製ベーコン` と `筍水煮` と `燻製オイル漬け牡蠣` があるので、これらも食べたければアレできます

**Comment by mrtry** [comment]
ストロングタピオカのメモ
https://sirabee.com/2019/06/16/20162099392/
https://www.amazon.co.jp/dp/B000FQOS6Q/ref=cm_sw_r_tw_dp_U_x_ZsCcDbB3PCJ38

**Comment by haze-it** [comment]
おつまみ、ローストビーフ適当に作るのと、行者にんにく味噌があるからそれ使って何か用意したい

**Comment by mrtry** [comment]
とりあえず、タピオカは買っておいた

**Comment by mrtry** [comment]
今の所のお品書き
- [ストロングレモンしゃぶしゃぶ](https://sirabee.com/2019/04/03/20162059342/)
- [ストロングレモンからあげ](https://sirabee.com/2019/01/21/20161969184/?FROM_WEBVIEW)
- [わさビーフ](http://negineesan.hatenablog.com/entry/2017/08/16/182527)
- [ストロングタピオカ](https://sirabee.com/2019/06/16/20162099392/)

ほか、ストロングゼロ関連メニューでも、普通に食べたいメニューでも、リクエストがあれば雑にくださいませ(当日の買い物までに知りたい)

**Comment by haze-it** [comment]
無事終了 :tada:

**Comment by mrtry** [comment]
お一人1923円です！！！！
オナシャッス！！！！
https://kyash.me/payments/OIn3l8km511WCQdaFwoppZi5xyFR

**Comment by mrtry** [comment]
感想
- ストロングレモンしゃぶしゃぶ: レモン鍋として普通。葉物がストロングゼロ吸って酔う感覚アリ
- ストロングレモンからあげ: ふつうに美味しい
- ストロングタピオカ: 午後ティ + ストロングレモン + タピオカ = 無限に飲めてヤバイ

**Comment by mrtry** [comment]
またやっていこうな
