### ISSUE TITLE
ウイスキーもくもく会

### ISSUE THREAD

**Issue by haze-it** [ngineerxiv/dark#106]
日時: `2019/07/27(土) 13:00 - 20:00ぐらい？`
場所: `LIFULL Fab - 東京都千代田区麹町1-4-4 1F`

出入り自由、適当にもくもくしましょうという感じです。
最後の1h〜2hぐらいで「やったこと」「やりたかったこと」を適当に話す＆雑談する時間を取っても良いかも。

### 経緯
<img width="309" alt="スクリーンショット 2019-05-20 11 35 02" src="https://user-images.githubusercontent.com/31850710/57993289-53052b00-7af3-11e9-887a-310fd908a86a.png">

はい
日程は後日、というか7月〜になるんじゃないかな

**Comment by noainoue** [comment]
私、気になります！🙋‍♀️

**Comment by udayan28** [comment]
私、気になります！:man-raising-hand:

**Comment by nasa9084** [comment]
私、気になります:man-raising-hand:

**Comment by sota1235** [comment]
私、気になります！:man-raising-hand:

**Comment by yamitzky** [comment]
私、気になります！:man-raising-hand:

**Comment by acchanAlexander** [comment]
![erutaso](https://user-images.githubusercontent.com/7720640/57993990-1850c200-7af6-11e9-98bd-1de702f42516.jpg)

**Comment by Udomomo** [comment]
大変なイベントができてしまった

**Comment by noainoue** [comment]
これ、いつ開催どす？？

**Comment by haze-it** [comment]
わ、わわわ、忘れてたわけじゃないのよ

**Comment by haze-it** [comment]
調整するやで
https://chouseisan.com/s?h=6ad5540e42b344239803fc6dcacdec26

**Comment by noainoue** [comment]
ありがとナス！

**Comment by haze-it** [comment]
6/29(土)がストロングゼロ飯なので **7/27(土)** で。結構先だしみんなカレンダー入れといてね

**Comment by udayan28** [comment]
これ、場所どうする？
どっかに会場借りる？

**Comment by haze-it** [comment]
どうすっか、〜8人ぐらいまでならうちでも行けると思うけど余裕が欲しいなら借りる

**Comment by haze-it** [comment]
スペースそのものはあるけど机は足りないだろうから借りるか

**Comment by acchanAlexander** [comment]
弊社使えないかみてみる

**Comment by Udomomo** [comment]
なんかボトル買っていく方がいいですかね

**Comment by udayan28** [comment]
好きなウィスキー（ボトル？）を持ち寄るのも良さそう

**Comment by haze-it** [comment]
おすすめのがあれば持ってきてくれると。量によってもくもくできるかどうかが変わります

僕はこれ https://www.amazon.co.jp/dp/B0119BPS7S

**Comment by udayan28** [comment]
https://hitokutiwhisky.com/

**Comment by acchanAlexander** [comment]
もし弊社使えたら、徒歩 3 分のところに酒屋がある
（いま聞いてる）

**Comment by Udomomo** [comment]
ミニボトルだと良いやつを気軽に味わえて良いですね。

個人的に好きなのはこれ https://www.amazon.co.jp/dp/B0049O2GAA

**Comment by udayan28** [comment]
私が好きなのはこれです。
https://amzn.to/2Xr1DcE

**Comment by ktanaka117** [comment]
参加はしないですが、僕が好きなのはこれです。甘めでまろやかで飲みやすい☺️
https://www.amazon.co.jp/dp/B001GLKBT2/ref=cm_sw_r_tw_dp_U_x_mW49CbVHYSHGT

**Comment by acchanAlexander** [comment]
場所、使えるとしたら 22:00 までなんだけどいいかな？
19:00 ~ やるとしたら、3時間くらいになっちゃうけど。

**Comment by haze-it** [comment]
くっそ適当に時間設定してたけど昼からで良いのではと思った

**Comment by acchanAlexander** [comment]
お、了解ー！
調整さんで 19:00 になってたからそうだと思った。

**Comment by haze-it** [comment]
:kami:

**Comment by acchanAlexander** [comment]
いま場所は相談中なんだけど、会社で行きたいっていう人がいて
数名連れてってもいいですか？

**Comment by haze-it** [comment]
草　いいんじゃなかろうか（結構ちゃんとしたイベントになりそうで趣旨通りになりそう？？？）
どう？ @udayan28

**Comment by udayan28** [comment]
草
ゆるーいイベントでただウィスキーを飲んでもくもくするだけで良ければって感じですw
（私に決定権あるんかw

**Comment by haze-it** [comment]
一応？発案者だから聞いてみた　適当にやっていこう

**Comment by acchanAlexander** [comment]
場所使えるようになった。

場所はここです。
https://fab.lifull.com/
弊社で運営してるコワーキングスペースのような場所です。
（3D プリンターとかレーザーカッターとかある、そういう系のコワーキング）

土日祝日休みってなってるけど、大丈夫です。
もちろん無料。

一点だけ、いまこのコワーキングスペースを広めようとしていて、
もくもく会の最初に 5 分くらい使って、説明だけさせてください。

**Comment by haze-it** [comment]
1Fのとこか、ありがとう！！！！！！！！！！！！！！！！！

**Comment by udayan28** [comment]
すごい！！！ありがとうございます！！！

**Comment by acchanAlexander** [comment]
ちなみに、徒歩 3 分もかからないところにある酒屋がこれです
https://www.yamaya.jp/pages/store/store/409kouzimati.html

**Comment by acchanAlexander** [comment]
会社の人
@y8yashi

**Comment by haze-it** [comment]
issueの説明を更新しました

**Comment by y8yashi** [comment]
こんにちは、会社の人です

**Comment by acchanAlexander** [comment]
あと、僕ら以外は当日いないので、その点ご心配なく

**Comment by acchanAlexander** [comment]
あとごめん、場所が 2F ってなってるけど、1F だわ。
間違ってるので修正お願いします。

**Comment by haze-it** [comment]
あ、やっぱそうだよね。外出たとこだよね確か

**Comment by Udomomo** [comment]
一瞬京都開催かと思ってびっくりした

**Comment by aq-nozomi** [comment]
あのあの、飛び入り参加は可能ですか？

**Comment by haze-it** [comment]
会場の広さが大丈夫なら？問題ないはず

**Comment by acchanAlexander** [comment]
広さ的には大丈夫！

**Comment by aq-nozomi** [comment]
わーい！

**Comment by acchanAlexander** [comment]
来週土曜ですよっというリマインド

**Comment by haze-it** [comment]
買いました
https://www.amazon.co.jp/gp/product/B0119BPS7S

**Comment by haze-it** [comment]
特定の企業の会場を借りているのと、「もくもく会」なので酒を飲みながら作業はできるだけやっていきたいという気持ちはあります。一応やりたいことを考えておくと良いかもしれない。二次会以降は知らん。警察や病院のお世話にならない程度にどうぞ

**Comment by acchanAlexander** [comment]
買い物メモ
- 炭酸
- 水
- 氷
- 軽いおつまみ
- コップ
- 皿

まぁすぐ近くに酒屋があるので、いつでも買いに行けます。

**Comment by aq-nozomi** [comment]
レモン、ポケットナイフ、ちっちゃいまな板的なヤツを持参予定です。
ポケットナイフはこちら
https://www.amazon.co.jp/dp/4622086042/ref=cm_sw_em_r_mt_dp_U_UDakDb556BB6C

**Comment by haze-it** [comment]
**ウイスキーもくもく会に来る人たちへ**
 - 一応もくもくするのが目的の一つなので何かしら作業用のPCとかは持ってきてね
 - 好きなor気になるウイスキーを持ってきてね、飲み比べしたい（数種類しかないとつらい）
 - コップとか氷とかは自分か @acchanAlexander か @udayan28 が用意するので↑だけ持ってきてくださいな
 - 13:00-開始、最初にacchanの説明があるので出来れば時間通りにきてくださいな

**Comment by acchanAlexander** [comment]
冷凍庫になるけど、調達できました！

**Comment by nasa9084** [comment]
何持って行こう(まず起きれるのか？)

**Comment by natsumican63** [comment]
キャパ大丈夫であれば参加したいす

**Comment by acchanAlexander** [comment]
キャパ大丈夫でっす！

**Comment by Omega014** [comment]
キャパ大丈夫そうであれば参加したいです！（真面目にもくもくする！

**Comment by Omega014** [comment]
もし参加できそうなら2.3年くらいまえに先輩にもらったやつが自宅に残ってたのでこれ持っていきます。ウィスキー飲めないマンだったのでどんなやつかは知らない。

ボトルキャップの上からサランラップぐるぐる巻きにして密閉してずっと日の当たらない場所で保存してたけど、さっき匂いかいだらめっちゃ甘いかんじになってた。美味しいかはわからない。

![Image from iOS (5)](https://user-images.githubusercontent.com/2178372/61771091-d7dd2f80-ae29-11e9-9100-3a090a3a7dd8.jpg)

**Comment by acchanAlexander** [comment]
キャパは大丈夫でござる！

**Comment by Udomomo** [comment]
土曜夜に台風が来そうですね...

**Comment by rnitame** [comment]
まだキャパ的に大丈夫そうなら行きたい〜。真面目に GraphQL いじります ^w^

**Comment by acchanAlexander** [comment]
キャパは大丈夫でござんす！

**Comment by acchanAlexander** [comment]
「台風」に発達　土日は関東などに接近　特徴と注意点
https://tenki.jp/forecaster/keiko_mochizuki/2019/07/25/5365.html
> 台風に発達した後は、進路を次第に東よりに変えて、土曜から日曜頃にかけて、関東甲信や東海など東日本の太平洋側に接近する恐れがあります。

もし危ない場合は無理して来ないようにお願いしますー！

**Comment by noainoue** [comment]
台風直撃したら私は不参加にします～！

**Comment by Udomomo** [comment]
台風の場合は家で飲むか...

**Comment by haze-it** [comment]
https://tenki.jp/forecast/3/16/4410/13103/
台風発生していますがそんな雨風強くならなさそうなので開催の予定です cc: @acchanAlexander

**Comment by aq-nozomi** [comment]
結局、27日ダメっぽいです…
かなc

**Comment by nasa9084** [comment]
がんばります(頑張れない可能性

**Comment by noainoue** [comment]
僕はいくよ、ウヰスキーのもとへ...

**Comment by acchanAlexander** [comment]
お疲れ様です
今日会場視察したのですが、最近壁の色を変えたらしく
ペンキの匂いがしますがご了承ください :bow:

あと、始まりのときにも説明しますが、今日総務に確認したところ
トイレに行くときだけ、本館に入るために僕が入り口でピッってするところまで
付きそうようにします。

**Comment by acchanAlexander** [comment]
会場行き方

麹町警察署のほうに行き、交差点を左に曲がります。
<img width="1246" alt="スクリーンショット 2019-07-27 13 30 51" src="https://user-images.githubusercontent.com/7720640/61990014-4bbe4880-b073-11e9-8fca-d8714e4e54ff.png">

1個目の交差点を左に曲がります。
<img width="1231" alt="スクリーンショット 2019-07-27 13 33 59" src="https://user-images.githubusercontent.com/7720640/61990023-67295380-b073-11e9-972c-7476debf6d43.png">

みえづらいですが、駐車場の左に入り口があります。
<img width="1239" alt="スクリーンショット 2019-07-27 13 31 51" src="https://user-images.githubusercontent.com/7720640/61990029-74464280-b073-11e9-9082-d7670429f940.png">

迷ったらメンションくださいー！

**Comment by acchanAlexander** [comment]
# 最初に話したこと
## 会場について
- 日頃、コワーキングスペースとして貸し出している会場です。
広めていきたいので、SNS でのシェアにご協力ください
https://www.facebook.com/lifullfab/
- トイレに行きたいときは、本館を使ってもらいます。
本館に入るためには、僕が持っているカードで開けなければいけません。
ので、本館に入るところまで僕がついて行きます。
トイレの場所は、案内します。
- 冷凍庫があるので、自由に使ってください。氷も入れています。
- Wifi は、僕に聞いてください。
- 会場は汚したりせず、常識の範囲ないでお願いね！（来たときよりも綺麗に！）

## 今日のイベントについて
- 18:00 に終わって、なにかしらやったことの報告会をします
19:00 には会場を出ようと思います。

## その他
徒歩 2 分くらいのところに酒屋があるので、何か欲しいものがあったら買いに行けます。
https://www.yamaya.jp/pages/store/store/409kouzimati.html
徒歩 30 秒のところに警察署があるので、何かあったらすぐに行けてしまいます。
https://www.keishicho.metro.tokyo.jp/about_mpd/shokai/ichiran/kankatsu/kojimachi/index.html

**Comment by haze-it** [comment]
進捗も記憶もないけど楽しかったのでOKです :+1:

会場提供あっちゃん LIFULL社ありがとう〜
あとお酒持ってきてくれた人たちもありがとう
