### ISSUE TITLE
みんなで半休を取って串カツ田中のハッピーアワーを堪能する会

### ISSUE THREAD

**Issue by haze-it** [ngineerxiv/dark#108]
思いついただけ　誰かハンドリングして

https://kushi-tanaka.com/news/entry/980

**Comment by haze-it** [comment]
https://chouseisan.com/s?h=658509af69074ee69497dfc12b78ff0c

**Comment by sota1235** [comment]
誠意見せました

**Comment by mrtry** [comment]
泥酔太郎

**Comment by Omega014** [comment]
チンチロ何回できるかな♪

**Comment by haze-it** [comment]
補足：渋谷の田中は16:00オープンなので16時開始の予定

**Comment by mrtry** [comment]
18時前集合だと食べ放題がある
会計まとめるの面倒だし、これを人数分予約するのアリかもしれない

https://kushi-tanaka.com/campaign/party/#zentabeho
- サイド含め食べ放題:2,180円
- 串カツ食べ放題: 1,480円

**Comment by haze-it** [comment]
プレミアムフライデーであるところの **7/26(金)** が有力　なお翌日 https://github.com/ngineerxiv/dark/issues/106

**Comment by haze-it** [comment]
串カツ田中、明日予約するやで
メンバーは @sota1235 @mrtry @Omega014 @haze-it でいいですか（来れなくなった or 参加したい等あったらコメントください）

**Comment by rnitame** [comment]
2 次会的なイベントがあったらいきたい

**Comment by haze-it** [comment]
ほぼ全品食べ放題  渋谷宮益坂店
7/26 16:00- 3名で予約しました🙌
@mrtry @Omega014

**Comment by haze-it** [comment]
無事帰宅
突然メンバーが増えたりゲストが来たりしましたが楽しかった、ありがとう〜〜
