### ISSUE TITLE
dark花火

### ISSUE THREAD

**Issue by haze-it** [ngineerxiv/dark#109]
花火したい！！！！！！！！！！！！！！！！！！！！！
@udayan28

日時: 8月10日 夕方ぐらいから
場所: 世田谷公園
参加者: https://chouseisan.com/s?h=ff452cca828446838cf6c157540b3ddf 参加したい人いたら適当にどうぞ
必要な道具: バケツ / チャッカマン / 花火 

参加希望は適当にコメントとかslackして

**Comment by acchanAlexander** [comment]
いえーい！

**Comment by udayan28** [comment]
場所の候補、今のところ、とらい氏宅か。

**Comment by mrtry** [comment]
絶対火災保険に引っかかるからダメ

**Comment by ara-ta3** [comment]
こんなのみっけた
https://travel.navitime.com/ja/area/jp/guide/NTJmat0492/

**Comment by Omega014** [comment]
線香花火買いました！
![Image from iOS (2)](https://user-images.githubusercontent.com/2178372/60793666-18d71200-a1a3-11e9-94ea-e867297c3ce0.jpg)

**Comment by mrtry** [comment]
やってくぞ

**Comment by haze-it** [comment]
https://chouseisan.com/s?h=ff452cca828446838cf6c157540b3ddf

:seiihakotobadenakutyouseisan:

**Comment by haze-it** [comment]
@各位
8月10日で！！！！！！！！！！！！！！！！！！！！！！

**Comment by haze-it** [comment]
弊彼女参戦予定（？）

**Comment by ara-ta3** [comment]
同じく参戦予定です

**Comment by cocodrips** [comment]
参戦したい

**Comment by igayamaguchi** [comment]
釣りに行ってるううううううううはぜさんの彼女みたいいいいいいいいいいいいいいいいい

**Comment by mihyaeru21** [comment]
いきたみ

**Comment by acchanAlexander** [comment]
調整さんでは丸になってたけど、予定入ってしまった ><
hazekano と arakano みたかったあああああああああああああ

**Comment by aq-nozomi** [comment]
wei!

**Comment by udayan28** [comment]
https://twitter.com/amado_tech/status/1151101681414934529

**Comment by ktanaka117** [comment]
いく

**Comment by natsumican63** [comment]
夫と共に行きます(たぶん)

花火は持ち寄りスタイル？誰かがまとめて買ってくる？

**Comment by haze-it** [comment]
必要なもの（共用）
 - バケツ *2
 - チャッカマン *3

各自持ってきてほしいもの
 - 花火
 - 虫除けスプレーとか蚊取り線香
 - 椅子（？）
 - ライト、懐中電灯があれば

バケツとチャッカマンは1つずつ用意します、持ってる人いたらコメントしてほしい

**Comment by haze-it** [comment]
```
バケツ: haze, try
チャッカマン: haze, udayan
ろうそく: udayan
```
二人ありがとう〜〜よろしくです
花火とか他持ってきたいものあれば各自よろしくです
**17時ぐらい**から始める予定？でいます、0次会、2次会は自由にどうぞ

**Comment by cocodrips** [comment]
花火買ってく、同伴者1

https://www.city.setagaya.lg.jp/mokuji/kusei/012/015/001/001/d00127318.html
>【騒音】打ち上げ花火、爆竹等の大きい音の出る花火
静かなやつならいいのね

**Comment by haze-it** [comment]
花火は各自持ってきてもらえると。余ったら適当に持って帰るか誰かが集めるか
自分も同伴者1、浴衣着ていきます

**Comment by igayamaguchi** [comment]
元気があったら海の帰りに寄るかもしれない

**Comment by igayamaguchi** [comment]
あ、同伴者はいないです

**Comment by cocodrips** [comment]
都会ってどこに花火売ってるんだ。田舎はスーパーに売ってるけど・・・

**Comment by udayan28** [comment]
ドンキ？

**Comment by mihyaeru21** [comment]
大変心苦しいですが同伴者なしです

**Comment by ara-ta3** [comment]
最高だったんでまた来年もやりたいですね
結構歩いて大変だったと思うので、渋谷から来るバス停をメモったマップ作っときますた

https://www.google.com/maps/d/u/0/viewer?hl=ja&hl=ja&mid=1DHxXuygdbpJKxqds-9f3n0YplzKOzWTz&ll=35.64588420125507%2C139.68390360080264&z=15

**Comment by haze-it** [comment]
楽しかったね、あらたさん二次会会場ありがと

世田谷公園情報
 - 木が生えているとこの下は結構暗い
   - 懐中電灯があると良い
 - 風でろうそくが一瞬で消えるので対策が必要、どうすればいいんだろうねこれ
 - 噴出花火は使用可だけど爆発音がなるやつは巡回している警察に怒られるので注意、買うときに気をつける
 - レジャーシートは最寄りの100円ローソンで

**Comment by ara-ta3** [comment]
自分のと見かけた写真でアルバム作っときますた
https://photos.app.goo.gl/TzzudAF4pwDDEpQT8

**Comment by haze-it** [comment]
またらいねん！

**Comment by ara-ta3** [comment]
精算用spreadsheet
https://docs.google.com/spreadsheets/d/1u_oWPgCikM6C7lQPG6l9yDsbss3aycbqWCLW7m8JMJ0/edit?usp=sharing
