### ISSUE TITLE
pokemon goで痩せる

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#11]
歩く、痩せる、ポケモン捕まえる、たのしい

最高では！！！！

わたしはゼニガメを選びました！
ええ！！！見た目重視派です！！！

調整さん
[ https://chouseisan.com/s?h=fde99b15766e40fb87a210beb6e802a2 ]

**Comment by jp-taku2** [comment]
参加します！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by TasukuNakano** [comment]
参加する人は初期ポケモンに何を選んだか書いていこう

**Comment by jp-taku2** [comment]
フシギダネです！！！

**Comment by hoto17296** [comment]
ポケモンGOイベント、やるなら明日(土)しかないので
乗るしかない、このビッグウェーブに

(初期ポケモンはピカチュウです)

**Comment by TasukuNakano** [comment]
わいもピカチュウです

**Comment by mihyaeru21** [comment]
ワイヒトカゲ

**Comment by papix** [comment]
ワイ将, フシギバナ

**Comment by gomayumax** [comment]
ひとまず7/30 11:00でいいですか

**Comment by ara-ta3** [comment]
23日にやったのでclose？

**Comment by gomayumax** [comment]
一応やるー
ただちょい飽きてきたので、
ポケモン課金アイテム総放出祭します

**Comment by jp-taku2** [comment]
上野公園と御苑と世田谷公園に行こう！

**Comment by gomayumax** [comment]
御苑に11時！！！！
ポケモンしてお昼食べてもくもく行こう

**Comment by hoto17296** [comment]
お台場に行きたいんですが(コイルとかビリリダマの巣

**Comment by ara-ta3** [comment]
大体終わったっぽいのでclose
