### ISSUE TITLE
読書会

### ISSUE THREAD

**Issue by igayamaguchi** [ngineerxiv/dark#113]
### 概要
みんな積読しているものとかを雑に集まって読もうの会
終わったらてきとーにアウトプットできるといいね
参加者求ム

### 開催場所
一休 最寄りは赤坂見附 or 赤坂
https://www.google.com/maps/place/%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE+%E4%B8%80%E4%BC%91/@35.6752943,139.7378198,15z/data=!4m2!3m1!1s0x0:0x150f3c6932e914bc?sa=X&ved=2ahUKEwjt4KCokvLjAhVtFqYKHXCoCqwQ_BIwC3oECAwQCw

### 開催日時
多分8/17

**Comment by haze-it** [comment]
たぶんいく

**Comment by Udomomo** [comment]
今のところ行けそう

**Comment by cocodrips** [comment]
いきたい

**Comment by udayan28** [comment]
いく予定

**Comment by igayamaguchi** [comment]
時間どうしようかー
13:00くらいから？

**Comment by cocodrips** [comment]
13:00~よい　それなら　ねぼうしない

**Comment by haze-it** [comment]
私用が入ったのでいけなくなった、すまん :sob:

**Comment by Udomomo** [comment]
明日ですね

**Comment by igayamaguchi** [comment]
13～19時でスペース取っています。
参加者は一休東京本社の7階にお越しくださいませ～

**Comment by igayamaguchi** [comment]
7階上がって右奥のラウンジスペースです。
7階はそこのスペース以外は他社なのと、土曜も一部社員がいるのだけご留意ください 🙏

**Comment by igayamaguchi** [comment]
とても進捗出ました。
またやりましょう
