### ISSUE TITLE
今日、赤坂見附で飲み/ご飯に行く

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#115]
集まらなかったらひっそりとclosedします

行くって人はなんかこうアピールして欲しい

日時8/13 20:00-

**Comment by nasa9084** [comment]
赤坂見附、微妙にアクセスが・・・・って思ったけど思ったよりアクセス悪くなかった(電車一本で帰れそう)ので行きます

**Comment by ktanaka117** [comment]
いくあ

**Comment by igayamaguchi** [comment]
赤坂見附、赤坂駅や永田町駅も近いのでご検討ください

**Comment by acchanAlexander** [comment]
いくぁ

**Comment by gomayumax** [comment]
なんかよく分からないけど楽しかったです！！
またお付き合いください！！

チャペルカンファレンスやりたい💒
