### ISSUE TITLE
星野リゾート BEB5に泊まりに行きたい

### ISSUE THREAD

**Issue by mrtry** [ngineerxiv/dark#116]
最高そうなところなので、いきたい
スケートも焚き火も温泉もある
一部屋素泊まり3人で5,400円らしい

土日は混むらしいので、早めにとるか、有休でアレしたい

# 関連リンク
- [星野リゾート BEB5 軽井沢【公式】 \| Hoshino Resorts BEB5 Karuizawa](https://beb-hotels.com/karuizawa/)
- [BEB2最高というツイート](https://twitter.com/mmooti_trip/status/1177168582540578816?s=20)
- [【口コミ】星野リゾートBEB5軽井沢に泊まってきた。35歳以下はリーズナブルな価格で泊まれるホテル。 \| ゆいごこち](https://disneyume.com/archives/8147)

**Comment by gomayumax** [comment]
土->日は割と埋まっている様子を観測した
日->月が狙い目そう

**Comment by acchanAlexander** [comment]
ほっしーの！

**Comment by gomayumax** [comment]
突然ですが！！！
3/1(日)-3/3(火)で行きます！！！
1人でも行きます！！！！！！

ともあれ
誰か一緒に行く人いたら行きましょう！！！

女性なら同じ部屋に泊まりましょう！！
一部屋15000円決め打ちなので
2人なら7500円
３人なら1人5000円の宿泊費になります！！

1/31(金)まで同室宿泊者募集。

同室でなければ、期限なしで待ってます！！！！！！一緒にくつろぎ旅行しましょう！！！

**Comment by gomayumax** [comment]
いろいろあり、一泊二日にしたぞ！！！

3/1(日)-3/2(月)で
のあし、おめがし、ごましで泊まるぞ！！！

焚き火でマシュマロとベーコン焼いて地ビールで乾杯

**Comment by gomayumax** [comment]
## つまみの調達
- ハム・ベーコン
   - 駅近にそういう店がある [腸詰屋](https://www.chozumeya.jp/)
- チーズ
  - 駅近くにそういう店がある [軽井沢チーズ熟成所・売店（ショップ）](https://www.a-fromage.co.jp/archives/shop/karuizawa/)

## 酒
- 近くにセブンイレブンがある
- ホテル
    - 量り売りのワイン
    - クラフトビールや地ビール

**Comment by gomayumax** [comment]
めっちゃ楽しかったです!!!!!

仲間と行くと本当に楽しい！
新幹線で1時間、お値段も安いし、周辺施設のコンテンツも豊富なので
ぜひみんな行ってみて欲しい!!!

`~fin~`
(close出来ないので誰かcloseしてくれ)

**Comment by Omega014** [comment]
@mrtry これIssue作成者しか閉じれない可能性ある

**Comment by mrtry** [comment]
`~fin~`
