### ISSUE TITLE
GomaConf #2 with baby

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#122]
# 日時
11/30(土) 16:00-21:00

# 場所
会場: 東急田園都市線「池尻大橋駅」より徒歩3分
	東京都目黒区目黒区東山3-6-1 (map: https://goo.gl/maps/3oG4NFx2pcJRaUyE9 )

https://www.spacemarket.com/spaces/ohsv9nhemorj0pf9/rooms/0PtMaw0R1Y5xpOEl

取説: http://spacemole.co.jp/guide/fika_ikejiri.pdf
ゴミについて: ベランダのところの箱にシュート
会場費: 17,259

```
https://github.com/ngineerxiv/dark/issues/122#issuecomment-539809107

> spacemarketで部屋借りたら私とトライ氏がコストコ行って食材を調達し皆さんに美味しいご飯を作ります（やりたいこと全部詰めた）

コレ優勝
```

# 参加者
現時点: 12名

- goma
- hoto 
- mrtry
- mihyaeru
- nasa
- haze
- omega
- jp_taku
- Notz
- natsumican
- udayan
- iganin

**参加表明してくれ!!!!!!!!!!**

**Comment by mrtry** [comment]
表明！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by mihyaeru21** [comment]
参加のお気持ちを表明します

**Comment by nasa9084** [comment]
現時点で、だけど参加のお気持ちを表明します

**Comment by haze-it** [comment]
参加登録

**Comment by Omega014** [comment]
spacemarketで部屋借りたら私とトライ氏がコストコ行って食材を調達し皆さんに美味しいご飯を作ります（やりたいこと全部詰めた）

**Comment by hoto17296** [comment]
自分が夕方まで予定があるので17時スタートにしたけど、場所借りるならもっと早くからやっていてもらっても大丈夫そう

**Comment by gomayumax** [comment]
spacemarket 候補
- 渋谷 ハンズ近く https://www.spacemarket.com/spaces/25n8zrkzkoyq_pm6/rooms/of2UVEaUR9BNGULf

**Comment by mrtry** [comment]
コストコ入場券6人分あるので、自分とおめが氏抜いたら4人参戦可能

**Comment by jp-taku2** [comment]
airbnbとかで大きいとこ借りてしまえばそのまま。。。

**Comment by aq-nozomi** [comment]
表明！！
(宣誓:自己管理に大変気をつけます。)

**Comment by natsumican63** [comment]
参加したいー！

**Comment by udayan28** [comment]
参加！！！

**Comment by gomayumax** [comment]
spacemarketで15人くらい入る場所を借りればいい気がしてきた

**Comment by gomayumax** [comment]
そろそろ場所抑えちゃおうと思う

候補

- 渋谷: https://www.spacemarket.com/spaces/25n8zrkzkoyq_pm6/rooms/of2UVEaUR9BNGULf
- 新宿: https://www.spacemarket.com/spaces/zy8quveyxhko5bsq/rooms/lq6MfjdvsPsnMLPG


コストコ組的に、会場都合がいいところあれば言ってほしい

**Comment by gomayumax** [comment]
予約done


会場: https://www.spacemarket.com/spaces/ohsv9nhemorj0pf9/rooms/0PtMaw0R1Y5xpOEl
時間: 16:00-21:00 (片付けとかバタつくと思うので長めに)

**Comment by gomayumax** [comment]
コストコ可能参加可能人数: 9人

内訳:
すずたくチケット: ３人
とらい氏チケット: 6人(このチケットはメルカリにてゲット予定)

**Comment by igayamaguchi** [comment]
参加！

**Comment by igayamaguchi** [comment]
コストコは行ってみたいけど車乗れそうだったらでOKです！

**Comment by hoto17296** [comment]
お金支払い先まとめ

> goma
> 会場代: 17,259円
> 1人1,438円
> kyash:  gomaaburamax

https://ngineerxiv.slack.com/archives/C1G9NUU2D/p1575118951378300

> mrtry
> コストコ: 29771円
> 一人: 2480円
> プロシュートチーズ買った人: +1588円
> だし(おめが氏: +1598円
> kyash: mrtry

https://ngineerxiv.slack.com/archives/C1G9NUU2D/p1575111241370200

> omega
> 調味料、酒代は私持ちだったので以下のアカウントまで支払いお願いしやす！
> 合計5252円
> 一人:477円
> kyash: omega014

https://ngineerxiv.slack.com/archives/C1G9NUU2D/p1575121148384400

> jp_taku
> レンタカー+ピザ代+etc
> 15290+1580+2050=18920円
> 1人 : 1576円 
> kyash: jptaku2

https://ngineerxiv.slack.com/archives/C1G9NUU2D/p1575156178393800

**Comment by gomayumax** [comment]
お金周りもう大丈夫だよね？

良き回でした
