### ISSUE TITLE
なんかキッチンスペース借りて料理しながらハッカソンする

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#13]
https://ngineerxiv.slack.com/archives/cooking/p1471243880000333

**Comment by ara-ta3** [comment]
https://spacemarket.com/spaces/utnakameguro/rooms/L4iCz7UnYkcNe7r4

https://spacemarket.com/spaces/rwC7TO3IIPo5mXw2/rooms/Rkvy0fYpDKVf-6bM

https://spacemarket.com/spaces/sancharentalspace/rooms/-pD6QGQ7tbPTCVhr

A社で良さそうだけど、会社の先輩が見つけていたところをついでに貼っておく

**Comment by papix** [comment]
狩りもしたい

**Comment by gomayumax** [comment]
A社でもいいけどなんて説明したら良いのかわからないので
可能性30％くらいにしておいてほしい

**Comment by takumi-suzuki** [comment]
A社はね空いてれば、mokumoku会で使いたいって言えば使える。
とR社の僕が言う。

**Comment by ara-ta3** [comment]
これどうするんだっけｗ

**Comment by Omega014** [comment]
ハムのイベントとがっちゃんこするという案が浮かんだ

**Comment by ara-ta3** [comment]
これどうするんだっけ感
やりたくなったらまた立てよう
