### ISSUE TITLE
大乱闘で最強を決める(ただしWiiU)

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#14]
- 我が家にて大乱闘で遊ぶ
- 酒飲みながら大乱闘で遊ぶイメージ

**Comment by ara-ta3** [comment]
明日あたり調整さん立てよう

**Comment by ara-ta3** [comment]
やりたい人が4人以上あつまったらやっていきたい
なければcloseの気持ち
https://chouseisan.com/s?h=88de63b9c5cd48aa8af89f752d9931ce

**Comment by sota1235** [comment]
ktkr

**Comment by mrtry** [comment]
わぁい

**Comment by acchanAlexander** [comment]
よっしゃ

**Comment by ara-ta3** [comment]
4人きた
5日もくもくしたいから外していきたくて19日にしようかと思ってるんだけど、
kirin氏は何時頃ならいいのだろう

**Comment by sota1235** [comment]
19日昼なら行けやす！！

**Comment by ara-ta3** [comment]
19日昼からで決定かな
14:00 ~ にしてたけど、13:00~とかの方がいいかな
何時からが良いのだろうコメントあると気持ちが楽です

**Comment by sota1235** [comment]
13時に1票！

**Comment by acchanAlexander** [comment]
13時に1票！

**Comment by mrtry** [comment]
どちらでも参加します！

**Comment by ara-ta3** [comment]
じゃあ19日13:00 我が家集合で！
住所はslackで〜

**Comment by acchanAlexander** [comment]
当日眼科行ってから向かうので、込み具合によっては遅れていくかもです ><

**Comment by ara-ta3** [comment]
やったこと

- ひたすら2~3人で4人大乱闘
- (4人集まってから) ひたすら8人大乱闘
  - スモークチーズとワイン最高でした。トライ氏ありがとう！ @mrtry ++ 
- ひたすら 4人間 VS  4CPU LV9 
- 課金して全隠しキャラ+ステージ出す
- イベント戦

計測は出来てないので誰が最強かわからなかった。
なので最強の決定は次回に持ち越し←

LV3に負けてる人たちの様子…

![image](https://cloud.githubusercontent.com/assets/2089153/20456505/1d6ff8b4-aebb-11e6-9628-6363a5d53ecf.png)

スモークチーズの様子

![image](https://cloud.githubusercontent.com/assets/2089153/20456499/133bf258-aebb-11e6-8ac1-472260a558fe.png)
