### ISSUE TITLE
温泉開発合宿したい

### ISSUE THREAD

**Issue by Omega014** [ngineerxiv/dark#15]
# 目的
- 温泉旅館で開発合宿する
- 自分の職場以外の様々なスキルを持った人と開発をすることでお互いの技術力を高める
- 限られた時間内で1つのプロダクトを作ることで機能を選定する技術を鍛える
- まぁ、四半期に一回はどこか旅行とかしたいじゃん？
# 旅行前にやること
- [ ] 参加者を集める
- [ ] 開催日時を決定する
- [ ] 温泉旅館の予約をする
- [ ] 合宿中の旅程を決定する

**Comment by Omega014** [comment]
なんとなく温泉合宿とか楽しそうだしやってみたいな〜〜とか言ってたらイベントたてることになったぞ

なお8月からそんなに経ってないので気分的に11月にやりたいです

**Comment by ara-ta3** [comment]
![image](https://cloud.githubusercontent.com/assets/2089153/20438067/88210ce2-adf9-11e6-8d94-9be531231b48.png)

**Comment by Omega014** [comment]
言ったは良いがこれ特に進捗無いですな。
来年開催くらいにしよう。ということで一旦閉じ。
