### ISSUE TITLE
おまえらあああ！！チーズに溺れたいかーーーーーー！！！

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#18]
http://www.cheesefesta.com/

チーズフェスタがあるそうです
# なんとなく予想される流れ

**11/12(土)**

12:00 チーズフェスタ
会場: 恵比寿スバルビル
|
14:00 ほとごま家
チーズとワインでうぇい

参加表明
調整さん : https://chouseisan.com/s?h=b31a0fa675e543528e9b95446396c921

**Comment by ara-ta3** [comment]
![image](https://cloud.githubusercontent.com/assets/2089153/19621555/3ee5f8a6-98cf-11e6-8ea8-7e28f2b8dc86.png)

**Comment by papix** [comment]
![https://pbs.twimg.com/media/B7fKhYbCIAAwWqV.jpg](https://pbs.twimg.com/media/B7fKhYbCIAAwWqV.jpg)

まずうちにさあ... ラクレット焼く機械, あんだけど... 焼いてかない?

**Comment by ara-ta3** [comment]
そういえばバスケがないって言われていけると思ったら
やっぱりありますと言われたのでいけなくなりますた… :rolling:

**Comment by gomayumax** [comment]
悲しみのclose
