### ISSUE TITLE
安西先生・・・バスケが・・・したいです・・・会

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#19]
中目黒公園にバスケしにいこう
http://www.city.meguro.tokyo.jp/shisetsu/shisetsu/koen/nakameguro.html

帰りに銭湯でも行くと良さそう
http://kohmeisen.com/

そのまま近くで飲んで最高の休日体験
一旦12月だけ
https://chouseisan.com/s?h=c2f1063fa11f4d86a308af0447296b5d

**Comment by sota1235** [comment]
銭湯最高か！！最高か！！！

**Comment by ara-ta3** [comment]
12/10, 12/11 が良さげだったのでとりあえず `12/10(土) 13:00` に中目黒駅集合的な感じかな
もしバスで来る場合は13:30 に現地集合の方が良いのかも？(とくにきりん氏あたり？

**Comment by ara-ta3** [comment]
`12/10` ボブバスケかぶったねｗ

**Comment by sota1235** [comment]
12/10 13時よかです！
現地集合でも全然可です 🙆

**Comment by TasukuNakano** [comment]
12/10(土) 13:00 了解です 🙆‍♂️ 

わい、銭湯行った後にまた戦闘(ボブバスケ)いきまする

**Comment by ara-ta3** [comment]
昼から行く感じになってたけど12/10昼やる？
中目黒の公園行くと人数がいればずっとゲームやることになりそうだから
夜のボブバスケ死にそうとかひよってる

**Comment by sota1235** [comment]
ずっとゲームになると聞いて、昼は英気を養うに一票です 😭

**Comment by TasukuNakano** [comment]
>中目黒の公園行くと人数がいればずっとゲームやることになりそうだから

これって知らない人も含めてってこと？
(ちょっとそういうのやってみたい)

**Comment by ara-ta3** [comment]
> これって知らない人も含めてってこと？

そうそう
楽しいは楽しいぞい

**Comment by TasukuNakano** [comment]
やりたい
「お前どこ高だよ？」
「くっ…やるな…！」
とかやりたい(やらないけど)

**Comment by ara-ta3** [comment]
じゃあ強気に昼から行くかぁー

**Comment by ara-ta3** [comment]
強気に昼からいったけど、少し休めば夜からのバスケも問題なさそうだった。
ただ、寒すぎて気管をやられた感あるので、なんらかの対策が欲しそうだった。
あと筋肉痛がやばい。

銭湯はちょっとぬるかったけどさくっと行けてよかった。
https://twitter.com/ara_ta3/status/807487612231352320
https://twitter.com/task1010243/status/807487839495602177

また1月あたり出来たらやりませう。
