### ISSUE TITLE
東北新幹線で行く ぶらり仙台旅行

### ISSUE THREAD

**Issue by Omega014** [ngineerxiv/dark#2]
# 目的

- [仙台七夕祭り](http://www.sendaitanabata.com/)に参加する
- takuの実家の縁側でスイカを食べる

# 日程
8/6, 7, 8 の2泊3日

### 8/6(土)

* 東京駅に9:30集合
  * 待ち合わせ場所
  * https://goo.gl/maps/asGyRxtagRQ2
* hotoかgomaに新幹線代金を渡す（往路11,400円/復路8400円）

* 新幹線乗る
  * 東北新幹線 こまち 51号
  * 10:04 東京駅発 ー 11:39 仙台駅着

- ~13:00 仙台駅付近で昼ごはん
- A: 13:20 ~ 17:00 （初めて仙台に来た人向け）
  - 瑞鳳殿 (政宗様のお墓。ちなみにこの日は七夕祭り仕様で夜には竹灯篭が光る。)・・・るーぷるというバスで移動
  - 仙台城跡 (政宗様の銅像があるところ)・・・地下鉄東西線 国際センター駅で降りる
  - https://github.com/ngineerxiv/dark/issues/2#issuecomment-231183497
- 17:00 ~ 23:00
  - 仙台七夕まつり [七夕マップ] ← 本来はこれに参加したいだけでイベント立てた
  - ご飯適当に七夕祭りので店でもいいし居酒屋でもいいしみたいな
  - 温泉 ← たくの家の場所ぼんやりとしか覚えてなかったのでどの辺りで温泉入るとベストなのか決めかねた
  - 風呂
    - 第一候補
      - https://goo.gl/maps/Luk6YKz5Ts62
      - 祭りが近くて混む可能性がある
    - 第二候補
      - https://goo.gl/maps/vL4Y5CgbkBE2
    - 第三候補
      - https://goo.gl/maps/S7srXhFFLT92
    - 第一候補.new
      - https://goo.gl/maps/n11oo14YCgq
      - 白石駅付近（すずたく家付近）
      - 21:30 まで
      - 仙台を20:00くらいまでに出ないといけない
      - 20:32の電車しかなさ気だから時間を気をつける
- 22:00 ~ 22:30 くらいに温泉あがる
- 23:00 頃に仙台駅合流

### 8/7(日)

**メモ**

* 車で移動して東北を観光する
* 日帰りはキツいのでどこかで一泊する
* 前回上がっていた行きたい場所
  * 温泉
  * 鍾乳洞
  * チーズ工場

**予定**

- 9:00 
  - 白石蔵王駅前 に レンタカーを取りに行く
  - 19,980 / 7 = 2855円/人 をjp_takuに払って下しあ
- ~12:00 
  - 御釜 蔵王に行く
  - 13:00 蔵王酪農センター ←譲らないぞ
    - チーズ食べたい！ピザ！ちーずけーき！ヒルメシ！
    - カッテージチーズ手作り体験したい！(所用時間30分)
- 15:00 猪苗代湖のほうまで来る
  - いろいろする
    - 温泉入ったりなんだり
-コテージに宿泊
  - チェックイン 13:30 ~ 16:00 まで
    - http://www.cottage.co.jp/
    - [コテージ予約情報](https://ngineerxiv.slack.com/files/omega/F1QPDFS67/____________________________________.txt)
    -  39,680(コテージ代)+2,000(バーベキューセット代) / 7 = 5955円/人をomegaに払って下しあ
  - このへんでブラブラしつつコテージ行って酒飲んでいい感じに楽しむ
  - http://www.bandaisan.or.jp/

### 8/8(月)

* 郡山駅西口 レンタカー返却する
* jp_takuとバイバイする
* papiは別ルートで帰宅する
* 郡山 17:30発の新幹線に乗車
* 東京 18:48着、解散

おうちに帰るまでが旅行ですよ！！

# 3日目

- 10:00 出発
  - おそらく大体チェックアウト時間
- 13:30 くらいまでぶらぶらする
- 13:30 猪苗代湖付近出発 
- 15:00 あぶくま洞
  - http://abukumado.com/
- 16:00 あぶくま洞終了
- 17:30 郡山から新幹線出発
- 18:48 東京着

# 新幹線代金について

### 往路

クレカ王子のhotoが一括で予約してくれました。
当日までに往路 11,400円を払ってね！

### 復路
大天使ミヒャエルさまが予約してくれました。
旅行中に 復路 8,400円を払ってね！

# 参加予定者
- 団体行動出来ないマンomega
- jp_taku(6日は友人と遊ぶため7日から案内してくれるってよ!)
- カヌレが食べたいarata氏
- 大天使ミカエル(mihyaeru21)
- ベンゼンのほうのgoma
- 知性のpapixくん
- 実は下鴨矢家一族hoto

**Comment by Omega014** [comment]
参加希望の人は各自参加予定者に名前入れてくれ

**Comment by mihyaeru21** [comment]
👍

**Comment by gomayumax** [comment]
行く

**Comment by papix** [comment]
行きたい

**Comment by urataku** [comment]
行けたら行きたい(7末締めのものの状況による)

**Comment by Omega014** [comment]
東北新幹線の予約は1ヶ月前から。
割とすぐに埋まりそうな気がするので、当日になったらすぐに予約することをお勧めする。

東京 ⇄ 仙台 
* [えきねっと ](https://www.eki-net.com/pc/personal/yoyaku/wb/Common/ReserveTop/ReserveTop.aspx)

あ、行き帰りの出発時刻決めないとな。来月頭にみんなと相談する。

**Comment by hoto17296** [comment]
(参加表明してなかったけど行きます)

**Comment by jp-taku2** [comment]
最終出社が5日になったから、僕もみんなと一緒に行くー

**Comment by ara-ta3** [comment]
払い戻しの話
http://eki-net.okweb3.jp/EokpControl?&tid=10777&event=FE0006

**Comment by ara-ta3** [comment]
キャンセルの注意点
http://eki-net.okweb3.jp/EokpControl?&tid=10783&event=FE0006

**Comment by urataku** [comment]
おっと危ない、おそらくアウトっぽいのでキャンセルします…orz

**Comment by Omega014** [comment]
前回話したとき(だいぶ時間経ってるけど)にあがっていた行きたい場所リスト

* 温泉
* 鍾乳洞
* チーズ工場
*

**Comment by jp-taku2** [comment]
朝一での温泉は必須な気がする。
前日、帰るの遅いから風呂は入れないはず

**Comment by Omega014** [comment]
こんな感じの旅程だったらぼくが最高というのをポストしておく


## 1日目

* 12時頃に仙台駅に着く
  * 仙台駅周辺で牛タン食べる！

* A: 13:20 ~ 17:00 （初めて仙台に来た人向け）
 * [瑞鳳殿](http://www.zuihoden.com/) (政宗様のお墓。ちなみにこの日は七夕祭り仕様で夜には竹灯篭が光る。)・・・るーぷるというバスで移動
 * [仙台城跡](http://www.sendaijyo.com/) (政宗様の銅像があるところ)・・・地下鉄東西線 国際センター駅で降りる

* B: 13:30 ~ 17:00 （ぼくの希望）

  * [地底の森ミュージアム](http://www.city.sendai.jp/kyouiku/chiteinomori/)
  * [仙台市電保存館](http://www.sentabi.jp/guidebook/attractions/view/14)

* 17:00 ~ たくと合流してたく家に帰るまで

  * [仙台七夕まつり](http://www.sendaitanabata.com/) [[七夕マップ](http://www.sendaitanabata.com/img/map/2016_streetmap.pdf)] ← 本来はこれに参加したいだけでイベント立てた
  * 温泉

# 2日目

* 10時くらいたく家出発
* 10:30 ~ 12:00 [蔵王酪農センター](http://www.zao-cheese.or.jp/) ←譲らないぞ
  * チーズ食べたい！ピザ！ちーずけーき！ヒルメシ！
  * [カッテージチーズ手作り体験](http://www.zao-cheese.or.jp/taikenindex.html)したい！(所用時間30分)

~ ここから夢のある分岐 ~ 

## Aコース

山形市内観光コース

* 14:00 山形市内
* 14:20 ホテル着 車置いていく（山形市内のホテルか宿てきとーにどこか予約する）
* あとは山形市内観光
  * [山形県郷土館 文翔館](http://www.gakushubunka.jp/bunsyokan/)
  * [霞城公園](http://kankou.yamagata.yamagata.jp/db/cgi-bin/search/search.cgi?panel=detail&d01=877)
  * 
* 18:00 ~ 
  * 米澤牛食べたい！！！

## Bコース

米澤牛食べたいコース

* 14:00 米沢市の宿に到着　車置く
  * 宿
    * [小野川温泉](http://www.onogawa.jp/index.html/) （米澤駅からバスで20分くらいのところにある）
    * 米澤市内のホテルか宿てきとーにどこか予約する

* 14:20 ~ 市内観光
  * [酒造資料館 東光の酒蔵](http://www.tokonosakagura.com/index.php) 酒の試飲とか最高です
  * 米沢城跡
  * [上杉家廟所](http://uesugigobyo.com/)
  * 
* 18:00 ~
  * 米澤牛食べたい！！！


## Cコース

このルートは宿が取れない可能性あるのでほぼ無い

* 17:30 宿に到着
  * [銀山温泉](http://www.ginzanonsen.jp/) (大部屋でみんなで寝るなら部屋空いてた所)
    * [旅館 永澤平八](http://www.ginzanonsen.jp/nagasawa/index.html)
    * [銀山荘](http://www.ginzanso.jp/)
* あとはまったり温泉入ったり肉を食べたりする


# 3日目

メモ：たくは地元にまだいるということなので、宮城県でばいばいする

* 2日目に行く先にもよるんだよねぇ
* 帰りに一つ、自然を堪能できそうなものを入れたい（天候見つつ臨機応変に対応したいよね）
  * 川下り
  * 滝を見に行く
  * ドライブいえーい

* たくの家に車を置いていく
* 15:00~16:00 くらいには仙台駅付近にいたいかも？
* 18:00~19:00くらい 東京駅着・解散 が体力的に無難かな

**Comment by jp-taku2** [comment]
ごめん、1日目僕は22時30〜23時頃まで飲み会なのです...。

**Comment by jp-taku2** [comment]
僕は、6日14:00頃〜23:00頃まで不在

**Comment by Omega014** [comment]
お、了解。
温泉入ったり飲み食いしてたらすぐ23時になるから大丈夫やろ。予定ちょびっと変えた

**Comment by Omega014** [comment]
コテージに泊まるという選択肢もある by taku

http://yamagatakanko.com/log/?l=359581

**Comment by gomayumax** [comment]
私のコレさえできればイイコト

酒蔵

**Comment by gomayumax** [comment]
一応MAP
https://drive.google.com/open?id=11V5wKWKFw1JD1-6IFfV-Mcy-sH0&usp=sharing

**Comment by gomayumax** [comment]
行きやすい銭湯https://www.google.co.jp/maps/place/%E9%A7%92%E3%81%AE%E6%B9%AF/@38.2618691,140.8680326,17.75z/data=!4m8!1m2!2m1!1z6Yqt5rmv!3m4!1s0x5f8a283bea113725:0x462992787804f1ec!8m2!3d38.26125!4d140.868564?hl=ja

**Comment by ara-ta3** [comment]
# 1日目

- 12:00 くらいに仙台駅着
- ~13:00 仙台駅付近で昼ごはん
- A: 13:20 ~ 17:00 （初めて仙台に来た人向け）
  - 瑞鳳殿 (政宗様のお墓。ちなみにこの日は七夕祭り仕様で夜には竹灯篭が光る。)・・・るーぷるというバスで移動
  - 仙台城跡 (政宗様の銅像があるところ)・・・地下鉄東西線 国際センター駅で降りる
  - https://github.com/ngineerxiv/dark/issues/2#issuecomment-231183497
- 17:00 ~ 23:00
  - 仙台七夕まつり [七夕マップ] ← 本来はこれに参加したいだけでイベント立てた
  - ご飯適当に七夕祭りので店でもいいし居酒屋でもいいしみたいな
  - 温泉 ← たくの家の場所ぼんやりとしか覚えてなかったのでどの辺りで温泉入るとベストなのか決めかねた
  - 風呂
    - 第一候補
      - https://goo.gl/maps/Luk6YKz5Ts62
      - 祭りが近くて混む可能性がある
    - 第二候補
      - https://goo.gl/maps/vL4Y5CgbkBE2
    - 第三候補
      - https://goo.gl/maps/S7srXhFFLT92

- 22:00 ~ 22:30 くらいに温泉あがる
- 23:00 頃に仙台駅合流

**Comment by ara-ta3** [comment]
```
会社
ニッポンレンタカー
出発
2016年08月06日（土）10:00
白石蔵王駅前営業所
返却
2016年08月07日（日）17:00
郡山駅西口営業所
基本料金
レンタカー11,800円免責補償込み標準装備カーナビ搭載標準装備
オプション
乗り捨て3,240円
合計料金15,040円(税込)
```

**Comment by ara-ta3** [comment]
# TODO 

- 2日目のレンタカー
  - 1台じゃ厳しげ

# 2日目

- 10:00 くらい
  - たく家出発
- ~12:00 
  - 御釜 蔵王に行く
  - 13:00 蔵王酪農センター ←譲らないぞ
    - チーズ食べたい！ピザ！ちーずけーき！ヒルメシ！
    - カッテージチーズ手作り体験したい！(所用時間30分)
- 15:00 猪苗代湖のほうまで来る
  - いろいろする
    - 温泉やら泊まる場所やら
    - このへんでコテージを取る
    - http://www.cottage.co.jp/
  - このへんでブラブラしつつコテージ行って酒飲んでいい感じに楽しむ
  - http://www.bandaisan.or.jp/

以上

**Comment by ara-ta3** [comment]
# 3日目

- 10:00 出発
  - おそらく大体チェックアウト時間
- 13:30 くらいまでぶらぶらする
- 13:30 猪苗代湖付近出発 
- 15:00 あぶくま洞
  - http://abukumado.com/
- 16:00 あぶくま洞終了
- 17:00 郡山から新幹線出発
- 19:00 だいたい東京到着

**Comment by gomayumax** [comment]
must
- コテージ
- 新幹線
- レンタカー

**Comment by Omega014** [comment]
大丈夫だと思うけど確認：旅程の最終日は月曜日なので有給とっておいてくだしあ

**Comment by ara-ta3** [comment]
https://ngineerxiv.slack.com/archives/tohoku/p1468208928000438
コテージ with BBQセットで予約

```
omega [12:48]  
空いているところでよさそうなところ
* http://www.syakunage.com/bessou/248.html
* http://www.syakunage.com/bessou/560.html
* http://www.syakunage.com/bessou/818.html

[12:51]  
んー、なんかどこでもいい気がする

goma [12:57]  
http://www.syakunage.com/bessou/560.html

[12:57]  
がいい

arata [12:57]  
248か560がいいなぁと思った

goma [12:57]  
560風呂綺麗

omega [12:58]  
560一番よさそう

[12:58]  
わかる、それ

mihyaeru21 [12:58]  
:+1:

omega [12:58]  
じゃあ560で予約してくるお

goma [12:58]  
わいわい

arata [12:58]  
:komagata:

mihyaeru21 [13:00]  
:funassy:

omega [13:03]  
560で予約とったお
電話でとりあえず部屋の予約した。
次、ネットから本登録的なのをやる
オプションが選べるんだけど、

バーベキューセット
鍋用ガスコンロ
DVDセット
生ビール10L
生ビール19L
テニスコート
フットサルコート
★ご利用料金は現地管理センターにてお支払いください
 
★オプション詳細は画面下部の「ご意見・ご要望」欄にご記入ください
・ビールサーバーの「配達日/希望時間/ジョッキ数」（配達は18時までとなります。）
 
・テニスコート・フットサルコートの「利用日時（2時間単位）/別荘地/面数」
　
　テニスコート⇒第1別荘地に1面、第2別荘地に3面
　フットサルコート⇒第1別荘地に1面
 
→「オプション料金」を確認する
 
バーベキューセット(1台2,000円税込）
鍋用ガスコンロ(1台目無料、2台目500円）
DVDセット（無料）
生ビール10L　（7,000円+税）
生ビール19L　（12,000円＋税）
テニスコート　（1時間1面1,000円税込）
フットサルコート　（同上）

[13:10]  
バーベキューセットだけでいいかな

[13:10]  
ガスコンロいる？

[13:11]  
ビールどうしよう

mihyaeru21 [13:11]  
バーベキューセットだけで良さそう

omega [13:11]  
ビールたけぇ

mihyaeru21 [13:11]  
ビールは地ビールじゃなかったっけ

omega [13:11]  
あー、なんかそういう話してたなw

mihyaeru21 [13:11]  
わざわざ生ビールじゃなくて良いと思う

omega [13:11]  
そうだな

mihyaeru21 [13:11]  
むしろ生ビールだと普段飲む銘柄だから微妙そうｗ

omega [13:11]  
BBQセットだけにしとく

new messages
[13:12]  
> 普段飲む銘柄だから微妙
タシカニ
```

**Comment by mihyaeru21** [comment]
※2枚目の画像で`あり`が片方変になっているのは、クリックしたら戻せなくなっただけで特に意味があるわけではない点に注意

**Comment by papix** [comment]
自由席は基本的に｢あり｣になっているはず. この感じだと, 始発で乗らない限り自由席立席乗車っぽい感じになるのでは? という気がしていて, 予約した方がいいかもしれないね...

**Comment by mihyaeru21** [comment]
帰りは、郡山17:30発、東京18:48着の新幹線を指定席予約済み（1人8,400円）。

**Comment by papix** [comment]
めっちゃいまさらだけど｢知性のpapixくん｣ってなんやねん...w

↑ については, 僕は別行動で郡山から夜行バスなり何なりで帰るですー.

**Comment by Omega014** [comment]
レンタカー側のガソリン代: 2633 円
たく家車側のガソリン代: 円

**Comment by Omega014** [comment]
ガソリン代は生産されますた。issue閉じまっす。
