### ISSUE TITLE
dotfilesを自慢しあう会

### ISSUE THREAD

**Issue by sota1235** [ngineerxiv/dark#20]
```
kirin	[4:18 PM]  
俺のdotfiles自慢LT大会したい

hoto	[4:18 PM]  
わかる

[4:19]  
2年くらい前に zsh の勉強会とかでひけらかしてたことはある (edited)

arata	[4:19 PM]  
やってこ↑↑
```

**Comment by ara-ta3** [comment]
＿人人人人人人人人＿
＞　2分で開催決定　＜
￣Y^Y^Y^Y^Y^Y^Y￣

**Comment by ara-ta3** [comment]
connpassで募集して良いかもしれんね

**Comment by hoto17296** [comment]
`Dotfiles Casual Talks #1` とかにしよう

**Comment by sota1235** [comment]
1月ぐらいですかね！

**Comment by ara-ta3** [comment]
これそう言えばいつに仕様

**Comment by sota1235** [comment]
2月かな…日付だけ決めてConnpass作ってって感じですかね

**Comment by hoto17296** [comment]
https://chouseisan.com/s?h=9222179ecbb44ebc8ed4e2de4253d272
なんとなく金土日なのかな？と思って立てたけども

**Comment by sota1235** [comment]
2/5か2/24の予感

**Comment by acchanAlexander** [comment]
2/5になりそうなら、早めに調整できそうならしたさ
connpassって作ったんでしたっけ？

**Comment by ara-ta3** [comment]
キリン氏2月日本にいないらしいから3月になりそうな気がする

**Comment by acchanAlexander** [comment]
気がついたら4月だ

**Comment by acchanAlexander** [comment]
やるとしたら平日でもよいかな？？
休日は弊社難しそう。
平日できるかもまだ確認中だけど。
なお、半蔵門です。

**Comment by acchanAlexander** [comment]
平日でも弊社無理そうだった。。。
すまんご。。。

**Comment by atariyo** [comment]
すみません、こっちの調整さんで日程再調整したいです。
https://chouseisan.com/s?h=b54302c3f09843928aed61804d1bd721

**Comment by acchanAlexander** [comment]
connpass のページ下書き保存して、レビュー中。

**Comment by acchanAlexander** [comment]
日付は 12/20 （木）

**Comment by acchanAlexander** [comment]
レビュー通ったので、明日の昼に connpass 公開します。
弊社の勉強会チームに運営を助力してもらえるようにしたので、
connpass のページにいくつか会社紹介文みたいなのが入ることになったけど、そこはご了承くださいませ

**Comment by acchanAlexander** [comment]
公開しました！
https://lifull.connpass.com/event/111401/
