### ISSUE TITLE
･･･「サイゼ飲み」･･･だと･･･？

### ISSUE THREAD

**Issue by mrtry** [ngineerxiv/dark#21]
「サイゼ飲み」は都会の人たちの教養だと聞きました。
教養を培いたいッ...！！！

調整さん
https://chouseisan.com/s?h=34e58aad864d44ef92faa3689fa16cfb

**Comment by ara-ta3** [comment]
![image](https://cloud.githubusercontent.com/assets/2089153/20438167/e552f344-adf9-11e6-8632-da92b47ece28.png)

**Comment by gomayumax** [comment]
12/16(金) 19:00〜 ぽさある

**Comment by Omega014** [comment]
サイゼのみしたい（つ・ω・）他の予定が入るかもしれないので行けたらいく！

**Comment by sota1235** [comment]
16日の気持ちでスケジュールに書き込みましたん

**Comment by mrtry** [comment]
12/16(金) 19:00 ~ でいきましょ！

コレは、予約しておくべき...?
あと、どこのサイゼが良いのだろうか...?

**Comment by mrtry** [comment]
場所、渋谷だとよさそうとのことで、`渋谷青山通り店`にしようと思ってます。
いかがでしょう？(´・ω・｀)

あと、私が移動の都合で合流が`20:00`になると思います。orz

サイゼリヤ 渋谷青山通り店
https://retty.me/area/PRE13/ARE8/SUB805/100000011955/

**Comment by mrtry** [comment]
無事閉会しました！
初のサイゼ飲みでしたが、とてもよかったです！！

最終的に8名集まり、18,000円ぐらいでした。
お一人2,250円ぐらいで、おなかいっぱい、ワインいっぱい、楽しみました 🍷 

また、できたらいいなあ、と思います 👍 

## 以下、雑レポ

**マグナム(1.5l 赤,白)/ 1,080円** 
安い、美味しい、悪酔いもしなさそうと評判でした

![img_20161216_194040](https://cloud.githubusercontent.com/assets/8851552/21284140/e8e2f582-c455-11e6-925f-01e7f102e9e3.jpg)

---

ドリアとフォカッチャ、一緒に食べると幸せになれる。
ワインも進みました 🍷 

![img_20161216_195035](https://cloud.githubusercontent.com/assets/8851552/21284138/e8e1975a-c455-11e6-92c2-33a41300d69c.jpg)

---

みんなでワイワイしました

![img_20161216_202629](https://cloud.githubusercontent.com/assets/8851552/21284139/e8e28df4-c455-11e6-8946-5d4fe72b5523.jpg)
