### ISSUE TITLE
紅葉眺めつつ高尾山登りに行く

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#22]
```
https://ngineerxiv.slack.com/archives/event-in-dark/p1478138711000515
mihyaeru21	[11:05]  
高尾山の紅葉を眺めつつ登山して、温泉に入って、:sake::beer:を飲む会をやりましょう！！！
https://chouseisan.com/s?h=72ecf67b17c142f7ad161732732e2c82

https://ngineerxiv.slack.com/archives/event-in-dark/p1478432557000564
mihyaeru21	[20:42]  
高尾山は23日にしましょう！

https://ngineerxiv.slack.com/archives/event-in-dark/p1478837684000578
acchan	[13:14]  
23日の高尾山、友達一人も一緒に行っていいっすか？
友達行けるかまだ未定なんだけど
mihyaeru21	[14:05]  
yeah
```

**Comment by mihyaeru21** [comment]
http://www.takaotozan.co.jp/course/img/course_map.pdf

1号路が紅葉マーク的に良さそう。
往復で180分。適当にバッファ30分くらいみとく。
暗くなると危ないし紅葉見れないから16:30には降りてこれるくらいの時間に出発したい。
ので、13:00に登山を開始する。

12:45に高尾山口駅に集合！

**Comment by mihyaeru21** [comment]
## 参加者

- @mihyaeru21
- @mrtry
- @stefafafan
- @acchanAlexander with friend
- @Omega014
- @ara-ta3 (来れたら

## 大体のタイムテーブル的なやつ

- 12:45 高尾山口駅集合
- 13:00 登山開始
    - コースは1号路: http://www.takaotozan.co.jp/course/img/course_map.pdf
- 14:40 山頂到着
    - 地図曰く、山頂から「もみじ台」なる場所へすぐ行けるっぽい
- 15:10 山頂出発
- 16:30 下山完了、温泉へ
    - ここ: http://www.takaosan-onsen.jp/
- あとは流れで飲む 🍺 🍶 
    - 温泉のところで飲めるっぽい
    - 無理なら電車でちょっと移動すれば何かあるだろう

## 準備

各自これを読んで万全の準備を: http://www.takaotozan.co.jp/guide/

**Comment by ara-ta3** [comment]
不参加でおなしゃすmm

**Comment by stefafafan** [comment]
すみませんわたしも不参加でお願いします :bowing_woman:

**Comment by papix** [comment]
@ara-ta3 と @stefafafan の代わりに参加します

**Comment by papix** [comment]
> 無理なら電車でちょっと移動すれば何かあるだろう

八王子まで行けばいろいろありますよ. 日本酒とか飲みたいなら https://tabelog.com/tokyo/A1329/A132904/13026595/ とか良いですね.

**Comment by acchanAlexander** [comment]
@mihyaeru21
言ってた friend 明日来ますー！
会社の後輩のエンジニアの女の子でっす！

明るくて元気な子です。
みんな仲良くしてください＾＾

**Comment by gomayumax** [comment]
楽しかったでごんす。

運動も兼ねて定期開催で良いんじゃないかと思うほどに良かった
膝を痛めてお風呂に浸かりビアーで回復.....最高!!!

**Comment by mihyaeru21** [comment]
DONE!

> 運動も兼ねて定期開催で良いんじゃないかと

普段運動しないし、たまにやるの良さそう

**Comment by mrtry** [comment]
おやすみ超絶満喫した感あるから、またいきたい

**Comment by ara-ta3** [comment]
closeで良さげに見えるのでcloseしまっす
なんかあったら個別に
