### ISSUE TITLE
SHIROBAKO鑑賞会

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#23]
Dアニメストア強い

https://anime.dmkt-sp.jp/animestore/ci_pc?workId=11479

24話なので多分13時半集合で行ける気がする

**Comment by ara-ta3** [comment]
いつやるの
https://chouseisan.com/s?h=05dd8c91029f441bb6b305e535db98b7

**Comment by mrtry** [comment]
参加したいお気持ちです

**Comment by sota1235** [comment]
参加したいです

**Comment by ara-ta3** [comment]
これもいつにしようｗ

**Comment by ara-ta3** [comment]
29日が候補っぽいけど新年会がかぶってるから無理そう

**Comment by ara-ta3** [comment]
3月にやりたいなぁという気持ちがある
23話をまた見てとても見たい気持ちになった

**Comment by ara-ta3** [comment]
熱が冷めつつあるので一旦closeしようかな・・・ｗ
