### ISSUE TITLE
12歳。鑑賞会

### ISSUE THREAD

**Issue by stefafafan** [ngineerxiv/dark#24]
## どういう作品なのか
「ちゃお」で連載中の小学生同士のラブストーリーです。「最近の小学生はこんなんなのか！」という気持ちになって便利です。
http://www.shogakukan.co.jp/pr/12sai/

## どこでみれるの
Amazonプライムビデオでみれます。実はまだ完結していない（シーズン2が今期放送中）。
Amazonプライムビデオは最新話まで対応していてすごい。

シーズン1
https://www.amazon.co.jp/dp/B01DPY201E

シーズン2
https://www.amazon.co.jp/dp/B01LXQE7IQ

## 募集
- 参加者
- 会場
- 日程

よろしくお願いします(´･_･`)

**Comment by gomayumax** [comment]
参加！

会場うちでよければどうぞ

**Comment by Omega014** [comment]
twitterでもいったけど私も参加するぞい(・v・)

**Comment by stefafafan** [comment]
ありがとうございます〜！
調整さんあれしました
https://chouseisan.com/s?h=d86392eb5bf94337aac4054c94642a51

**Comment by stefafafan** [comment]
ごま氏ハウスで1月14日辺りにしようかなという気持ち
他に興味あるマンいないのかなっ(´･_･`)

**Comment by Omega014** [comment]
あ、14日はPython入門者のメンターやる予定入れてしまった。
あとその日はDARKのイベントと被ってるね。-> goma氏参加するかも？

できれば別の日にお願いしたくー。

**Comment by stefafafan** [comment]
おっなるほどそちらをチェックしてなかった、調整さんみてなんとなく14と言ったのでした（日程は( ∩'-'⊂ )ｼｭｯと決めたほうが良さそうと思って）
そうなると8日とか15日とかかな

**Comment by Omega014** [comment]
( ∩'-'⊂ )ｼｭｯ
実は3日もみんな予定○ついているという事実
流石に三が日にロリはやめておきますかねぇ...
ということで8日あたりでどうでしょ？

**Comment by stefafafan** [comment]
3日確かにね…w
8日🙆です！

**Comment by gomayumax** [comment]
3日やるぞ！！！

見終わった後に神社にいって「尊い〜」って言ってゴール！！

**Comment by stefafafan** [comment]
3日オッケー!!!!

**Comment by stefafafan** [comment]
1期と2期終了した、24話あります。
Amazonプライムだと倍速再生などできなさそう、何時から何話みましょうか

**Comment by gomayumax** [comment]
なんか12歳という概念が再構成された

みんなでは全話見れなかったけど、
個人であのカレカノ関係の行く末を見届けて行きたい

ゆいちゃんのぱんつチェキが欲しい

**Comment by Omega014** [comment]
2期全部見終えた。

このアニメにはイマドキの小学生女子の夢が詰まり過ぎてて若干の恐ろしさを感じましたよ。こんなきれいな世界は現実にはそうそうないんだよなぁ...

高尾は最終回も小学生とは程遠い言動をしていて逆に将来が心配になります。やっぱり桧山くんくらいの小学生がかわいいですね。許されるなら一緒に暮らしたいです。

ゆいちゃんも乙女でかわいいけど、やっぱり表情がコロコロ変わって見ていて面白い、愛され体質のピュアな花日ちゃんを彼女にしたくなる気持ちわかります...。

**Comment by stefafafan** [comment]
めちゃ楽しかった、皆さんありがとうございました

ということでCloseしますね
