### ISSUE TITLE
痛風meetup

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#25]
こうですかわかりません。

```

hoto [21:04]  
痛風スゴロクを買いました :innocent:

[21:04]  
https://www.facebook.com/saisa6153/posts/1206705559409535
 facebook.com
Yuki Tannai - 痛風ボドゲ。いの一番に発症した。 | Facebook
痛風ボドゲ。いの一番に発症した。 

mihyaeru21 [21:05]  
@isaoeka

hoto [21:05]  
何かの機会に遊びましょう

[21:05]  
遊びながら痛風について学べる、すごい

mrtry [21:16]  
酒を飲みながらやりましょう！！！！！！！！

goma [21:18]  
明太子食べながらやりましょ！！！

omega [21:19]  
ビールだビールだ！

hoto [21:26]  
痛風 meetup やろう

goma [21:27]  
ｗｗｗｗｗｗ

mihyaeru21 [21:28]  
基調講演： @isaoeka

papix [21:29]  
よさそう

[21:29]  
うにとか買おう

mrtry [21:42]  
年明けすぐなら、帰省ついでにいくらとか買える

omega [21:50]  
鶏レバーもいいですね

mrtry [21:54]  
レバーとこんにゃくの煮物が食べたい

[21:54]  
日本酒も一緒に

[21:54]  
あああ〜〜〜

isaoeka [23:16]  
お

[23:17]  
まかせろ

[23:17]  
え、もうこんな時間なのかよ

kirin [23:40]  
退職祝いにボドゲ一杯もらったので痛風meetupにしれっと持っていきたい←
```

**Comment by ara-ta3** [comment]
超短焦点プロジェクターペイしたいのでうちがいいなぁ・・・←

一旦調整さん
https://chouseisan.com/s?h=99265c3456df4fa6accee42af6e37b1d

**Comment by mrtry** [comment]
これいつしましょ

**Comment by ara-ta3** [comment]
1/20（金）はどうでしょう

**Comment by hoto17296** [comment]
> isaoeka [6:02 PM]  
> うにょ
> ok_woman
> （おそらく夜だと思って返答している

1/20 (金) にしましょう

**Comment by gomayumax** [comment]
行く気でいる

**Comment by hoto17296** [comment]
[延期](https://ngineerxiv.slack.com/archives/event-in-dark/p1484707034000354)のため調整さんやりなおし〜〜〜

https://chouseisan.com/s?h=58eee2d9811b46418fe3d8d9c9401696

**Comment by hoto17296** [comment]
2/24(金) にしよう

**Comment by sota1235** [comment]
まさかの海外出張なので不参加でお願いします :bow:

**Comment by gomayumax** [comment]
覚えているだろうか、痛風に憧れたあの日あの時(※忘れてたのでリマインドコメント)

**Comment by mrtry** [comment]
帰省した時に、地酒買ってきたので持っていく

**Comment by mrtry** [comment]
今週や！！！！！

会社飲みの週だったから、
多めに作ったケータリングをちょっと持ち出す予定。

**Comment by ara-ta3** [comment]
19:00には家にいるようにします
宮城行った時の日本酒ストックしてます

住所は参加者みんなわかるんかな
わからなかったらSlackで聞いてもらって答える感じでmm

**Comment by hoto17296** [comment]
いさおパイセンに基調講演 LT していただく予定です

**Comment by ara-ta3** [comment]
集合まで大乱闘をやって、
買い物行って、
Fridayだからという理由で（？）フライドポテトを買って、
めっちゃ食べて、
カスタムロボやって、
痛風すごろくやって、
バトルラインやって、
最高のプレミアムフライデーでした。
これにて **第一回** 痛風ミートアップは終了です

![image](https://cloud.githubusercontent.com/assets/2089153/23312806/6955c5c6-fafe-11e6-9058-7363178a8633.png)
https://twitter.com/hoto17296/status/835094943714562049

![image](https://cloud.githubusercontent.com/assets/2089153/23312813/6f7fd3e2-fafe-11e6-9ca9-1d111206df0c.png)
https://twitter.com/ara_ta3/status/835091216869928961

超短焦点もいいんだけど、レムかわいい

![image](https://cloud.githubusercontent.com/assets/2089153/23312838/8efd8e08-fafe-11e6-8b56-5122ed9b3349.png)
https://twitter.com/hoto17296/status/835109493448966144

https://twitter.com/hoto17296/status/835137612075560960
