### ISSUE TITLE
papi's kitchen 第4回目くらい

### ISSUE THREAD

**Issue by papix** [ngineerxiv/dark#3]
5/22(日)にやるヨ!

- 参加しようと思っている人は名乗りでてね! (ほと夫妻含む)
- 食べたい料理があったら書いてね! (ないと雑に作るよ)
- 嫌いな食べ物/食材, あとアレルギーとかもあったら書いてね! (絶対だよ!)

**Comment by ara-ta3** [comment]
体調が最高すぎるので、回復したら行きます。
土曜までには決める所存

**Comment by gomayumax** [comment]
夫妻参加 (なお、hoto氏の確認は取っていない

野菜系、魚系を希望です！

**Comment by jp-taku2** [comment]
千里と秋葉原散歩が終わったら参加！
お魚が美味しいですね！

**Comment by ara-ta3** [comment]
無事終わったからclose
