### ISSUE TITLE
2017年麻雀大会

### ISSUE THREAD

**Issue by urataku** [ngineerxiv/dark#30]
# 概要
とりあえずこのコミュニティで麻雀しようぜ

# 日程調整

https://chouseisan.com/s?h=d841460f3edb48a9b49d053b447c4cde

# ルール

調整中  
天鳳と同じで良い？

[天鳳のマニュアル](http://tenhou.net/man/)←結構下の方、ルール / 段位戦4人打ち

**Comment by isaoeka** [comment]
あ、場所ってどこになりそうです？
（オンラインなのかオフラインなのかさえも分かっていない

**Comment by urataku** [comment]
そもそもどっちか決めてなかったマン  
せっかくだから、オフラインでやりたい

**Comment by natsumican63** [comment]
渋谷だといくつかお店分かるので、とりあえず渋谷集合で如何でしょう？？

**Comment by isaoeka** [comment]
ok_woman

**Comment by urataku** [comment]
Yes Master
