### ISSUE TITLE
雑に料理を作り、酒合わせてキャッホーイする

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#32]
https://twitter.com/gomaaburamax/status/829916697553362944

会場は、ほとごま家でもいいし、持ち寄りなら会場問わない
店は除くよ！！！

調整すっぞ→ https://chouseisan.com/s?h=3c35aef95a1d490894c21128e1b7a573

**Comment by mrtry** [comment]
呼ばれた気がしたぞ！！！！！！！！！！

**Comment by Omega014** [comment]
酒があまってるので持っていく！

**Comment by gomayumax** [comment]
おいしかった！楽しかった！またやろうず(・∀・)
