### ISSUE TITLE
花見したい

### ISSUE THREAD

**Issue by mrtry** [ngineerxiv/dark#33]
缶チューハイ片手に、散歩しつつ、出店で焼きそば買いたい

**Comment by ara-ta3** [comment]
去年は4/2に行ったらしい
3月〜4月の序盤で出来ると良いんだろうなみたいな気持ち。

https://twitter.com/ara_ta3/status/716160955483226113
![image](https://cloud.githubusercontent.com/assets/2089153/23313999/52b83678-fb03-11e6-8e59-076e3d40c1b8.png)

https://twitter.com/ara_ta3/status/716204025318809600
![image](https://cloud.githubusercontent.com/assets/2089153/23314005/5832bdee-fb03-11e6-89f5-fab3ca2e9c24.png)

https://twitter.com/ara_ta3/status/716204512629764096
![image](https://cloud.githubusercontent.com/assets/2089153/23314015/611880c4-fb03-11e6-8374-574cfca27efe.png)

https://twitter.com/ara_ta3/status/716228518862979072
![image](https://cloud.githubusercontent.com/assets/2089153/23314031/716d1a0c-fb03-11e6-8c85-cf4052efc301.png)

https://twitter.com/gomaaburamax/status/716209247277568000
![image](https://cloud.githubusercontent.com/assets/2089153/23313987/41fdd43c-fb03-11e6-98d9-6515ab7c37c8.png)

**Comment by ara-ta3** [comment]
|дﾟ)ﾁﾗｯ

**Comment by mrtry** [comment]
いきたさMAXなので、調整さん立てました
https://chouseisan.com/s?h=b05f1cca2237452c961e70446ab00386

**Comment by Omega014** [comment]
おうおう、花見のための御猪口を探さないとなぁ
調整さん入れた

**Comment by gomayumax** [comment]
調整さん入力done!!!

今年の見頃はいつだろうね(・∀・)  
まぁみんな集まればそれは花見になるでしょうｗ

**Comment by ara-ta3** [comment]
現状見る限り4/2が濃厚そう？

**Comment by ara-ta3** [comment]
場所どうしよう

**Comment by mrtry** [comment]
そろそろ確定したほうが良さそうな気持ち。
4/16なら☓な人がいないのでよさそうな気がしました。
確定でいいですかね...?
(よさげなら :+1: お願いします)

**Comment by mrtry** [comment]
人生2回目の花見マンなので、場所詳しくないです！！！！
よさそうなところあったら教えてください！！！！

**Comment by gomayumax** [comment]
# 花見場所(勝手に候補/随時更新)

+ 芝公園
    + いいぞ！:  芝生が広い、ピクニックっぽい、アクセス○
    + 悪いぞ！:  桜の木は２,３本、都会ど真ん中でウェイがたくさんいる

**Comment by gomayumax** [comment]
投票の結果

https://ngineerxiv.slack.com/archives/C1G9NUU2D/p1490510419603283

会場: **井の頭公園**

**Comment by mrtry** [comment]
@gomayumax 
あざす！！

花見初心者マンですなんですが、場所取りマンって、何時ぐらいから公園にいってればいいんでしょ...?

**Comment by gomayumax** [comment]
場所取りは10時くらいでいいかなーと甘く思ってる
例年がどれくらい分からないので
役立ち情報を提供できない(´･д･`)

本日、ダンボールをお尻の下に敷けば冷たくないねという知見を得たのでメモしておく

**Comment by mrtry** [comment]
すんごく今更な話ですが、今週桜ピークとの話をきいたのですが、
もしかして来週花見するってなったら、もしかして散りきってます...? 😇
もしかして、出店もなかったりします...? 😇
(そこまで考えが及んでなかった........)

**Comment by hoto17296** [comment]
酒が飲めればいいという身も蓋もない意見があります

**Comment by mrtry** [comment]
## 食べ物、飲み物について
- 当日持ち寄りでやっていきたい気持ち
- 公園近くにスーパーあるから、足りなくなったら買いに行く

**Comment by gomayumax** [comment]
今のところ天気予報は**晴れのち曇り**

# 場所とりについて
10時くらいには着いていようかなーという気持ちですが
我が家のシートはあまり広くないのでどれだけ場所が取れるか微妙です

**Comment by mrtry** [comment]
腰が弱い人、体がかたくて足組むとしびれてくる人、
ダイソーでレジャー用の椅子が100円でバックに収まるもの売ってるので、あるといい感じですよ！！！！！！！
(先日得た花見の知見)

**Comment by acchanAlexander** [comment]
控えめに言って花見最高でした。
@gomayumax @mrtry とりまとめてくれてあざす！最高でした。

清算ってどうするんだっけ。

**Comment by mrtry** [comment]
最高に楽しかった...！！！！
ありがとうございました！！！

精算に関してですが、
私が購入した分については、 

- 前日買ったお皿等の食器とツマミ: `1,300円`
- 当日使ったつまみと酒: `2,700円`

をあわせて `4,000円` でしたので、10人で割って `一人:400円` ですね。

何かしらでお会いした時に頂けると幸いです 🙏

わからなくなりそうなので、チェックリストつくっとく
([調整さん](https://chouseisan.com/s?h=b05f1cca2237452c961e70446ab00386)を参考)

- [ ] omega
- [ ] jp_taku2
- [ ] うら
- [ ] ごま
- [ ] isaoeka	
- [ ] みひゃ
- [ ] Hoto
- [ ] ichigotake
- [ ] あっちゃん

**Comment by isaoeka** [comment]
楽しかったです！諸々ありがとうございました！
お金出すマン

**Comment by mrtry** [comment]
回収すっかり忘れて3ヶ月位たってしまった...。

今回そこまで額大きくないし、
なかなか他の人に会う機会がなかったりするので、
お金は私持ち、ってことにしておきます 👌 

楽しかったので、また来年やっていきましょ 👍 
Issue、閉じときます！

(次回こんなかんじのことやるときは、飲み始める前にその場でお金貰うようにしたほうがいいかもなぁ〜。)

**Comment by isaoeka** [comment]
あ〜ごめん...
払うぞ！ & ちゃんと全員から貰おう。（一回なぁなぁになると続きそうだし）

**Comment by mihyaeru21** [comment]
🙇 
払います！！！

**Comment by jp-taku2** [comment]
払う！
多分会う機会が無さそうだからisaoekaに託す

**Comment by isaoeka** [comment]
まかせろ

**Comment by isaoeka** [comment]
すずたくの400円を授かった

**Comment by takumi-suzuki** [comment]
goma hoto のも払っていない気がしている！

**Comment by mihyaeru21** [comment]
はらた
