### ISSUE TITLE
ボドゲがしたい

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#34]
おうちにあるボドゲがホコリを被ってきました
由々しき事態です！！！！

ボドゲしよう！！！！！

# 日付
3/18(土) 午後14時〜

# 会場
ほとごま家
(大崎・五反田あたり)

# 内容
ボドゲをする

- カタン(6人までできる)
- 痛風すごろく
- ニムト
- バトルライン(対面で数字のカード並べて駒をとるやつ)
- お邪魔もの(6人以上いたらやりたい)

# 人数
~7人(キャパの都合)

確定(6人): hoto goma kirin gomaの友人A arata suzutaku

**Comment by ara-ta3** [comment]
任天堂switch持っていきます

**Comment by gomayumax** [comment]
add arata
add suzutaku

**Comment by gomayumax** [comment]
開始１４：００〜　ね！

**Comment by takumi-suzuki** [comment]
日本酒持ってくね！！

**Comment by takumi-suzuki** [comment]
あと、カタンの航海者版も

**Comment by sota1235** [comment]
🍺と赤玉ポート🍷持ってく！

**Comment by ara-ta3** [comment]
close?

**Comment by gomayumax** [comment]
楽しかった！！

やったボドゲ↓↓

- カタン(6人までできる)
- バトルライン(対面で数字のカード並べて駒をとるやつ)
- お邪魔もの(6人以上いたらやりたい)
- (人が死んだところから始まるやつ)


やったswitchゲーム

- 1 2 switch
- ゼルダ
- ボンバーマン


**やり残してしまたボドゲがまだまだある(やりたいswitchゲームもこれから発売)**　
第２回やりましょーーーーーーーーー
