### ISSUE TITLE
みんなで行こうよ技術書典

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#35]
https://ngineerxiv.slack.com/archives/event/p1488159459000562
```

goma [10:37 AM]  
https://techbookfest.org/event/tbf02
 技術書典：技術書オンリーイベント
技術書典2：技術書オンリーイベント
僕らが作る。 技術書オンリーイベント第2回開催決定！ 2017年4月9日(日) 秋葉原 アキバ・スクエア (656KB)


[10:37]  
技術書典4/9(日)空けとかなきゃ

stefafafan [10:39 AM]  
4/9か

omega [10:40 AM]  
今年出店しようと思ってたっけ、もう締め切り過ぎてた

[10:41]  
開店と同時にいこう（人がめちゃくちゃ多いらしいので

stefafafan [10:41 AM]  
人〜

goma [10:41 AM]  
前は入場規制してたもんね

[10:42]  
早めに行って、アキバでラーメン食べて、フラフラして帰るぞ！！！！
 ```

# 目的
同人技術本を買って、
秋葉原で美味しいラーメンを食べる、
そしてガジェット系の店を巡って
充実した日曜日を送る

# 日付
4/9(日) 10:30?(開場の30分前)~

# 場所
秋葉原

# 注意
同人誌即売会は戦場である（個人差あり)
遅刻して入場出来なかったら、それは敗北を意味する（個人差あり）

「行ける気がしねぇ、、、俺を置いて先にいけ。。。。」って人で
どうしても欲しい本があるってことであれば
前もって言っておいてくれればおつかいします(๑•̀ㅂ•́)و✧

# メンバー
@gomayumax 
@mrtry 
@isaoeka 
@papix 

(・∀・)< 参加表明コメントでよろ〜〜〜

**Comment by mrtry** [comment]
いきたさ

**Comment by isaoeka** [comment]
いきたさ

**Comment by papix** [comment]
いたきさ

**Comment by isaoeka** [comment]
🙏  申し訳ないっす...用事が入り参加不可になりました... 🙏

**Comment by ara-ta3** [comment]
欲しい気持ちがある
https://twitter.com/hagino3000/status/843416731640971264

**Comment by gomayumax** [comment]
私、ダブルブッキングをしてしまい、大変申し訳ないが不参加です。。。。
でも欲しい本があるので
@hoto17296 に引き継ぎます！

ごめんなさい。。。

**Comment by mrtry** [comment]
今週だった

**Comment by nayucolony** [comment]
え-03でサークル参加しております :)

**Comment by mrtry** [comment]
明日行くの
- mrtry
- hoto

ぐらいですか...?

**Comment by ichigotake** [comment]
:raised_hands:

**Comment by mrtry** [comment]
わいわい

明日は10:30に秋葉原駅の電気街口に集合とかでいいですかね...?

**Comment by nayucolony** [comment]
わたしもいるよ〜

**Comment by nayucolony** [comment]
整列は10時からなんだよ〜

**Comment by mrtry** [comment]
なゆ氏物販する人から別なのかと思ってた 👀 

10時から整列できるのか。
会場広くなったから、開示30分前ぐらいでいいのでは節があったがどうしましょうかね〜

**Comment by nayucolony** [comment]
サークル参加なので別入場でする〜！前回みたいに入場規制とかはないとおもうし、ゆるっとでよさそう

**Comment by mrtry** [comment]
なるほど
ありがたき助言👍 
ゆるっといきます。

**Comment by mrtry** [comment]
平均500円ぐらいで、おもしろみにあふれる技術書をいっぱい買えて楽しかったです！！
開始30分前着で、そこそこ前に並べたので、次回もそれぐらいに行くと良いかもしれない。
(後ろ見ると結構長蛇の列になってたので、それより遅いとだいぶ待ちそう)

以下、参加レポ

- ほと氏
    - http://blog.hotolab.net/entry/techbookfest2
- ichigotake氏
    - http://ichigotake.hateblo.jp/entry/2017/04/10/042533
- わたし
    - http://mrtry.hatenablog.jp/entry/2017/04/09/235855

**Comment by mrtry** [comment]
(閉めとこうと思ったけど、ワイ立ててないから閉めれない模様)

**Comment by gomayumax** [comment]
いけなくてごめんなさい！！！豊作だった(らしい)
