### ISSUE TITLE
転職.beer

### ISSUE THREAD

**Issue by hoto17296** [ngineerxiv/dark#36]
ココ数ヶ月で転職(した|する)人を祝うという名目で酒が呑みたい

時間は 19:00 くらいから
転職してない人も祝いに来て！！

一覧： https://ngineerxiv.slack.com/archives/event-in-dark/p1488943075001018

**Comment by hoto17296** [comment]
調整さん： https://chouseisan.com/s?h=c4eb03301f9e43de9dbdcb3414b71ec5

**Comment by hoto17296** [comment]
( Issue に書いてなかったので書いておく )
21日(火) 開催です！！

**Comment by Omega014** [comment]
当日は .sake file(実体有り)を持って行きます

**Comment by hoto17296** [comment]
直近の転職者 **総勢12人** が集う善き会であった( ˘ω˘)
