### ISSUE TITLE
Docker手探り会

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#37]
https://ngineerxiv.slack.com/archives/C03GMD3QV/p1490788951025032

dockerの勉強会に行ったら
imageの管理ツールの話を聞くことになり
不完全燃焼感

Darkのメンバなら手探りでやれるやろ！！！
みんなでやれば怖くない

※私はよく理解してないので一緒に理解していきたい所存

**Comment by takumi-suzuki** [comment]
僕のオンプレ環境が火をふくぜ！！

**Comment by sota1235** [comment]
インフラの人視点のDocker解説聞きたいかも
PHPerのためのコンテナ活用みたいな話ならできそう！

**Comment by gomayumax** [comment]
とりあえず調整しよう
忘れないうちに

https://chouseisan.com/s?h=7b831ed2064540acb96e437ddd4d7e37

**Comment by gomayumax** [comment]
ほったらかしになってたわ  

**5/27(土)** にしようと思う
どうかな
@TasukuNakano @acchanAlexander @mrtry

**Comment by mrtry** [comment]
👍

**Comment by TasukuNakano** [comment]
空いているので先に予定を確定してもらえたほうが助かる

**Comment by mrtry** [comment]
デレスレライブいくので、私欠席します........... 🙇

**Comment by acchanAlexander** [comment]
5/27(土) いけるぜ！

**Comment by gomayumax** [comment]
場所を決めかねている

**Comment by acchanAlexander** [comment]
芭蕉ーーー！！
どうするか...

**Comment by TasukuNakano** [comment]
feedforce でやれるか聞いてみます？(みんなからは場所が遠いけど)

**Comment by gomayumax** [comment]
弊社むりぽっぽいのでfeedforce使わせていただけるならそうしたいです＞＜

@TasukuNakano 確認お願いします＞＜

**Comment by papix** [comment]
日曜日だったら教えに行けたけど残念

**Comment by TasukuNakano** [comment]
>弊社むりぽっぽいのでfeedforce使わせていただけるならそうしたいです＞＜

あっさり取れた。
時間だけ教えてくれたら本格的に抑えます @gomayumax @acchanAlexander @mrtry

**Comment by gomayumax** [comment]
14時とかでいいと思われ

**Comment by TasukuNakano** [comment]
feedforce の場所
https://www.feedforce.jp/corporate/access/

> 〒113-0034 東京都文京区湯島3-19-11 湯島ファーストビル5F
> 東京メトロ千代田線、湯島駅 徒歩約6分
> 東京メトロ銀座線、末広町駅 徒歩約6分

**Comment by TasukuNakano** [comment]
14:00 ~ 21:00 で抑えた

**Comment by gomayumax** [comment]
明日だわいわい

**Comment by TasukuNakano** [comment]
そうだ、オフィス自体がカードキーがないと入れないので、ついた人から順に私にメンション飛ばしてください。
当日は 13:00 頃あたりには会社にいる予定です

**Comment by gomayumax** [comment]
たまご氏がきます

**Comment by amymd** [comment]
ぎりぎりで申し訳ないですが参加したいです！！たまごです！

**Comment by gomayumax** [comment]
参加ありがとうございました！
たすく氏も会場提供ありがとうございます！

どっかーの理解が少しでも深まる会になった気がしてます！！
またやろうず(*ﾟ▽ﾟ*)
