### ISSUE TITLE
ボドゲ会 第2回

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#38]
# 目的
- ボドゲの面白さを再認識する
- 各人の素晴らしさ ~性格の悪さ~ を再認識する
- すずたくが置いてったカタン大航海版が邪魔なので遊ぶ

# 日付
5/5 14:00~

# 会場
ほとごま家
(大崎・五反田あたり)

# 内容
ボドゲをする

# 人数
~7人(キャパの都合)

参考: ボドゲ第1回 https://github.com/ngineerxiv/dark/issues/34

**Comment by gomayumax** [comment]
*switch で遊ぶ* というオプションもあります

**Comment by gomayumax** [comment]
調整して！！！！
https://chouseisan.com/s?h=9d427a479aed4cd6930b2f155df7f39f

**Comment by gomayumax** [comment]
**5/5** にします！！！

**Comment by takumi-suzuki** [comment]
19:00頃に行くー
酒、牛タン、筍？を持って行くかー

**Comment by ara-ta3** [comment]
行く気持ちがあります

**Comment by gomayumax** [comment]
GW暇な人まだまだ募集　|дﾟ)ﾁﾗｯ

**Comment by gomayumax** [comment]
明日14:00〜開催の気持ちでいます
家のキャパにまだ余裕があるので当日突撃参加もおｋです

**Comment by ichigotake** [comment]
突撃参加します :D

**Comment by gomayumax** [comment]
楽しかった(☝︎ ՞ਊ ՞)☝︎また性格悪くなってこ！
