### ISSUE TITLE
mastodonを立ててみる

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#39]
何をやればいいのかすらわかってないので整理したい
https://github.com/tootsuite/mastodon

**Comment by YOwatari** [comment]
始まるんだよォ！誰も見た事のねぇマスト ![image](https://cloud.githubusercontent.com/assets/4982161/25035250/61e95538-2127-11e7-9c40-ebb921fa1eb1.png)

**Comment by ara-ta3** [comment]
https://github.com/tootsuite/mastodon
README通り実行したら動いた

やったこと

- cp .env.production.sample .env.production
- docker-compose build
- .env.productionの修正
  - docker-compose run --rm web rake secret
    - 3回やって .env.production のSecretにそれぞれ設定した
    - https://github.com/tootsuite/mastodon/blob/master/.env.production.sample
- LOCAL_DOMAINを `mstdn.waka.ru.com` に変更
- ローカル用にLOCAL_HTTPSをfalseに
- smtpの設定は http://qiita.com/motiakoron/items/1e5b0679f7283bfee70b を元に s://app.sparkpost.com の設定をした

ドメインの問題でメールが飛ばないので一時休憩中
ローカルで動いている様子

![2017-04-14 20 32 51](https://cloud.githubusercontent.com/assets/2089153/25042262/9043321c-2151-11e7-9231-e3e8d482a29b.png)

**Comment by ara-ta3** [comment]
```
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_LOGIN=XXX@gmail.com
SMTP_PASSWORD=XXXXXXXXXXXXXXX
SMTP_FROM_ADDRESS=notifications@mstdn.waka.ru.com
```

smtpをgmailにしたらメールも飛んできた

**Comment by ara-ta3** [comment]
![IMAGE](https://cloud.githubusercontent.com/assets/2089153/25062309/3a66f39c-2205-11e7-97b4-819c2e20281f.png)

ローカルで動いた

**Comment by ara-ta3** [comment]
やーめっぴ
