### ISSUE TITLE
Dark BBQ 2016

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#4]
## 日程

6/12
調整さん
https://chouseisan.com/s?h=c4d1712bfc0f4602b7258691d964c3b6

## 参加者

約11名
まだまだ募集中

## 場所

多摩川かお台場を検討中
お台場キラキラ過ぎるので多摩川が良いのでは見たいな話までした。

## 残タスク

- [x] 予約

**Comment by mihyaeru21** [comment]
追加thx

**Comment by ara-ta3** [comment]
:komagata:

**Comment by ara-ta3** [comment]
このへんかなぁなどと考えてる
http://www.bbqtokyo.com/p-maruko.html

プランはこのあたり
http://www.bbqtokyo.com/bbqrental-bbqset.html

セットだけ借りて、残りはスーパーで買えば良さそう

**Comment by ara-ta3** [comment]
**予約**

丸子橋付近 + プランA + 12:00開始 + 11名で予約したった
http://www.bbqtokyo.com/bbqrental-order.html
この時間に集まれるのかとかめっちゃ不安なんだけど、15:30には撤収と言われたので、一旦12:00で予約した。

**前日までにやること**

今見たら12名だったので、変更あることも考慮して前々日くらいまで待つ。
前日までにキャンセル＋人数変更が可能なので、まあ前々日(10日)くらいには連絡しよう。

**当日必要なこと**

- 食べ物＋飲み物の購入
- 一人2100円の支払い
- 15:30撤収後の予定がないのでレジャーシートとか持ってきてもくもくするのありだなぁとか思った

**Comment by mihyaeru21** [comment]
青空もくもく++

**Comment by hoto17296** [comment]
日除けのテントみたいなのって借りれるのかな
こないだ多摩川で BBQ したけど日差し強すぎてつらかった
日焼け止め必須

**Comment by gomayumax** [comment]
http://www.bbqtokyo.com/bbqrental-bbqgear.html
テント追加セットであるみたいだけど、どうだろうか

**Comment by ara-ta3** [comment]
PlanAで予約しているからテントもついてくるはず！
http://www.bbqtokyo.com/bbqrental-bbqset.html#a

一応確認して見る所存

**Comment by jp-taku2** [comment]
ビールサーバーはいらないのですか！？

**Comment by Omega014** [comment]
前にBBQ参加者の誰かと話したとき、ビールサーバはいらないのではという話になったのを覚えている。
理由：
みんなが飲みそーなビール缶の処理が面倒だから持ち運び+後片付けやってくれるビールサーバ入れる方が楽では？という話だったけど、今回は片付けコミのプランで予約したので、缶でもいいかーという流れ（サーバは値段もそれなりにするしビール飲まない人もいるしね）

**Comment by jp-taku2** [comment]
そーだね。
ビール注文必要だけど、48本でいいかってなった気がする。
酎ハイ類は、個別で買う所存

**Comment by papix** [comment]
http://www.amazon.co.jp/%E3%82%BD%E3%83%88-SOTO-%E7%87%BB%E5%AE%B6-%E3%82%B9%E3%83%A2%E3%83%BC%E3%82%AF%E3%83%8F%E3%82%A6%E3%82%B9-ST-114/dp/B000AR1KGQ/ref=sr_1_1?ie=UTF8&qid=1465317682&sr=8-1&keywords=%E7%87%BB%E8%A3%BD これ買っていいですか?

**Comment by gomayumax** [comment]
燻製最高っぽい！！
BBQ滞在時間内に完成するかだけ気すれば行けそう₍₍⁽⁽(ી( ･◡･ )ʃ)₎₎⁾⁾

**Comment by ara-ta3** [comment]
事前の買い物は新丸子駅付近のスーパーかなとか考えてるところ

11時に駅集合して買い物してから行けばいいかなー
https://goo.gl/maps/p5bvJomyUou

**Comment by gomayumax** [comment]
天気予報は今のところ「くもり」でっす！

http://www.jma.go.jp/jp/week/319.html

**Comment by ara-ta3** [comment]
降水確率昨日見たら40%だったけど、今は20%なので行けるかな

**Comment by ara-ta3** [comment]
確認の電話とかした

やったこと

- 人数12名に変更

確認したこと

- Q. テントっぽいのは12名なので2つ借りれる？
  - A. Yes
- Q. 丸子橋の下に12時までに行ってそこで金を払うって認識でおｋ？
  - A. Yes 金額は 25,200 JPY
  - (= (* 12 2,100))
- Q. キャンセルっていつまで？
  - A. 明日の12:00 JST

**Comment by ara-ta3** [comment]
ビールの様子

```
jp_taku [14:33]  
ビール24本で注文しちゃうよ？

arata [14:33]  
おｋ〜

jp_taku [14:35]  
買い出しとかは？
primenow?

arata [14:35]  
primenowで肉頼むの斬新だ

[14:35]  
11時新丸子集合で買いに行こうかなみたいな気持ち

jp_taku [14:36]  
りょ！
何時にスタートだっけ？

arata [14:36]  
12時スターツ！

jp_taku [14:37]  
じゃー、10分前位に届くようにしよー

```

**Comment by ara-ta3** [comment]
明日の予定

11時に新丸子駅集合して
https://goo.gl/maps/5u7jNKktppn

買い物をまいばすけっと新丸子東口店で済まして
https://goo.gl/maps/sRZpvkmrQUB2

12時前くらいに丸子橋付近までたどり着くイメージ
（大体この辺） https://goo.gl/maps/o7Ax1YQkYY92

具体的な場所は12時前くらいに電話が来るらしい
その後は肉を食らう

**Comment by ara-ta3** [comment]
BBQよかった。またしましょう。
http://papix.hatenablog.jp/entry/2016/06/13/120353

**Comment by ara-ta3** [comment]
#event-in-dark 用のテスト
