### ISSUE TITLE
最高級イタリアンを堪能する

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#40]
＿人人人人人人人人＿
＞　 サイゼリヤ　＜
￣^Y^Y^Y^Y^Y^Y^Y^Y￣

調整しましょう
https://chouseisan.com/s?h=bd72fa4fd03f41e29742d23505a67fdf

**Comment by isaoeka** [comment]
done

**Comment by mrtry** [comment]
done

**Comment by sota1235** [comment]
done

**Comment by gomayumax** [comment]
**5/14(日) 17:00~** にしよう

**Comment by ara-ta3** [comment]
http://omocoro.jp/kiji/109284/

**Comment by mrtry** [comment]
そういえば、場所ってどこでしょ？
五反田ですか？

**Comment by gomayumax** [comment]
五反田の土日はどの店も空いている傾向にあるので  
五反田にしようと思っていた

**Comment by mrtry** [comment]
わいわい

**Comment by isaoeka** [comment]
ミラノ風ドリア高級にして満喫したい

**Comment by gomayumax** [comment]
ピザの贅沢切りして食べにくさを堪能したい

**Comment by gomayumax** [comment]
【感想】
ピザの贅沢切りは、思ったよりも贅沢だった
温玉ガッ、ワインガッは微妙だった
ミスドは、ミスドであるか怪しいけど美味しかった
4時間飲み食いして2200円のだった
最高級イタリアンすごい
