### ISSUE TITLE
納涼祭

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#43]
![](http://4.bp.blogspot.com/-43BOmoYL000/UqmPTeWcFHI/AAAAAAAAbhE/z3q7GaHiO9M/s800/chouchin_matsuri.png)

# 概要
納涼が目的です
涼しくなることならなんでもおk
夏を感じることならなんでもおｋ
お祭りっぽければなんでもおｋ

# 日付
**8/10(木) 19:00~**

# 会場

```
arata
[1:43 PM] 
会場提供が必要という話なら我が家か会社の会議室貸しまする
```

🙏 ＜圧倒的感謝!!!!
人数次第でどちらか決めます

↓

VOYAGE社のジパングっていう部屋

# やりたいこと(夢)
- エンジニア怪談
    -  **肝の冷えるやっちまった談**とかいい
    - 最後はキレイにまとめなくていいですよ？今も肝ヒエヒエみたいな落ちでもおｋ
- 出店メシを食べる
    - 祭りといえば出店
    - 焼きそば!!かき氷!!!
    - フランクフルト!!
    - びあー
- 祭りっぽいこと
    - すてきな案を募集中...

# 調整するぞ！！！

体力の都合上
休前日と休み中日に限定してます
あと納涼って8月までだとおもうから8月いっぱいまで！！

https://chouseisan.com/s?h=e23d3febd0644a0abd73783c875a3f2c

**Comment by gomayumax** [comment]
8/10(木)19:00~ : 祝日の前日の機運

**Comment by ara-ta3** [comment]
畳部屋のジパング取った

**Comment by gomayumax** [comment]
8/10(木)19:00　で、きーめた！！

[いまのところ参加予定]
arata mihyaeru21 meru acchan kirin 

**まだまだ募集中です！！納涼しよう！**

**Comment by gomayumax** [comment]
今日です！！！

やることとしては下記

- エンジニア怪談LT
- 花火 / お祭り動画を見ながらお祭りぽいものを食べる

あと何か思いつきでやります

**Comment by gomayumax** [comment]
楽しかった！！！

また来年の夏
