### ISSUE TITLE
びっくりドンキーのあの大きいメニューを見てワクワクしたい

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#44]
# 概要
びっくりドンキーでご飯を食べる
シンプル
前に1回やったけどログがない(twitter探せばあると思うので探しておこう)

## びっくりドンキーの良さ
- メニューが窓の形していて馬鹿でかい
- 店内が不思議空間、ワクワクする
- パフェとドリンクが頼みたくなる
- ディッシュと呼ばれるメニューに夢中

# 調整する

https://chouseisan.com/s?h=6d3f2b0046be4b8f8640777e879ced36

**Comment by mrtry** [comment]
ビールが！！！！！！！！！！！
飲みたい！！！！！！！！！！！！！！！！！！！！！！！

**Comment by gomayumax** [comment]
調整さん書いた！！！

ディッシュとパフェが食べたい！！！

**Comment by mrtry** [comment]
今週日曜か...? 👀  (超ビール飲みたい)

**Comment by gomayumax** [comment]
昼なら行けそう！！！！
8/20 13:00~ いける？

mrtry acchan isaoeka

**Comment by mrtry** [comment]
👌👌👌👌👌👌

**Comment by acchanAlexander** [comment]
:thumbsup::thumbsup::thumbsup::thumbsup::thumbsup::thumbsup::congratulations:

**Comment by mrtry** [comment]
ところで、どこのびくドンなんでしょ

**Comment by gomayumax** [comment]
前は新宿に行った
東京ドームシティにもあるらしい

https://www.bikkuri-donkey.com/shop/tokyo/

**Comment by isaoeka** [comment]
🕺🕺🕺 行けそう祭り🕺🕺🕺

**Comment by gomayumax** [comment]
決めちゃいます！！

明日 13:00に
新宿店前集合！！！

google: 
びっくりドンキー 新宿靖国通り店
〒160-0022 東京都新宿区新宿５丁目5−17−13 オリエンタルウェーブビル
03-5291-9610
https://goo.gl/maps/mLczMHcENAH2

公式: https://www.bikkuri-donkey.com/shop/detail.html?sh=1062&pref=tokyo

人数少ないし都合悪けりゃ調整する

**Comment by gomayumax** [comment]
学生気分を思い出して楽しかった！！
次は埼玉のローカルハンバーグが食べたいという話題が出たな(((o(*ﾟ▽ﾟ*)o)))
覚えておこう
