### ISSUE TITLE
学生気分の気持ちを取り戻す飲み会をする

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#46]
予算を決めて飲み会をするとか

**Comment by mrtry** [comment]
寒いので、鍋をやりたい気持ちが高まっております。
なお私の家には大きめの土鍋と電熱器がある模様。

**Comment by mrtry** [comment]
学生気分を思い出して鍋を囲む会の調整さんです！！！！
私んち、最寄りが南柏駅で遠いので、それでも良い方いたら😼
(帰りのこと考えて、スタートは16時にしときました)

https://chouseisan.com/s?h=b1cb00136c91481eb681c05fc4b48c80

**Comment by mrtry** [comment]
11/25(土) 16:00 ~ かなという気持ち
mrtry家で鍋したい人いたらきてくださいませ(千葉/柏)

https://chouseisan.com/s?h=b1cb00136c91481eb681c05fc4b48c80

**Comment by gomayumax** [comment]
記入どぅーん

**Comment by mrtry** [comment]
予定している鍋
- 牛鍋
- みぞれ鍋
- よせ鍋

なんかもうひとつぐらいリクがあったきがする........

**Comment by mrtry** [comment]
キムチ鍋だった

**Comment by mrtry** [comment]
現在の鍋候補
- 牛鍋
- みぞれ鍋
- よせ鍋
- キムチ鍋

ですが、シメとか食べると考えると、2種類かな〜〜〜〜〜という気がしている
参加する人に、好きな鍋選んで投稿してもらうかな〜〜〜〜〜

流れると面倒なので、このIssueのコメントで食べたい鍋を書いてほしいです！！！！

## 回答用テンプレ的なやつ

第一候補: 牛鍋 / みぞれ鍋 / よせ鍋 / キムチ鍋 / その他あったら名称をここで挙げてくれ
第二候補: 牛鍋 / みぞれ鍋 / よせ鍋 / キムチ鍋 / その他あったら名称をここで挙げてくれ

**Comment by noainoue** [comment]
第一候補:寄せ鍋
第二候補:キムチ鍋

**Comment by mrtry** [comment]
第一候補: みぞれ鍋
第二候補: キムチ鍋

**Comment by iga-yamaguchi** [comment]
1. キムチ鍋
1. よせ鍋

**Comment by ara-ta3** [comment]
第一候補:みぞれ鍋
第二候補:寄せ鍋

**Comment by rnitame** [comment]
第一候補: キムチ鍋
第二候補: みぞれ鍋

**Comment by gomayumax** [comment]
第一候補: キムチ鍋  
第二候補: みぞれ鍋

**Comment by rnitame** [comment]
第一候補はキムチが3票かな？第二候補は寄せ鍋かみぞれか

**Comment by mrtry** [comment]
キムチ確定で、「寄せ」or「みぞれ」を決めるか〜〜〜〜〜〜〜
どっちがいいです？

私は、みそれ鍋が良いです

**Comment by acchanAlexander** [comment]
第一候補が決まったっぽいので、
第二後方に寄せ鍋を一票

**Comment by acchanAlexander** [comment]
あ、嘘です、行けないです。
https://github.com/ngineerxiv/dark/issues/56
と勘違いしてた。。

**Comment by noainoue** [comment]
あっちゃん・・・・・・😇

寄せ鍋も王道でいいのだけれど、良く考えたらみぞれ鍋食べたことないのでみぞれ鍋に一票！

**Comment by rnitame** [comment]
みぞれがよい！

**Comment by iga-yamaguchi** [comment]
これはみぞれ決定だな

**Comment by mrtry** [comment]
解答してない人ら、みぞれって元々言ってた人だし、みぞれでいいか。

**Comment by mrtry** [comment]
じゃ、`みぞれ鍋` `キムチ鍋` ってことで〜〜〜〜〜〜〜〜

**Comment by Omega014** [comment]
バイクが動いたら+良さそうな駐車場が近くにあったら参加する！

**Comment by mrtry** [comment]
おっ
良さげかわからないけど駐車場マンション真横にある

onepark
〒277-0075 千葉県柏市南柏中央７−５

https://goo.gl/maps/GWvGuMLe52m

**Comment by mrtry** [comment]
料金表はこれか
http://search.ipos-land.jp/p/detailp.aspx?id=COP290512

**Comment by mrtry** [comment]
明日鍋パだ〜〜〜〜〜〜

雑に、こんな感じのつもりです
- 15時に南柏駅に集合
- そのまま買い物
- とらい家に食材運搬
- 17時ぐらいに食べ始め

その後は、家で遊ぶのも良し、カラオケ行くのも良しという感じです
(私の家はスイッチとトランポリンぐらいしか遊ぶものがないです 😇 )

**Comment by Omega014** [comment]
ならしで多摩川走ったらバイクに満足してしまったので今日の鍋パはパス✋
みんなで楽しんで！

**Comment by ara-ta3** [comment]
https://github.com/ngineerxiv/dark-bot/pull/272

**Comment by ara-ta3** [comment]
学生の気分、また取り戻していきましょう
