### ISSUE TITLE
【リアル脱出ゲーム】ホウオウの試練からの脱出に行く

### ISSUE THREAD

**Issue by isaoeka** [ngineerxiv/dark#47]
![](https://4.bp.blogspot.com/-8_goph-KBiA/V7kyNuAcC5I/AAAAAAAA9Ls/Uhyl8AbSnikQycDKcdOStT9SMMOB8Z4qACLcB/s450/nigaoe_harry_houdini.png)

## ホウオウの試練からの脱出 is 何

http://realdgame.jp/pokemon/main/

初心者だけど、博士コースに挑みたいお気持ち。

## 日程

`#realdgame` 、又はこのissueにて調整予定
（調整さん忘れるので雑に決めたい

### [日程候補](https://www.0553.jp/scrap/events/index?content_code=poke2017&shop_id=99)

とりあえず9月に行けたら良さそう。
- ~2017年09月09日(土)~ : PyCon 2017がありNG
- 2017年09月10日(日)
- ~2017年09月16日(土)~ : iOSDC 2017がありNG
- ~2017年09月17日(日)~ : iOSDC 2017がありNG
- 2017年09月23日(土) 
- 2017年09月24日(日) 

## 場所

[東京・下北沢ナゾビル](http://realdgame.jp/ajito/shimokitazawa/access.html)

## 雑記

参加人数とかの調整不要な奴なので、良しなに行きたい

**Comment by TasukuNakano** [comment]
この前参加したけど、博士コースでも割りと問題は優しい方やで。最後の問題だけ難しいけど

最初のポケモン3匹選んで別れるけど、ルートが違うだけで特別何か違うわけでもないから、人数多ければ 3 チームに分けるの良さそう。


あと、街歩きなので歩きやすい服装、靴が必須。
時間は 2 時間もあれば終えられる感じかなーと。

**Comment by isaoeka** [comment]
:arigatou: なるほど、徐々に難易度高めのに挑んでいきたい。

**Comment by acchanAlexander** [comment]
午前中は予定があって、夜はdarkイベントなので
13:00 ~ 18:00とかの間だと嬉しさ
もし無理そうだったら私は置いてってください

**Comment by ara-ta3** [comment]
close？

**Comment by isaoeka** [comment]
close! 🙇
