### ISSUE TITLE
そろそろサイゼ行くぞ！！

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#49]
【定期】最高級イタリアですよ

店舗はいつも悩むんだけど
オススメあればそこで
なければ五反田になります

【調整さん】
https://chouseisan.com/s?h=b8ed6aa55ba2492a938face6d9122a53

※このissueはサイゼで書いています

**Comment by gomayumax** [comment]
調整さん追記したのでガンガン書いてこ↑↑

**Comment by gomayumax** [comment]
9/3(日)17:00~になりそう

**Comment by gomayumax** [comment]
リスケ申し訳なかった！！！！＞＜

今週末9/15(金) 20:00〜でいかがだろう
夕飯は最高のイタリアン
（´-`）.｡oO（個人的にMTG差し込まれていて遅れる予感がある

**Comment by mrtry** [comment]
参加できるはず！
場所は銀座のサイゼですよね？

**Comment by gomayumax** [comment]
> 場所は銀座のサイゼですよね？

ですです＼＼\\ ٩( ‘ω’ )و //／／

**Comment by acchanAlexander** [comment]
15予定が入ってしまった〜:joy:
他の人で予定合いそうなら行ってくだせぇ:bow:

**Comment by Omega014** [comment]
先約入ってたので見送り

**Comment by isaoeka** [comment]
逆に行けそう

**Comment by acchanAlexander** [comment]
会社飲み会があるんだけど、会社飲み終わってまだサイゼやってたら行くんご

**Comment by isaoeka** [comment]
もう腹減りが限界に来てる

**Comment by gomayumax** [comment]
こちらメニューをご覧になってお待ち下さい
http://www.saizeriya.co.jp/menu/grandmenu.html
