### ISSUE TITLE
たこ焼きをする会

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#5]
あらた氏の家でたこ焼きがしたいです

**Comment by ara-ta3** [comment]
いつにしよう。
平日夜から？それとも土日？

**Comment by gomayumax** [comment]
調整さぁあああああああん！！！

https://chouseisan.com/s?h=824dc23321844b5a8e21afce543fb4dc

**Comment by ara-ta3** [comment]
とりあえず7/8で確定なんかな

**Comment by gomayumax** [comment]
あらたし7/8家空けといてくだされ

**Comment by ara-ta3** [comment]
今週だ。19:00には家にいる所存。
Amazonで家になさそうなものは頼んだけど、どうせ酒がないのでスーパーに買いに行きませう

家の場所は一応Slackにはるかなｗ

**Comment by ara-ta3** [comment]
またやりましょうヽ(´▽｀)ノ

**Comment by acchanAlexander** [comment]
次は行きたし
