### ISSUE TITLE
Dark ISUCON 予習会 - DAICON 2017

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#50]
https://github.com/ngineerxiv/dark/issues/9

https://ngineerxiv.slack.com/archives/C0ACAFGJE/p1504847310000022

```
hoto [14:08] 
ポータルとかは去年作ったコレ使い回せば楽そうなので、
あとは練習問題なににしようっていう問題がある
http://blog.hotolab.net/entry/isucon_portal
```

**Comment by ara-ta3** [comment]
テーマ探していい感じに作れそうだったら実施しませう

**Comment by papix** [comment]
DAIKONじゃん https://ja.wikipedia.org/wiki/DAICON_FILM

**Comment by hoto17296** [comment]
[去年の予選問題](https://github.com/isucon/isucon6-qualify) ならあるけど AMI は公開されてないな
作ればいいっちゅう話だけど

**Comment by ara-ta3** [comment]
去年の問題、さくらのインスタンスでぽちぽちやったら一応起動できたからそれを頑張ってもいいかも？
https://gist.github.com/ara-ta3/706f3ed831ac900c060280e1c4d438dc

**Comment by ara-ta3** [comment]
一応やった
次は振り返り会
