### ISSUE TITLE
物理最高だよ？（ボドゲしたい）

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#51]
イカ断ちをしています、ご協力お願いします

# 日時
9/16(土) 15:00 (ちょっと遅めにしたよ）
三連休初日

# 概要
ボードゲームをしよう

## ごま家から持ち寄るボドゲ
- 深海探査
- mojibake
- color code
- 名刺じゃんけん
- 藪の中
- インサイダー
- 猫と死体と12人の容疑者
- THE 修学旅行の夜

**Comment by gomayumax** [comment]
参加表明をslackなり、issueでしてくれると信じてる

**Comment by gomayumax** [comment]
場所はボヤ社

**Comment by acchanAlexander** [comment]
流れるのでこちらにも
これにいくので、18:00くらいでもやってればいこうと思う
https://supporterzcolab.com/event/141/

**Comment by ara-ta3** [comment]
これ誰が来るんだろｗ

おじゃまもの買ったったのでやりたい
会社のジパングを取得済みです

**Comment by hoto17296** [comment]
ほとごま + あらた + もう二人 (+ あっちゃん)
かな？

**Comment by ara-ta3** [comment]
もう二人くるのか
よかった、3人でボドゲかと思って焦っていたｗ

**Comment by gomayumax** [comment]
あと ichigotake さん来る　₍₍⁽⁽(ી( ･◡･ )ʃ)₎₎⁾⁾
