### ISSUE TITLE
ボドゲするよ 2017/11/18(土)

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#52]
# 日時
11/18(土) 
何時がいい？？

# 概要
ボードゲームをしよう
ルールが難しいやつはじめにやって、後半は楽なやつやりませう

# 場所

VOYAGE GROUP 8F ジパング
8人超えると辛くなるので場所変えるかも

### 過去のボドゲ
https://github.com/ngineerxiv/dark/issues/51

**Comment by ara-ta3** [comment]
聞いてる限りの現状参加者5名(あらた、ほとごま夫婦、すずたく氏、りほ氏、まりな氏）
他にも参加する人slackやらここでやら書いてくれるとうれしい

**Comment by gomayumax** [comment]
14時？

**Comment by acchanAlexander** [comment]
行くんご！

**Comment by ara-ta3** [comment]
14時かな

**Comment by ara-ta3** [comment]
明後日じゃん？
14:00にはいるようにします
場所は畳の部屋です

**Comment by acchanAlexander** [comment]
最高っぽい
http://www.animatetimes.com/news/details.php?id=1510731832

明日時間あって買えたらもっていきます。

**Comment by ara-ta3** [comment]
レンタカー借りて温泉行くこともなく無事終了
