### ISSUE TITLE
技術書典に行く@10/22(日)

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#54]
技術書の同人誌を買ってニヤニヤする

# 日時
10/22 10:30現地集合

# 詳細
https://techbookfest.org/event/tbf03

# メンバー
gomayumax c5meg1012 mrtry acchanAlexander
※集まっても集まらなくても一人で行くけどなッ(´；ω；｀)
現地にnayu氏がいる気がしてる

**Comment by nayucolony** [comment]
サークル出展してます:)

**Comment by c5meg1012** [comment]
polidog氏登山につき参加！
技術書典はじめてだ〜

**Comment by mrtry** [comment]
いきたい！！！！！！！
副業の給料日後だから気になったものは全部買う勢いで行きたい！！！！！！

**Comment by gomayumax** [comment]
わいわい
やったぜ！ぼっち回避！

10:30に現地集合( アキバ・スクエア )という強気の設定でいく

**Comment by nayucolony** [comment]
各位
今回は整理券方式なので公式サイト及び公式ツイッターアカウントを見てください！

**Comment by acchanAlexander** [comment]
行くンゴ

**Comment by mrtry** [comment]
行く気まんまんだけど、台風心配マン

**Comment by nayucolony** [comment]
大丈夫大丈夫！

**Comment by gomayumax** [comment]
雨の中ありがとうございました！！
来年も行きたいっす
