### ISSUE TITLE
ISUCON7振り返り会 at 11/04, 11/11

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#55]
場所はVGいつものユーラシア（緑の部屋）
https://github.com/isucon/isucon7-qualify

http://isucon.net/

復習は早いほうが良いと思うのでやりましょう。
どっちも既に部屋取ってるので、来れる人は

`11/04, 11/11 行きます！` 

的な感じにこのissueか、slackのチャンネルに書いてもらえると嬉しいです。

**Comment by gomayumax** [comment]
11/04, 11/11 行きます！

**Comment by hoto17296** [comment]
11/04 だけいく

**Comment by iga-yamaguchi** [comment]
11/4行きます
11日は直前にならないと分からんです

**Comment by ara-ta3** [comment]
時間は体力的に14:00が好ましいです・・・

**Comment by mihyaeru21** [comment]
4元気あれば行く

**Comment by gomayumax** [comment]
明日何人来るんだろう....🤔

2,3人とかなら行くのやめようかなと思い始めた

**Comment by ara-ta3** [comment]
確かに。
確実に来そうなのは、ごま氏と自分か
来たとしてもいがにん氏かな

それならやめとくか

**Comment by ara-ta3** [comment]
Slackで話して、なしな感じにしますた
またやりませう
