### ISSUE TITLE
レンタルスペースを借りて、ご飯作って、ウェイしたい

### ISSUE THREAD

**Issue by mrtry** [ngineerxiv/dark#56]
## 概要
- タイトルそのまま
- キッチンあるとこかりて、みんなでご飯準備して、お酒飲んで、ウェイしたいですねっていう感じです

## 候補地
- bird_tummy曰く、以下がオススメらしい
- プロジェクターとスクリーンもあるとのことです
    - http://ikejiri-select-house.p2.weblife.me/

**Comment by Omega014** [comment]
広いキッチンで料理したい、ウマイメシが食いたい

**Comment by rnitame** [comment]
http://ikejiri-select-house.p2.weblife.me/1f.html

使えるものはここに ↑

**Comment by mrtry** [comment]
調整さんです！！！！
準備あったりするとおもうので、15時に設定してみました👏
https://chouseisan.com/s?h=e7a5dc5f6b8b4774b0aa6dbc63867bb7

**Comment by gomayumax** [comment]
入力done

**Comment by mrtry** [comment]
12/2(土)かな...?
https://chouseisan.com/s?h=e7a5dc5f6b8b4774b0aa6dbc63867bb7

**Comment by mrtry** [comment]
日付は12/10に決定のつもり
https://chouseisan.com/s?h=e7a5dc5f6b8b4774b0aa6dbc63867bb7

で、候補に上げてた場所なんですが、埋まっていることに気づきました 😇 
http://ikejiri-select-house.p2.weblife.me/booking_calendar.html

場所どうしましょうね 😇

**Comment by gomayumax** [comment]
> 日付は12/10に決定のつもり

お家探しでいけなくなったごめんなさい(´・ω・｀)

**Comment by mrtry** [comment]
ほとごま氏、だめなの了解っす
今のとこ6人かーーー。
スペース今週中に探します😇

**Comment by jp-taku2** [comment]
わいもダメそ

**Comment by papix** [comment]
ワイはいける

**Comment by ara-ta3** [comment]
これは延期かな？

**Comment by mrtry** [comment]
そんな気持ちになってます。
年末までイベントいろいろあるし、来年にしません? 😇

**Comment by ara-ta3** [comment]
年明け早め（？）hotogomaが引っ越す前あたりが良さそう

**Comment by Omega014** [comment]
ほとごま家の食材消化をこのイベントでやるってものアリかも

**Comment by ara-ta3** [comment]
面白そう
ほとごま家付近にして、みんなで食材持っていってやるの楽しそう

**Comment by mrtry** [comment]
トマト缶フェス(?)になりそうで面白げ

**Comment by gomayumax** [comment]
ありだな＼＼\\٩( 'ω' )و //／／
でも絶対に食材置いてくなよ！！絶対だぞ！！フリじゃないぞ！！

**Comment by jp-taku2** [comment]
わい、お米なら持ってける！

**Comment by mrtry** [comment]
開催したさあったけど、かなり高まらないと頑張れなさそうなので、閉じておく
