### ISSUE TITLE
日本酒飲みたい

### ISSUE THREAD

**Issue by rnitame** [ngineerxiv/dark#57]
https://ngineerxiv.slack.com/archives/C034QSSPA/p1509009619000162

この辺からの流れ

行き先は
https://ngineerxiv.slack.com/archives/C034QSSPA/p1509010546000012
で決める？

（候補）
渋谷「米心」
恵比寿「麦酒庵」
神泉「mocchi」
吉祥寺「日本酒や」
四ツ谷「燗コーヒー藤々」
銀座「ナラシバ」
阿佐ヶ谷「SUGAR」
自由が丘「金田」
新宿「方舟」
https://tabelog.com/tokyo/A1316/A131601/13176012/
https://tabelog.com/tokyo/A1301/A130101/13016562/
https://tabelog.com/tokyo/A1316/A131601/13034404/
https://retty.me/area/PRE13/ARE1/SUB105/100000703400/
https://junmaishu.net/
https://tabelog.com/tokyo/A1305/A130503/13187906/
https://tabelog.com/tokyo/A1316/A131603/13122590/
https://tabelog.com/tokyo/A1310/A131001/13171817/
http://sake-genkabar.com/

**Comment by gomayumax** [comment]
レビューお願いします

```shell
SHOPS=('日本酒原価酒蔵' 'きさらぎ はなれ' '酒場それがし' '太閤' 'YATA （やた）' 'こころむすび' '風音' '庫裏' 'いと' '方舟' '金田' 'SUGAR' 'ナラシバ' '燗コーヒー藤々' '日本酒や' 'mocchi' '麦酒庵' '米心')
NUM=$(($RANDOM % 18))
echo ${SHOPS[$NUM]}
```

**Comment by rnitame** [comment]
LGTM! 
ガチャの結果、庫裏になりました
https://tabelog.com/tokyo/A1301/A130101/13016562/

![image](https://user-images.githubusercontent.com/4950792/32046916-6546bc60-ba7f-11e7-991f-4a8130426918.png)

**Comment by gomayumax** [comment]
雑に調整さん作った
雑すぎたかもしれない

https://chouseisan.com/s?h=c722a09d3cbf4813ae697f629b07b78e

**Comment by gomayumax** [comment]
店が日曜休みだ(´・ω・｀)

**Comment by gomayumax** [comment]
> bird_tummy [11:19 PM] 
> 15 か 20 あたりかな

わかる。15日でいいでしょう
(omega 氏来れないの残念なので、第1回をさっさとやって、第2回をやろう)

**Comment by rnitame** [comment]
よっしゃ！15で！

**Comment by rnitame** [comment]
https://yoyaku.toreta.in/kuri/#/

5名以上は新橋じゃないとだめだそうなので、新橋店に今夜電話しまーす

**Comment by rnitame** [comment]
（書き忘れてた）
電話したんだけど、19時半までに来店できる場合じゃないと予約できないらしい。
誰かいけそう…？

![image](https://user-images.githubusercontent.com/4950792/32208615-eade61dc-be46-11e7-8b4d-8787d6513db1.png)

**Comment by ichigotake** [comment]
なんとなく🍶ガチャを作った

https://sake-button-cbb77.firebaseapp.com/

**Comment by rnitame** [comment]
申し訳ないんだけれども、仕事が 🔥 な感じになってきたので延期したい。。

**Comment by gomayumax** [comment]
となると,,,11/20(月)かな？

みんなの予定に変更なければということで再度調整さんの確認お願いします

**Comment by mrtry** [comment]
わたしはへんこうない〜〜〜〜〜〜〜〜〜〜〜〜

**Comment by atariyo** [comment]
20おけすー！

**Comment by ichigotake** [comment]
🙆

**Comment by urataku** [comment]
20すまぬ、予定入ってしもた…調整さん更新します

**Comment by rnitame** [comment]
いったん、15日の予約キャンセル done

**Comment by mrtry** [comment]
第1回目の日本酒会は、おめが氏とたみー氏のおすすめのここにいってきた
https://ngineerxiv.slack.com/archives/C1G9NUU2D/p1510655452000174

日本酒いっぱいあったし、海鮮がいっぱいで、よかったです！
そのうち第2回目もしたいですね！

**Comment by mrtry** [comment]
@rnitame Issue閉じといてくれると 🙇
