### ISSUE TITLE
そうだ、猫カフェにいこう！

### ISSUE THREAD

**Issue by noainoue** [ngineerxiv/dark#58]
# 猫、みんなすきだよね？
みんな大好きな猫をなでなでもふもふ・・・
都会の喧騒から少し離れて、日々の疲れを癒しにいこう。
## こんな人におすすめ！
- 人間に疲れた・・・猫と会話したい・・・
- 猫を飼うことができない環境にある
- あまり触れることがなかったが、みんながいくなら行こうかな

そんな人はぜひこのイベントに参加してください。
猫はいいぞぉ〜(小並感)

## 概要
日程は11月25・26日あたりで検討中
tryさん宅での鍋パ(https://github.com/ngineerxiv/dark/issues/46)
上記イベントの開催時間前後で予定しています。(参加者もまだまだ募集してますよ。)
柏駅近くで猫カフェは調査中
詳細は参加者で固めていきましょう。

## 猫カフェ候補
- 「猫の手」参考記事(http://mrs.living.jp/kashiwa/town_gourmet/reporter/2091036)
- 「ニャフェ・メランジェ」(http://www.nyafe-melange.com/)

## 参加者
- noainoue
- meru(26のみ可)
- mrtry
- gomayumax
- iganin
- arata

**Comment by mrtry** [comment]
お昼に猫カフェよさそう

**Comment by gomayumax** [comment]
柏駅に猫カフェがなかったら
候補としてご検討ください

http://www.nyafe-melange.com/
(恵比寿の猫カフェ: こじんまりとした猫カフェ、猫はしょうがねぇなーって感じでかまってくれる)

**Comment by noainoue** [comment]
> 猫はしょうがねぇなーって感じでかまってくれる
これ笑うww猫様だ！ww

**Comment by gomayumax** [comment]
仕事のやる気が無いので調べた

柏の猫カフェ
https://twitter.com/22nekote

**Comment by noainoue** [comment]
マリモちゃんが可愛すぎて禿げそう

**Comment by noainoue** [comment]
調整さん作りました！
参加希望の方は参加可能日程をご記入ください！
https://chouseisan.com/s?h=564b7281f2e54b158fd0c24537da3708

**Comment by noainoue** [comment]
申し訳ないです、もう一度調整さんにご記入いただけたら嬉しいです

**Comment by noainoue** [comment]
こちら締め切ってもよいですか〜？？
他に猫カフェ行く人はいませんか〜？？

**Comment by noainoue** [comment]
猫カフェ参加者締め切ります！！
日程は11月26日です。(あっちゃんごめんなさい・・・)
参加メンバーは下記の通りです！


＝＝＝＝＝＝＝＝＝
のあのあのーあ
mrtry
める
goma
いがにん
ara_ta3
＝＝＝＝＝＝＝＝＝
以上6名

日程は11月26日に決定しましたが、時間と場所が決まっていません。
なお25日の鍋パ後でなくなったので、都内でもいいかなと考えております。
時間と場所に関して、みなさんの意見くださいませ〜！

**Comment by ara-ta3** [comment]
そういえば時間と場所どうしよう

**Comment by noainoue** [comment]
朝方〜昼まで
もしくは
夕方〜夜希望

**Comment by ara-ta3** [comment]
その2択なら夕方がいいな〜
（前日学生気分で鍋をやってるので社会人の体に現実が突きつけられていそう

夕方からって言うと16:00くらいからの感じかなぁ〜

**Comment by ara-ta3** [comment]
場所、自分で選ぶと渋谷・恵比寿・新宿あたりから探そうとしてしまうので、
柏方面の二人(いがにん氏もだよね？)がちょうどいい感じの場所ってどこなんだろうというのを把握したくなってきている

**Comment by iga-yamaguchi** [comment]
そこらへんは気にしなくていいですよー
渋谷とか品川近辺なら大丈夫です。
あまり西すぎると遠くなっちゃうので東寄りだとありがたいですが

**Comment by mrtry** [comment]
ごめなさ。
副業のリリースがあったりで、いけなさそうです 😇

**Comment by ara-ta3** [comment]
とりあえず渋谷・恵比寿・新宿あたりで調べるか・・・

**Comment by acchanAlexander** [comment]
開発合宿に行ってるんだけど、
18:00頃に品川に戻ってくるので、時間があえば顔だけ出しにいきますー！

僕のために時間ずらしたりしてもらわなくていいので、もし時間がちょうどあえばで！

**Comment by iga-yamaguchi** [comment]
場所についてだけど下記どっちかでいいんじゃないかなーって思ってます。

- 渋谷 MOCHA http://catmocha.jp/shibuya/
- 恵比寿 ニャフェ・メランジェ http://www.nyafe-melange.com/

MOCHAは友達が行ったことあって評判良かった
ニャフェはごまさんからのおすすめ

**Comment by c5meg1012** [comment]
MOCHA、池袋のやつなら行ったことあるけど、どの店舗もおしゃれだった
人気店だから混むかもしれない

**Comment by ara-ta3** [comment]
MOCHA渋谷でいっかみたいな話をした
何時にしようかな

**Comment by ara-ta3** [comment]
16:00に現地集合でいいかな

- 場所
  - 渋谷MOCHA
  - https://goo.gl/maps/Fct2ta7uqJ92
- 参考
  - http://catmocha.jp/shibuya/

**Comment by c5meg1012** [comment]
旦那氏の体調だいぶ落ち着いてきたけど、念のため引き続き、様子見しようと思うので、残念ながら見送ります...当日で申し訳ないです！
ふええネコちゃん〜(´；ω；｀)

**Comment by noainoue** [comment]
めるさんのために写真とります。
🐈カフェの場所はめるさんが勧めてくれた処で異議なし！
あと、時間は17時か18時が希望！

**Comment by iga-yamaguchi** [comment]
18時に現地集合にしましょ

**Comment by ara-ta3** [comment]
https://photos.app.goo.gl/xB5gflu4SpsZWNl23
