### ISSUE TITLE
dark歌謡祭-20時ダヨ！全員集合！-

### ISSUE THREAD

**Issue by noainoue** [ngineerxiv/dark#59]
# カラオケもくもく会
音楽好きが集まってカラオケオールをしましょう！(※開始時間は20時ではないです)

**Comment by noainoue** [comment]
参加者は調整さんに記入をお願いします〜！
https://chouseisan.com/s?h=ae18542fc9f4483683bf304b7fc1c284

**Comment by noainoue** [comment]
時間帯は日程決まり次第参加者で決めましょう！！

**Comment by noainoue** [comment]
こちら締め切ってもよいですか〜？？
他にカラオケ行く人はいませんか〜？？

**Comment by rnitame** [comment]
すべりこみで入れましたった

**Comment by urataku** [comment]
記入！！

**Comment by noainoue** [comment]
参加者締め切ります！！
日程は11月28日に決定しました！(時間によって井上が途中参加になります。takuさんも△)
参加メンバーは下記の通りです！

＝＝＝＝＝＝＝
ののあのあ 
jp_taku2 
める
いがにん
あっちゃん
hoto
とらい 
 Ω 
bird_tummy
ara_ta3
うら
＝＝＝＝＝＝＝

日程は11月28日です。こちら場所と時間が確定していません。
それぞれ希望時間や場所の指定いただけたらと存じます〜！

**Comment by rnitame** [comment]
時間は20時以降だと嬉しい気持ち。場所は渋谷とか新宿のほうがいいのかな？
（💰  はお高めになりそう）

**Comment by noainoue** [comment]
同じく20時以降希望です！！
(場所は東京民にまかせませう)

**Comment by jp-taku2** [comment]
ここら辺のダジュールならwifi完備で予約可能！
目黒、五反田、自由が丘、赤坂

**Comment by ara-ta3** [comment]
体力が尽きているので明日不参加でおなしゃすmm

**Comment by iga-yamaguchi** [comment]
再確認
参加メンバーは下記でいいです？

＝＝＝＝＝＝＝
ののあのあ
jp_taku2 (△)
める
いがにん
あっちゃん
hoto
とらい
Ω
うら
＝＝＝＝＝＝＝
以上9名

これでよければ本日中に予約しちゃいます

**Comment by urataku** [comment]
タスクが遅れているのと喉の調子が悪いのとでちょいと無理そう…  
直前ですまぬが不参加でお願いしますm(_ _)m

**Comment by iga-yamaguchi** [comment]
コート・ダジュール 目黒駅西口店 11/28(火) 20:00~24:00に山口で予約しておきました。

**Comment by acchanAlexander** [comment]
すんません、今日帰宅してから体調悪くなってきてるので
明日不参加にさせてください。
予約してもらったあとで申し訳ない。。。

**Comment by iga-yamaguchi** [comment]
今8人で予約してますがカラオケで部屋取っただけで先払いしているわけではないので人数変動可能です。
変わる人は直前に来るか来ないかだけおなしゃす

**Comment by noainoue** [comment]
みんなうまくてえらい！！
懐メロ携えてまたいきましょう！！
