### ISSUE TITLE
papi's kitchen vol.5

### ISSUE THREAD

**Issue by papix** [ngineerxiv/dark#6]
やりますか.

**Comment by urataku** [comment]
いつですか？

**Comment by gomayumax** [comment]
なにつくるです？

**Comment by papix** [comment]
> いつですか

ほとごま夫妻の都合次第ですね.

> なにつくるです

希望を書くよろし.

**Comment by papix** [comment]
個人的にはパエリアとか作ってみたい気持ちがある. 作れるかは不明.

**Comment by gomayumax** [comment]
https://chouseisan.com/s?h=38bb4598b9fc4b92a45b6f08917358ee

多分我が家大丈夫な日達↑

**Comment by papix** [comment]
突然ですが来週日曜日(7/24)はどうか. ピザをつくります.

**Comment by ara-ta3** [comment]
＿人人人人人人人人人人人人＿
＞　とうもろこし食べたい　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y￣

**Comment by papix** [comment]
だったらピザに乗せたらいいだろ!

@gomayumax いける日程挙げてくだされ〜. というか, オーブンレンジあるなら @ara-ta3 宅でも行ける? (行ったことないから規模感わからないけど)

**Comment by gomayumax** [comment]
7/23,24,31

直近でおｋ

**Comment by jp-taku2** [comment]
24空いてるっぽいから決定でいいの @papix

**Comment by papix** [comment]
ウオオオレス忘れてた, ってごまのレスポンス6時間前か.
@gomayumax が大丈夫なら24で. あとは人集まるかですねー.

**Comment by ara-ta3** [comment]
ピザは最高だった
とりあえず、終わったと思うので一旦closeしようかなと
