### ISSUE TITLE
音楽系映画鑑賞会

### ISSUE THREAD

**Issue by noainoue** [ngineerxiv/dark#60]
# 年代問わず音楽系の映画鑑賞しよう！

セッションやドラムラインなど、音楽系の名作映画を鑑賞しましょう！
ミュージカルなんかもあり。

**Comment by sota1235** [comment]
## 見たことあるよかったやつ

- ドラムライン
- Sing Street
- Begin Again(邦題: はじまりのうた)
- LA LA LAND
- Burlesque
- セッション

## 見てみたいやつ

- once ダブリンの街角で
  - Sing Street, Begin Againと同じ監督
  - でもいまいちという話も聞いたのでどうだろう

**Comment by noainoue** [comment]
# 見たことあるよかったやつ
## 音楽が題材の話
- シカゴ
- セッション
- ドラムライン
- スウィングガールズ
- のだめカンタービレ(私も最終章だけ見てない)

## ミュージカル
- ムーランルージュ
- バーレスク
- LA LA LAND
- The Sound of Music
- ロッキー・ホラー・ショー
- オズの魔法使い
- マンマ・ミーア！
- 雨に唄えば
- ドリームガールズ
- サタデーナイトフィーバー

# 見て見たいやつ
- ラブソングができるまで
- ダンサー・イン・ザ・ダーク(これずっと見たいと思ってた)
- Ray/レイ
- ブルース・ブラザーズ
- once ダブリンの街角で
- はじまりのうた（原題：Begin Again）

基本洋画(字幕)しかみません！

**Comment by Omega014** [comment]
# 見たことあるよかったやつ

## 音楽が題材の話

カルテット！人生のオペラハウス
天使にラブソングをシリーズ
のだめカンタービレ（あったね、ドラマも好き）
スウィーニー・トッド（音楽が題材というわけでもなさそうだけどよく歌ってる）
ファニー・ガール（最後の歌の演技すごい）
インドの映画（元気になる）

## ミュージカル
シカゴ
バーレスク（相手役の男に腹が立った）
プロデューサーズ（おバカ映画）
ヘアスプレー
マンマ・ミーア！
ムーランルージュ
キャバレー
ドリームガールズ
レ・ミゼラブル（アン・ハサウェイがひたすら美しい）
--- 小学生の時見たシリーズ---
サウンド・オブ・ミュージック（号泣）
オズの魔法使い（初期のカカシが不気味過ぎる）
ウエスト・サイド・ストーリー（悲しい）
アイーダ（圧巻）
オペラ座の怪人（号泣）

## 見て見たいやつ

ドラムライン
オール・ザット・ジャズ
オードリー・ヘップバーンが出てる映画（オードリーは歌が下手なので別人の声が当てられているという話は有名）
ロッキー・ホラー・ショー
ダンサー・イン・ザ・ダーク

**Comment by noainoue** [comment]
いつか叶えましょう(完)
