### ISSUE TITLE
台湾行きたい

### ISSUE THREAD

**Issue by papix** [ngineerxiv/dark#61]
- 安そうな時期に適当に行きたい
- JALならJGCで最高4人(含papix)までラウンジ無料で行けるぞ
- 2〜3日くらいブラブラしたいっすね

**Comment by mrtry** [comment]
いきたいわん

**Comment by ara-ta3** [comment]
いきたいわん

**Comment by mihyaeru21** [comment]
いきたいわん 🐕

**Comment by acchanAlexander** [comment]
いきたいわん

**Comment by papix** [comment]
宗教上の事情で日程は4/7〜4/8の土日を中心に, 4/6〜4/9くらいで行く感じになりそうです.

**Comment by rnitame** [comment]
いきたいわん！

**Comment by gomayumax** [comment]
来年行く予定がふわっと湧いているわん
合わせていけたら最高わん

**Comment by gomayumax** [comment]
2/3-2/4で台湾行くことになったわん

**Comment by acchanAlexander** [comment]
パスポート更新しなきゃ

**Comment by gomayumax** [comment]
行ってきたわん。
雨ばっかりらしいので
行くときは雨対策を必ずしてね＼＼\\٩( 'ω' )و //／／

またオススメとかブログにまとめるので見てね＼＼\\٩( 'ω' )و //／／
