### ISSUE TITLE
11/30(木)もつ鍋を食べにいこう

### ISSUE THREAD

**Issue by acchanAlexander** [ngineerxiv/dark#63]
acchanが行ったもつ鍋屋が美味しかったので、また行きたいので
行きましょうというお誘い。

酒菜家
https://r.gnavi.co.jp/p746600/

まりな氏とりほ氏とすずたくと行こうという話しをした。
ぜひぜひ他の人も行ける人がいたら行きましょう :blush:

![motsunabe](https://user-images.githubusercontent.com/7720640/32999041-1b39d784-cde3-11e7-9e66-51266d833917.jpeg)

**Comment by ara-ta3** [comment]
良さそうと思ったけど個人的には遠目だｗ

**Comment by jp-taku2** [comment]
いさおもいくよ！

**Comment by acchanAlexander** [comment]
明日です！

@riho 
@まりな氏
@jp_taku 
@isaoeka 
@acchan 

の5人でいいかなー？
他にも行きたい人いれば :stew:

**Comment by acchanAlexander** [comment]
予約done
20:00 ~ 5名
予約名：あたり

**Comment by acchanAlexander** [comment]
もつ鍋うまかった。
また行きませう。
