### ISSUE TITLE
国立科学博物館に遊びに行く

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#64]
たくとのあ氏と自分が行きそう

**Comment by ara-ta3** [comment]
時間とかはいい感じのプランを考える予定
日にち的に来れそうな人、時間がいつだったら来れそうな人とかはSlackかここのコメントで雑に行ってもらえると嬉しい

**Comment by ara-ta3** [comment]
ごま氏がこれそうな他の日程にするかとか話してる

**Comment by ara-ta3** [comment]
12/23ごま氏いけるんだっけ行けるならそっちに変えたい
ちょっと今週体調が最悪目なので12/3は少なくとも延期したい・・・

**Comment by isaoeka** [comment]
行きたさある

**Comment by acchanAlexander** [comment]
科学に触れたい
