### ISSUE TITLE
seccon練習会をやろう

### ISSUE THREAD

**Issue by acchanAlexander** [ngineerxiv/dark#65]
#### 理想
去年キリンさんが用意してくれたみたいな
seccon環境を整えてやってみる。

#### 代替案
ksnctfのようなctfサイトを順番に解いていく。
https://ksnctf.sweetduet.info/

その他代替案募集中

時間決めてやって、
終わったらみんなで答え合わせしたり教えあったり。

### 日程
練習会の日程決め
https://chouseisan.com/s?h=02176c6f24a045c39a2c722a67339a40

### 場所候補
- v社？（いつもお世話になってます）
- 去年はBe社でやりましたね
- 他に使えそうな場所があれば

### 備考
本番の予選は2017年12月9日（土）15:00～10日（日）15:00 (JST)

**Comment by ara-ta3** [comment]
いつもの緑の部屋取った

**Comment by ara-ta3** [comment]
(調整さんの雰囲気12/2になりそうだったから12/2で取ってる

**Comment by acchanAlexander** [comment]
2日の個人予定調整しました！
2日にやるぞい！

**Comment by ara-ta3** [comment]
これ何人来るんやろ

**Comment by ara-ta3** [comment]
もしかして、そんなにこない？

**Comment by acchanAlexander** [comment]
人数集まらなそうなので、各々で勉強ということでclose
