### ISSUE TITLE
ほとごま家の食材を消費する会

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#67]
引っ越しにあたり食材を消費していきたい

ご協力いただきたく候

**Comment by ara-ta3** [comment]
ブルーレイのアレがあれば https://github.com/ngineerxiv/dark/issues/66 も一緒にできそう

**Comment by gomayumax** [comment]
なんか、引っ越しが1月の第1,2週とかになりそうな気がするので  
候補日がすごい限られそうです  

ひとまず調整さん立てておこう

https://chouseisan.com/s?h=d747400134d74a2793ae7326e4486c64

ほとごま家、最後の会場です

食材をマジで減らしていきたいので  
ぜひご参加ください

ボードゲーム＆アニメ&switch各種取りそろえております

**Comment by gomayumax** [comment]
# 日程決定！！！！
**12/23(土) 15:00〜**

です！！！！

# 今回のルール
- ほとごま家のものを飲み食いする
    - 調理場どうぞお使いください
- 食べ物飲み物は絶対に置いていかない
    - みんなお持ち帰りください＞＜

# 思いつく限りの食材
- トマト缶: 大量
- 冷凍食品: 唐辛子,ネギ,きのこ,チャーハン
- 佃煮
- 乾パン
- トニックウォーター
- 調味料各種
- お好み焼き粉
- ナンの粉
- 鰹節
- さくらチップ(とらい氏にもらったやつ

よろしくお願いします

**Comment by mrtry** [comment]
トマト缶で、バターチキン作ったら乾パンとナンはぶっとばせそうとか妄想した

**Comment by gomayumax** [comment]
無事いろいろ消費できました！ありがとうございます！
