### ISSUE TITLE
星を見に行く

### ISSUE THREAD

**Issue by acchanAlexander** [ngineerxiv/dark#7]
ｱﾚｶﾞﾃﾞﾈﾌﾞｱﾙﾀｲﾙﾍﾞｶﾞ

**Comment by acchanAlexander** [comment]
まるでプラネタリウム！東京から行ける「満天の星空」スポット10選
https://retrip.jp/articles/5987/

奥多摩あたりで1,2hくらい観測する

時間的に、レンタカーして行こう

運転できそうな人
オメガ氏、あっちゃん、

人数多かったら2台で行くものあり

家が近い人同士で固まって拾うとか、帰るとかしたら良さそう。

7/30
もくもく会したあとに行く

**Comment by papix** [comment]
一応免許は持っているヨ(運転慣れているとは言っていない)

**Comment by ara-ta3** [comment]
Eventページ
http://connpass.com/event/34407/

**Comment by urataku** [comment]
免許だけは持っている(6年間運転はしていない)

助手席で手伝いくらいしか出来へんな

**Comment by TasukuNakano** [comment]
免許持ってるし車持ってたから割りと運転慣れてる(と思う)

**Comment by mihyaeru21** [comment]
車社会マンだったから普通の車を運転する分には全く問題ない。

**Comment by Omega014** [comment]
レンタカーはここが安いという情報 by jp_taku

https://honda-smartrental.com/


* 基本料金が安い
* ガソリン代はかからず、1km/15円で課金するシステム

これでいきましょう。
一応イベントは7/15に応募締め切りするので、締め切ったあと僕がまとめて車予約します。
現時点で10名なので、4~5人乗りを3台借りる予定。

予約の際には運転手の登録が必要なので、
↑で運転できると書いた人たちに運転手情報もらって予約するという流れです。よろしく。

**Comment by jp-taku2** [comment]
毎日運転してたから平気さー

**Comment by acchanAlexander** [comment]
ざっくり予定（暫定）
昼から、もくもく会している
19:00頃：もくもく会解散して、車取りに行く人は取りに行く。それ以外は飯とか行ってる。
22:00頃：V社に再集合、車はV社の前の坂のとこら辺に停車してられそう。
22:30頃：奥多摩へ出発
24:00頃：到着、天体観測開始
25:30頃：天体観測終わり、23区へ出発
27:00頃：それぞれ家の近くへ送り届けて、解散

**Comment by Omega014** [comment]
@acchan
@isaoeka は事情によりよみうりランド付近で合流なので、22:30頃にV社に来た人間を車に詰めた後、どちらか一台は isaoeka 拾うためによみうりランドへ向かうことになった。

そのほかのスケジュールはacchanが書いてくれた感じで良いと思われる。thx! 

集合場所と時間が決まったので、あとは天気の様子みつつレンタカーの予約をしましょう。

**Comment by Omega014** [comment]
ポテトさん？という方が予定入ってキャンセルするということで今のところ参加者は9人。
天気みているけど、今の所くもりだなぁー。

**Comment by acchanAlexander** [comment]
@Omega014 
5人乗り、ホンダのFitくらいのクラスのを12時間で予約しましたん！

クラスの内容
http://www.nipponrentacar.co.jp/service/syasyu/car_ss.htm

**Comment by acchanAlexander** [comment]
僕の家が一人遠くて、
帰りの時間的に電車がないので、僕の家の近くで車借ります。

奥多摩まで運転してやんよ！とか、日頃運転する機会ないからしたいよ！って人がいれば
本名を私に教えてください。（レンタルするときに書類に書くので）
slackか何かしらで教えていただければ！

**Comment by Omega014** [comment]
@acchanAlexander 
4人乗り（人数減ったので）、を同じく12時間で予約しました。

**Comment by Omega014** [comment]
@acchanAlexander 
8532(レンタカー代) + 1598(ガス代) = 10130円
@Omega014
7960(レンタカー代) + 1230(ガス代) = 9190円

一人あたり2150円。

あっちゃんの方が多めに払ってるので、そのあたりうまく計算しよう（ねむいので今はやめとく..w）。

**Comment by ara-ta3** [comment]
精算はこんな感じかな
あとは高速代が決まれば決まる
https://docs.google.com/spreadsheets/d/1zXrKoaYzrHQaTwDq4lhj9LgNaxfH6NLMXqwXRSlZjj4/edit?usp=sharing

**Comment by acchanAlexander** [comment]
高速代は430円であった。
[参考サイト]
http://www.driveplaza.com/dp/SearchTop
[キャプチャ]
![2016-07-31 15 30 42](https://cloud.githubusercontent.com/assets/7720640/17274990/dfbdb01c-5733-11e6-8c48-01c1d81d2550.png)

**Comment by Omega014** [comment]
メモ：isucon参加者からお金集めたので、あとはpapiとすてにゃんとYくんから集金するだけ

**Comment by ara-ta3** [comment]
![進捗どうですか](https://cloud.githubusercontent.com/assets/2089153/19315322/2f97ea0c-90d8-11e6-85a4-1a2f0bfcc4cb.jpg)

**Comment by acchanAlexander** [comment]
あと3人から集金が残っている ><
もくもく会とかで会ったときに、確実に集金してクローズさせよう。
集金者と納金者が偶然会うことを待ってると終わらなそうなので、よくいる人に預かってもらうようにしようかな。

@Omega014 という感じでいかがでしょう。

**Comment by stefafafan** [comment]
あっあっ今度おめが氏に会いそうなので渡します 🙇 🙇

**Comment by ara-ta3** [comment]
![image](https://cloud.githubusercontent.com/assets/2089153/20437929/15903c8e-adf9-11e6-859d-f33faaf41056.png)

**Comment by acchanAlexander** [comment]
@Omega014 
すてにゃんからってもらっている感じですかね？
papi さんは明後日の高尾山で会えそう。
Yくんは、何かのときにもらうからこの issue に含めなくてよさそうみたいなこと言ってた気がするけど記憶が曖昧...

**Comment by Omega014** [comment]
@acchanAlexander すてにゃんからまだ貰ってない！金曜日もらうぞい。
papi氏はそうですね、明後日にいただきましょう。
Yくんは僕のおごりでいいっす！
あっちゃんのほうが多くもらえる計算なので、高尾山のときにYくんのぶんを私から渡せばOKという感じだ。

**Comment by Omega014** [comment]
めも：すてにゃんからお金貰った

**Comment by acchanAlexander** [comment]
オメガ氏と話して、あとは思い出したときに受け取れたら受け取るくらいにして、
この issue は閉じていいんじゃないかという話ができたので、閉じます。
閉じるまで長くかかっちゃってすみませんでした。
