### ISSUE TITLE
昼から酒を飲む会

### ISSUE THREAD

**Issue by Omega014** [ngineerxiv/dark#70]
# 概要
Notz氏オススメの店 「新宿三丁目 KURAND」
昼から酒を飲むにはもってこいの店なので、今度行こうぜという話になった。

http://kurand.jp/sakemarket/shinjuku/

```
KURAND SAKE MARKET新宿店は、
日本酒100種類飲み比べし放題、時間無制限、持ち込み自由 (手作り料理持っていこうぜ)
が特長の日本酒専門店です。

※料金 時間無制限 3,000円(税別)
※ビールも飲み放題
※梅酒・果実酒もあります

平日17:00~23:00(22:45LO) 
土日12:00~16:00(15:30LO)
17:00~23:00(22:45LO)
定休日 年中無休
```

最高です。

# 日程
日にち: 2月3日
時間: 昼飯感覚で12:00から行きたい

# 参加者

- あっちゃん
- Notz氏
- omega

参加する人はcommentで表明してくれ。
予約のため、1月26(金)には参加締め切ります。

**Comment by Omega014** [comment]
そういえばこれ完全に忘れていたんだけど体調あんまりよくないのでリスケしたい

**Comment by acchanAlexander** [comment]
お大事に😥
リスケ構わないです！

**Comment by acchanAlexander** [comment]
こっちと一緒にやってよさそう
https://github.com/ngineerxiv/dark/issues/71

**Comment by acchanAlexander** [comment]
調整さんだーーーーーー
https://chouseisan.com/s?h=8529f730fbb84e5ba1c66ae981f7b077

**Comment by Omega014** [comment]
これ一旦closeします。気が向いたら飲みに行こう
