### ISSUE TITLE
きき寿司 in the Dark

### ISSUE THREAD

**Issue by noainoue** [ngineerxiv/dark#72]
# お前らぜってー許さねーかんな
## 寿司 or Die
サーモンとマグロ間違えたらスライディング土下座の刑
条件は私がやった時と同じく、サーモン・赤身・びんとろ・中トロの4種類
Ajitoあたりでやりたい。
調整さんカモン

**Comment by ara-ta3** [comment]
証拠スレッドです。
https://twitter.com/ara_ta3/status/942986407529680896

**Comment by iga-yamaguchi** [comment]
サーモンもマグロもわかんねーやつはずっとガリ食ってろ

**Comment by chocopie116** [comment]
FYI
こちらから頼めば全く同じ条件です。

http://asp.demae-can.com/shop/menu/1003648/?menuCd=70036000&firstMenuCd=70036000&author=kakiyasushi&orderTyp=1&blockCd=13113015000&addressId=1#menu

**Comment by urataku** [comment]
😊つ わさび

**Comment by noainoue** [comment]
つばささんありがとうございます❤️圧倒的感謝❤️

**Comment by chocopie116** [comment]
ちなみに、のあ氏・あらた氏はサビ抜き環境でした
気持ちのこもったスライディング土下座をするためには、条件揃えるのがオススメです。

**Comment by ara-ta3** [comment]
調整さん
https://chouseisan.com/s?h=853e549a812c43d789e5e97066bf84ee

**Comment by iga-yamaguchi** [comment]
調整さんの保留にしていた予定更新しておいた

**Comment by rnitame** [comment]
14 日で良さそう

**Comment by ara-ta3** [comment]
1/14でいきませう

**Comment by rnitame** [comment]
サーモンとマグロの違いわからんやつおる！？？！？って堂々と煽りたかったけど、予定が入ったので不参加で (´・ω・｀)

**Comment by ara-ta3** [comment]
次の日曜じゃん
何時からにしよう

**Comment by noainoue** [comment]
18:00以降希望

**Comment by iga-yamaguchi** [comment]
いつでも行けます

**Comment by urataku** [comment]
朝16時以降ならOK

**Comment by ara-ta3** [comment]
19時開始にしてちょっと早めに行ってようかな
16時にはいる感じにしよう

寿司注文がめんどくさいなという気持ちから誰か注文してくれないかなぁと思ったりしている

**Comment by noainoue** [comment]
詳細くれればやっとくぞい

**Comment by ara-ta3** [comment]
最低↓の4種類をそれぞれ人数分注文する必要がある
あとは普通の食事用に http://asp.demae-can.com/shop/menu/1003648/?menuCd=70031300&firstMenuCd=70031300&author=kakiyasushi&orderTyp=1&blockCd=13113015000&addressId=1#menu の寿司があると良さげという感じ

- http://asp.demae-can.com/shop/item/1003648/700300048210/70030004821/?menuCd=70036000&backMenuCd=70036000&firstMenuCd=70036000&author=kakiyasushi&orderTyp=1&blockCd=13113015000&addressId=1
- http://asp.demae-can.com/shop/item/1003648/700300048220/70030004822/?menuCd=70036000&backMenuCd=70036000&firstMenuCd=70036000&author=kakiyasushi&orderTyp=1&blockCd=13113015000&addressId=1
- http://asp.demae-can.com/shop/item/1003648/700300048240/70030004824/?menuCd=70036000&backMenuCd=70036000&firstMenuCd=70036000&author=kakiyasushi&orderTyp=1&blockCd=13113015000&addressId=1
- http://asp.demae-can.com/shop/item/1003648/700300048330/70030004833/?menuCd=70036000&backMenuCd=70036000&firstMenuCd=70036000&author=kakiyasushi&orderTyp=1&blockCd=13113015000&addressId=1

**Comment by ara-ta3** [comment]
@noainoue お願いしていい？

**Comment by acchanAlexander** [comment]
遅れましたが何時でも大丈夫です

**Comment by noainoue** [comment]
注文やっとく！

**Comment by noainoue** [comment]
結局みんなマグロもサーモンもわからん。
みんなちがって、みんなクソ。
