### ISSUE TITLE
YAPC::Okinawaに行こう 🛫

### ISSUE THREAD

**Issue by isaoeka** [ngineerxiv/dark#73]
[YAPC::Okinawa](http://yapcjapan.org/2018okinawa/) に行くぞい！

行く人の滞在期間などを聞き(共有)つつ、予定立てましょう！

**Comment by isaoeka** [comment]
ちなワイ  `3/2 ~ 3/5` が有力で下記のようなイメージ
```
2: 沖縄着 前夜祭(あれば)  
3: 当日
4: 観光 
5: 観光 東京着
```

**Comment by takumi-suzuki** [comment]
わい、3/2〜3/5or3/6
3/2〜3/6なら、3/2はどこかで仕事してたい

**Comment by Omega014** [comment]
```
2: 沖縄着(OKA 13:15着), 観光, 前夜祭
3: YAPC
4: 観光, 東京戻り(OKA 19:10離)
```

**Comment by isaoeka** [comment]
割と翌日帰るのアリな気がしてきた

**Comment by mihyaeru21** [comment]
```
2: 到着、前夜祭
3: 当日
4: 観光
5: 観光
6: 観光、蛙
```

@takumi-suzuki とだいたい同じ行動する

**Comment by mihyaeru21** [comment]
ミニバン予約しました

**Comment by mihyaeru21** [comment]
2-6で借りてあるので、一緒に観光 🉑 な人は一緒に観光しましょ〜〜 with @takumi-suzuki

**Comment by isaoeka** [comment]
飛行機取った

**Comment by rnitame** [comment]
3/2〜5 で飛行機取った

**Comment by ara-ta3** [comment]
行き（3/2）：14:55 -> 17:45
帰り（3/5）：13:35 -> 15:50
で飛行機取った

**Comment by ara-ta3** [comment]
memo
ホテルは県庁前という駅付近に取ると良いらしい
https://goo.gl/maps/zzpgr6by64v

https://ngineerxiv.slack.com/archives/C82QPLLRE/p1518475106000271

```
tummy [07:38]
あ、取らなきゃホテル

ara_ta3 [15:56]
そういえば取らねば

tummy [19:55]
県庁前って駅の近くでホテル取るといいっぽい？

goma [20:10]
会場行きのバス乗るならその方がいい
県庁近くならもっと良さそう (edited)

ichigotake [20:10]
バス乗るから駅から徒歩圏の場所にした
```

**Comment by ara-ta3** [comment]
ちゅらデータは県庁前付近から車で約30分ほどかかるらしい
https://goo.gl/maps/zqqMF17uJbp

すずたくたちの車に乗れないとしたらリムジンバスで行けるっぽい雰囲気がある
https://goo.gl/maps/9iUJjhDH6ny

**Comment by ara-ta3** [comment]
YAPCのバスは県庁前から朝8時に乗る
チケットは3/2の23:59までなのでギリギリまで大丈夫そう
https://passmarket.yahoo.co.jp/event/show/detail/017xe4z7g99k.html

**Comment by jp-taku2** [comment]
車は8人乗りを予約してある
https://cars.travel.rakuten.co.jp/cars/rcf140a.do?jcid=3431&v=1
乗る人
6人:ミヒャ、おめが、いさお、あらたし、いちごたけし、わい

2日の合流は時間ずれてる人は頑張って👍
3日は県庁前が最寄りのホテルから出発するから頑張って

**Comment by Omega014** [comment]
# 3/2(金)
- ちゅらデータ
- 前夜祭

# 3/3(土)
- YAPC
- 夜飯どこか

# 3/4(日)
- 美ら海水族館
- 古宇利大橋
- 昼飯どこか

# 3/5(月)

**Comment by gomayumax** [comment]
わいわい！みんな来てくれて楽しかった！！！
また遊びに来てくれ！！！待ってる！！！
あと寂しいからインターネットで会っていきましょう！！！

**Comment by Omega014** [comment]
@mihyaeru21 車・ガソリン・高速代金教えてクレメンス

**Comment by ara-ta3** [comment]
kyashで支払ったりしたのでclose(残精算はおのおの・・・
