### ISSUE TITLE
darkだよ！全員集合忘年会！

### ISSUE THREAD

**Issue by acchanAlexander** [ngineerxiv/dark#74]
### 今年の闇は、今年のうちに♪

気まぐれ飲み会です。

日程：12/26（火）

**Comment by acchanAlexander** [comment]
参加できる方はコメントなどいただけると

**Comment by mrtry** [comment]
うぇい

**Comment by noainoue** [comment]
別の予定が入ってるけど早めに切り上げられたら途中参加します！(もしくはちょっと顔出す)

**Comment by acchanAlexander** [comment]
年末なので、早めに予約しなきゃだ

**Comment by acchanAlexander** [comment]
isao氏とnotz氏も参加かな（emojiでリアクションくれているので）

**Comment by acchanAlexander** [comment]
urataku氏とmeru氏もかな

**Comment by c5meg1012** [comment]
うぇい:beer:

**Comment by acchanAlexander** [comment]
年末でお店も混んできて、予約を早めにしたいので、
今日中までで参加できる方はコメントもらえると><

**Comment by acchanAlexander** [comment]
予約doneです〜！(๑˃̵ᴗ˂̵)و
比内地鶏専門店 鈴音 五反田本店
https://tabelog.com/tokyo/A1316/A131603/13157637/

時間:20時~
予約名:あたり
内容:席のみ
人数:7名
@acchan
@mrtry 
@sasakure 
@isaoeka 
@Notz 
@urataku 
@meru

当日は年忘れ盛り上がりましょうー！！₍₍ (ง ˙ω˙)ว ⁾⁾

**Comment by c5meg1012** [comment]
ありがたや！

**Comment by mrtry** [comment]
ありがたや！！！！！！！！！！！

**Comment by isaoeka** [comment]
ごめん、到着21:30頃になりそうなんだけど、大丈夫かな？

**Comment by acchanAlexander** [comment]
それくらいだとまだやっているので、大丈夫だと思われ

**Comment by acchanAlexander** [comment]
場所です
東京都 品川区 西五反田 1-11-8 6F-B
https://tabelog.com/tokyo/A1316/A131603/13157637/dtlmap/

**Comment by acchanAlexander** [comment]
いい感じで年忘れできたのでよかった。
