### ISSUE TITLE
暴露会

### ISSUE THREAD

**Issue by iga-yamaguchi** [ngineerxiv/dark#75]
やあ

ここに来たということは君も闇を抱えているんだね？
こんなご時世だ
珍しくもない
君も闇を吐き出して前を向こう
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

# 暴露会だーーーーーーーーーーーーーー！！！！！！！！！！！！！

ということで暴露会です。
SNSへの発信禁止です
流れはblogチャンネルとかjobチャンネルで察してください。

レンタルスペースとかでやれたらなって思ってます。

**Comment by rnitame** [comment]
人数そんなにいなかったら #remote-talking とかでも良い気はしている

**Comment by iga-yamaguchi** [comment]
これいつやろっか
たみーさん、のあさん、俺がそろってる日でどこかテキトーにやっていきたい

**Comment by iga-yamaguchi** [comment]
特別会を設けず適当にやっていくっす！
