### ISSUE TITLE
今年も花見やりたい 

### ISSUE THREAD

**Issue by Omega014** [ngineerxiv/dark#77]
代々木公園で酒飲みたい

**Comment by ara-ta3** [comment]
https://github.com/ngineerxiv/dark/issues/33

**Comment by rnitame** [comment]
酒飲みたいし写真撮りたい

**Comment by urataku** [comment]
前職やめたときにもらった獺祭、まだ開けてないから消費したい

**Comment by mrtry** [comment]
ブルーシートおうちにあること気づいたので、ブルーシートマンなれます

**Comment by mrtry** [comment]
とりあえずたてた
https://chouseisan.com/s?h=867ba7e728324d61b2f0068b0ac4eda7

**Comment by acchanAlexander** [comment]
僕の家の近くが割と良い花見スポット（普通の公園）だと5年目にして気づいたので
来年はオススメしたい
# メリット
- 徒歩3分のところに、22:00までやってるスーパー・100均・マック・ケンタ・ポッポ・ベーカリーの入ったイトヨーがある
- ウェイがいなかった
- 公園にくる人もそんなに多くないので、余裕で桜の下に座れる
- ジャグリングできる広さもある
- 駅徒歩5分
# デメリット
- 都内から遠い（と言っても渋谷から40分、品川から30分で来れるよ！）
- 出店とかはない
- なんでも捨てれそうなゴミ箱はない

![180401_0001](https://user-images.githubusercontent.com/7720640/38171430-a61d22a8-35d4-11e8-82ab-440db0abb5f5.jpg)

**Comment by Omega014** [comment]
花は散りました、また来年
