### ISSUE TITLE
家庭料理のとらい#2

### ISSUE THREAD

**Issue by mrtry** [ngineerxiv/dark#78]
GWにとらい家で飲む???
参加者いたらコメントよろしくどうぞ

**Comment by cocodrips** [comment]
GW暇

**Comment by ichigotake** [comment]
＼( 'ω')／

**Comment by ytgch** [comment]
基本暇

**Comment by cm-TanakaKenji** [comment]
たぶん暇

**Comment by iga-yamaguchi** [comment]
暇かもしれない

**Comment by mrtry** [comment]
割と集まって草
調整さん建てるかあ

**Comment by mrtry** [comment]
各位、入力よろっすーーーー
https://chouseisan.com/s?h=d2eab47f431841e8989d57185d3b7c66

**Comment by mrtry** [comment]
飲食したいモノのリクエストも募集中

**Comment by cm-TanakaKenji** [comment]
- 日本酒
- IPA
- コーン茶
- カレー

**Comment by ichigotake** [comment]
- みょうがの塩漬け

**Comment by noainoue** [comment]
入力DONE

下記、飲食したいものリストアップ
---

- [ ] 日本酒
- [ ] ウイスキー
- [ ] エイヒレ
- [ ] 肉じゃが
- [ ] なんかしらの燻製
- [ ] ねるねるねるね

**Comment by mrtry** [comment]
当日ワイが作ったりしそうなのはこんな感じかなあ
- スープカレー
- 肉じゃが
- 燻製(以下のどれかはできる)
  - ベーコン
  - スモークチキン
  - スモークチーズ

酒やらエイヒレやらねるねるねるねは、買いに行こう😇

**Comment by cm-TanakaKenji** [comment]
@mrtry 
ソーセージとかそのあたり持ってけるけど持ってきますか？

**Comment by mrtry** [comment]
神

**Comment by mrtry** [comment]
(メモ)チキチキボーン布教するために、チキチキボーンを買いたい

**Comment by noainoue** [comment]
ねるねるねるねを拾ってくれる優しさよ

**Comment by noainoue** [comment]
5日でだいじょぶいぶい！！！

**Comment by mrtry** [comment]
じゃ、5/5(土)の15時ぐらいにうち集合にしますかあ
燻製はベーコン面倒なのでスモークチキンにします！！！

**Comment by cm-TanakaKenji** [comment]
FOOOOOOやったーーー

**Comment by mrtry** [comment]
そいや、調整さんにくーむ氏が入ってない

**Comment by noainoue** [comment]
すまん、予定ブッキングしてしまった・・・5日いけぬわ
先約があるのでそっち優先します・・・ごめんごめんご

**Comment by mrtry** [comment]
現在7人ぽい

## 参加者
- だんぼーる 
- いちごだけ
- とらい
- いがにん
- める
- たぐち
- くーむ

## 作る/食べたい/持参されるリスト
- スモークチキン
- スープカレー
- チキチキボーン
- ソーセージとか
- みょうがの塩漬け

**Comment by mrtry** [comment]
ええんやで。ふぁいとやで😂

**Comment by ktanaka117** [comment]
### アナログゲームお品書き
- Dixit
- ゾン噛まパーティ
- ヒットマンが
- ごきぶりポーカー
- FABFIB
- 髑髏と薔薇
- ダンジョンオブマンダム(powered by たぐぴっぴ)
- ダンジョンオブマンダム8

**Comment by mrtry** [comment]
家の酒メモ

- 日本酒
  - なんかすごいやつ
  - 富士山近くで買った生搾りなやつ
- ラム(キャプテンモルガン)
- 赤ワイン
- 炭酸水が8本ぐらい

**Comment by mrtry** [comment]
作ったり食べたもの
- キーマカレー
- 土鍋で炊いたご飯
- ダンボー氏が持参したソーセージ
- ナムル的なサラダ
- スモークチキン
- チーズ
- ビール3種
- たけさん持参の日本酒
- わかめせんべい
- ポトフ

写真はダンボー氏がとったやーつ
![image_uploaded_from_ios](https://user-images.githubusercontent.com/8851552/39669240-18261dfc-5121-11e8-8870-d21e67736e5f.jpg)

**Comment by mrtry** [comment]
ボドゲもやって、たのしかった！！！！！！！！
またやろう！！！！！！！！！！！！！
