### ISSUE TITLE
技術書典にいきたい@2018

### ISSUE THREAD

**Issue by mrtry** [ngineerxiv/dark#79]
今年もいきたい
朝からいく気持ちではいる

**Comment by mrtry** [comment]
10:30ぐらいに秋葉原駅あたりに集まって、気が乗ったらそのへんの喫茶店で読書会する感じがいつもの流れ

**Comment by rnitame** [comment]
https://techbookfest.org/event/tbf04/circle/14710011
これのおつかい！お願いしやす！！

**Comment by ytgch** [comment]
Nuxt Techbookは自分も欲しかったのでいってきます！！
他のやつも可能な限り回収してくる〜

**Comment by c5meg1012** [comment]
🙇🙇🙇

**Comment by gomayumax** [comment]
DNS本をお使いお願いします！！
https://techbookfest.org/event/tbf04/circle/15420009

**Comment by mrtry** [comment]
たみちゃんパイセンとごま氏のは、私買ってこようかねえ

**Comment by acchanAlexander** [comment]
あ、僕もよければ行きたいですー！

**Comment by natsumican63** [comment]
行きたいですー！！(朝げきよわなので頑張ります)

**Comment by rnitame** [comment]
https://twitter.com/nayucolony/status/986585796965613568
とらいし、これも追加で… 🙏

**Comment by mrtry** [comment]
明日一緒にいく人ら(Issueに書いてた人)
10時30分に秋葉原駅電気街口に集合の予定

- とらい
- あっちゃん氏
- たぐち氏
- なつみかん氏

おつかい
- たみー氏(たぐち氏が購入予定)
  - https://techbookfest.org/event/tbf04/circle/14710011
  - https://twitter.com/nayucolony/status/986585796965613568

- ごま氏(とらいが購入予定)
  - https://techbookfest.org/event/tbf04/circle/15420009

- める氏(とらいが購入予定)
  - https://techbookfest.org/event/tbf04/circle/18260009
  -https://techbookfest.org/event/tbf04/circle/17570001
  - https://techbookfest.org/event/tbf04/circle/17580004

**Comment by mrtry** [comment]
(メモ)のあ氏になゆ氏の本頼まれてて、ワイ買う
