### ISSUE TITLE
チャット飲み会やりたい

### ISSUE THREAD

**Issue by acchanAlexander** [ngineerxiv/dark#8]
これやりたい。
【飲み会はもうチャットでよくないですか - デイリーポータルZ】
http://portal.nifty.com/kiji/160126195572_1.htm

もくもく会の後とかがいいかと思っている。
人数多かったら店じゃなくて、もくもく会の会場とか使わせてもらえたらと思っている。
弊社でも可。

もしチャット飲みが上手くいなかったら
そのまま普通の飲み会にシフトすればいいので汎用性もある。

**Comment by ara-ta3** [comment]
なんだかんだやってないなｗ
これも調整さんかな

**Comment by acchanAlexander** [comment]
oh... 進めます。ごめんなさい。

**Comment by acchanAlexander** [comment]
間延びしてしまって、まだ目処がたってないのでクローズ
もくもく会で、この日できそうみたいなときがあればレコメンドするようにする
