### ISSUE TITLE
DARK BBQ 2018

### ISSUE THREAD

**Issue by Omega014** [ngineerxiv/dark#80]
# 概要
多摩川でバーベキューをします

# 日時候補
- ~6/9(土) 11:00 ~ 15:00~ -> DARKのLT会をやるらしいので却下
- 6/23(土) 11:30 ~ 14:00くらい

# 参加費
未定, バーベキューセット+飲食費で毎年だいたい4000円くらいだった気がする.

# 参加方法
参加する人は参加しますとコメントしてね. 
~日時どっちが良いか選んでね.~

有人回遊システムが巡回しに来て参加者をカウントします.

# 参加者 (15名)
- omega
- すずたく
- tummy氏
- urataku氏
- いさお
- あらたし
- すてにゃん
- やみつきー氏
- たぐぴっぴ
- みっひゃ
- とらい氏
- ichigotake氏
- momo氏
- iganin氏
- natsumican氏

**Comment by Omega014** [comment]
参加します.
日程どっちでも良いです.

**Comment by takumi-suzuki** [comment]
参加
多分、どっちでも

**Comment by c5meg1012** [comment]
参加します！
日程もどっちでも可ですー

**Comment by rnitame** [comment]
うぇーい参加！
23 がよい〜

**Comment by urataku** [comment]
参加
両方行けると思うが9のほうが良い

**Comment by isaoeka** [comment]
参加！
23いけそう

**Comment by ara-ta3** [comment]
参加！9にLT会をやろうと思ってるので23日が助かる！

**Comment by ara-ta3** [comment]
2017年の奴
https://github.com/ngineerxiv/dark/issues/41

2016年の奴
https://github.com/ngineerxiv/dark/issues/4

**Comment by stefafafan** [comment]
参加〜

**Comment by rnitame** [comment]
おお、新丸子のあたりでやったのか。最寄り駅やw
我が家から日本酒とか提供できまっせ

**Comment by ytgch** [comment]
参加したい(家の契約終了の二日前だ)

**Comment by mihyaeru21** [comment]
23参加 :eyes:

**Comment by Omega014** [comment]
そろそろ予約しようと思う
今のところ参加表明している人は12名
もし他に行きたい人いたら今週いっぱいまで「参加します」ってcommentしてくだしあ

**Comment by ichigotake** [comment]
参加します

**Comment by c5meg1012** [comment]
別件に行かなくてはならなくなってしまったので、今回は不参加でお願いします＞＜
いきたかったー！

**Comment by mom0tomo** [comment]
参加したいです！

**Comment by iga-yamaguchi** [comment]
参加したいです！

**Comment by natsumican63** [comment]
参加したいですー！

**Comment by Omega014** [comment]
下記の内容で予約しました. 

```
■ ご予約内容
──────────────────────────────────
配送方法：通常
配達日指定： 2018-06-23  

  ・Aプラン｜タープテント付本格プラン  2,100円 x15
──────────────────────────────────
注文合計： 31,500円

支払方法： 商品代金引換（現金決済のみ）
お届け場所（BBQ会場・公園・その他）：丸子橋BBQ広場(新丸子駅)
ご希望のお届け時間：11:30
```


キャンセルについて
```
＜キャンセル・返品について＞
■ ご予約キャンセル受付に関して
【BBQレンタル機材のみお申込みの場合】　ご利用日の前日お昼12時で受付終了となります。
【BBQ用食材の同時お申込みの場合】　ご利用日の3日前お昼12時で受付終了となります。
※ご利用予定日2日前以降のキャンセルに関しては、トラブル防止のためお電話でのみ受付となります。

■ キャンセル料に関して
【BBQレンタル機材】　ご注文合計金額の50％のキャンセル料が発生いたします。
【BBQ用食材】　ご注文合計金額の100％のキャンセル料が発生いたします。
※キャンセル料は当日現地でのお支払いか、請求書送付のうえ銀行振り込みにてお支払い頂くようになります。 
※BBQ用食材に関しては現地よりお持ち帰り頂けます。

※降雨などの悪天候による当日キャンセルの場合にも、キャンセル料を頂戴しております。 ご利用に際して、お客様にはご不便を強いてしまいますが、何卒ご理解のうえご活用下さいます様、よろしくお願い申し上げます。

```

**Comment by Omega014** [comment]
今のところ降水確率40~60%くらい.
キャンセル料も50%くらいかかるし土砂降りではなさそうなので, ひとまず開催の方向で行きまっす！ 

# 当日の流れとか
- 11時ちょっと過ぎに新丸子駅の改札出たところに集合.
- 駅に東急ストアが併設されているので, 適当に買い出しする人を決めて食材を人数分買い込む. Slackでコミュニケーションしていい感じに準備しよう.
- テント・椅子・BBQセットは業者が用意してくれるので組み立ては不要. 15人分のお皿と箸, ゴミ袋も付けてくれるけど絶対に足りなくなるのでスーパーで買ったほうが良い.
- 会場に到着したあとはひたすら肉とビールをしましょう. 


# その他注意点
- セットを予約してしまっているので, 参加してもしなくても固定費は一人あたり最低2100円はかかります.
- 当日は雨が降ることが予想されるので, レインブーツや濡れても良いような服装で来ることをおすすめします.

**Comment by Omega014** [comment]
お会計

BBQセット台 一人2100円
支払先: omega
支払い方法: Kyash or 現金  KyashIDはomega014です.

食材・飲み物代を支払った人, 一人あたりの支払金額を書いてくれ〜！

**Comment by mrtry** [comment]
食料代、1649円です！
ここから支払ってください！
https://kyash.me/payments/fl1yFlq9CBIWyzf4GhVxCCgiGAas

**Comment by rnitame** [comment]
すずたく家でピザを食べた人 → きりん先生に 550 円
〃 でマック食べた人 → だんぼーしに 400 円

**Comment by Omega014** [comment]
atara氏とichigotake氏 BBQ代金2100円を私に支払ってねー ：）

**Comment by iga-yamaguchi** [comment]
ちょっとバタバタしていて僕も払えてません！
申し訳ないのですがもう少しお待ちください 🙏

**Comment by ara-ta3** [comment]
> atara氏とichigotake氏 BBQ代金2100円を私に支払ってねー ：）

:done:
