### ISSUE TITLE
和酒フェス＠中目黒に行きたい

### ISSUE THREAD

**Issue by rnitame** [ngineerxiv/dark#81]
https://www.fashion-press.net/news/31232
http://sakefes.com/event10/

もうチケット買える

**Comment by ara-ta3** [comment]
行きたいンゴ

**Comment by rnitame** [comment]
2部がいいなー

**Comment by Omega014** [comment]
他の予定と被ってて行けないことが判明してしまったので辞退

**Comment by mrtry** [comment]
引っ越しタイミングに被ってしまった 😇

**Comment by rnitame** [comment]
@ara-ta3 行く？

**Comment by rnitame** [comment]
終わってたw （忘れてた）
