### ISSUE TITLE
ペアプロTDDを楽しむ会

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#82]
https://ngineerxiv.slack.com/archives/C034QSSPA/p1526624556000091
Slack流れてしまうのでメモがてらこっちにも

調整さんはこのあたりから
https://ngineerxiv.slack.com/archives/C034QSSPA/p1526624933000158

> まず反応してくれた人の調整さん取って、他の人にも声かけていくスタイルでやろうと思います。
> https://chouseisan.com/s?h=a15f61642cfb43d2bbb1fd3f4ad76651

**Comment by ktanaka117** [comment]
なるべくペアプロだった方が楽しいと思っているので、使いたい言語をここに表明してほしす

**Comment by ktanaka117** [comment]
僕は 
- Swift
- ペアがなければJavaScriptも可

**Comment by ytgch** [comment]
- Ruby
- JavaScript(TypeScript)

です

**Comment by urataku** [comment]
- php:innocent:

です:innocent:

**Comment by nasa9084** [comment]
* Go
です

**Comment by iga-yamaguchi** [comment]
- C#
- PHP
- JavaScript（TypeScriptはなんとなくいけるかも）

**Comment by mrtry** [comment]
- PHP
- JS(TS)
- Java
- Kotlin

**Comment by butaosuinu** [comment]
- Go
- JavaScript

闇のTDDフロントエンドとかいうの知見ある人とやってみたさはある（）

**Comment by iga-yamaguchi** [comment]
日程5/28かな？

**Comment by ktanaka117** [comment]
28日で！

**Comment by ktanaka117** [comment]
はいじゃあみんな同じ言語でペアつくってー(地獄の号令)

僕はSwift書きたいのでペアを連れてこようと思います。

**Comment by ktanaka117** [comment]
あ、ちなみにペアの方が楽しいと思っているけど、一人でも良いと思ってます。

**Comment by rnitame** [comment]
Swift マンやりまっせ

**Comment by callmegema** [comment]
普段ロム専してますがペアプロTDDしたことないので参加してみたいですー
- Ruby
- C#
- (JS)

**Comment by ara-ta3** [comment]
余ってる人に合わせようかなという気持ちでいます
すっと環境含めて作れそうな言語はこのあたり

- PHP
- JavaScript
- TypeScript
- Scala
- Go
- Python3

**Comment by Udomomo** [comment]
やったことないので参加したいです

- Python3
- Java
- JS(TS)

**Comment by iga-yamaguchi** [comment]
## 参加者 12人
@ara-ta3 @ktanaka117 @ytgch @urataku @nasa9084 @mrtry  @butaosuinu @dtzx @rnitame @callmegema @Udomomo @iga-yamaguchi

## ペアマッチング済み ❤️ 
- @ktanaka117 @rnitame (Swift)
- @ytgch @iga-yamaguchi (TypeScript)
- @urataku @mrtry (PHP)

## 未マッチング
- @ara-ta3 (PHP, JavaScript, TypeScript, Scala, Go, Python3)
- @nasa9084 (Go)
- @butaosuinu (Go, JavaScript)
- @dtzx (JS(TS))
- @callmegema (Ruby, C#, (JS))
- @Udomomo (Python3, Java, JS(TS))

**Comment by iga-yamaguchi** [comment]
@ktanaka117 から
> 19時スタートかなと思ってます。
集まり具合を見て、少しずらすかも。
最初TDDの説明するかも。

場所はパンゲア@Voyage Group 8F

**Comment by mrtry** [comment]
PHP挫折したので、ぼっちします！！！！！！！！！！！

**Comment by ktanaka117** [comment]
## ざっくりタイムスケジュール(目安)

| 時間    | やること                                               |
|---------|--------------------------------------------------------|
| 19:00 - | 開場                                                   |
| 19:15 - | 『50分でわかるテスト駆動開発』を流し見しながらわいわい |
| 19:50 - | TDDの説明 from ダンボー田中 |
| 20:00 - | FizzBuzzゲーム作っていく                               |
| 20:30 - | 中間発表、引き続き開発                                 |
| 21:20 - | 最終発表                                               |
| 21:30   | 撤収                                                   |

## 会の趣旨
- TDDやってみよう
- ペアプロやってみよう
- みんなでプログラムを書いてわいわいしよう
- 実装の速さは求めない

## 50分でわかるテスト駆動開発
神動画
https://channel9.msdn.com/Events/de-code/2017/DO03

## FizzBuzzゲーム
### 題材
https://medium.com/@ynzc/getting-started-with-tdd-in-swift-2fab3e07204b

### FizzBuzzとは
1から100の数字の範囲で、

- 3の倍数をFizz
- 5の倍数をBuzz
- 3と5の公倍数をFizzBuzz

と判定するプログラムのこと。
FizzでもBuzzでもFizzBuzzでもない数字はそのままの数字として扱い、関数の戻り値とする。
みたいな。

https://ja.wikipedia.org/wiki/Fizz_Buzz

### おおまかな手順
1. Fizzを判定する
2. Buzzを判定する
3. FizzBuzzを判定する
4. FizzBuzzを判定し、結果を返却する
5. 各自UI実装する

実装の速さにはこだわらない。
TDDの文化とペアプロを理解することが大事。
UI実装は各言語・プラットフォームごとに異なるので、エクストラステージ扱いする。

## 中間発表
TDDを広めるTDDBCというイベントにちなんで、中間発表を取り入れてみようと思う。
中間発表は以下の手順で進める。

- 適当なチームに前に出て、プロジェクターにコードを写してもらう
- テストを実行して、通ることを確認する
- なんの言語を使ったか言う
- こだわりポイントや、悩んだ箇所を発表してもらう
- 前に出ていないチームの人間から挙手制で、発表やソースコードに対してコメントする
- 言語ごとの文化の違いや、他のチーム・人が書くコードを楽しもう！！！

**Comment by ktanaka117** [comment]
## 動画のメモ
- ロン・ジェフリー
	- 「動作する綺麗なコード」
	- 動作するコード
		- とりあえず動くと思うからリリースしようぜ！
	- 綺麗なコード
		- 考え抜かれた設計を元にしたコード

- 動作するコードに手を入れる恐怖
	- すでに要件を満たすコードを書き換える恐怖
	- デグレへの恐怖

- レッド・グリーン・リファクタリング
	- レッド: 期待する結果をテストとして書き、失敗を確認する
	- グリーン: テストを通ることを最優先に考える、汚いコードでも良い
	- リファクタリング: 成功したテストをそのままに、より綺麗なコードを手に入れる。テストが通っているので、デグレの恐怖を乗り越えられる

- TDDを支えるテクニック
	- TODOリスト
		- やるべきことを記述する
		- TODOリストを用意することで、気になるものを傍によけておける
		- 目の前の実装に集中できる！

- ソフトウェア開発に伴う恐怖
	- 動作するコードを壊してしまう
	- 動作するコードを書けない
	- 綺麗なコードが書けない
	- リファクタリングはあとでやる->忘れる
		- 「リファクタリング」のチケットは切るな

- 受入テスト(Acceptance Test)のサイクル
	- TDDのサイクル(レッド・グリーン・リファクタリング)の外には、受入テストのサイクルがある

- はじまりのレッド
	- 最初にテストを実行されるかどうかを確認する理由
		- テストが動作することを確認できていなければ、TDDを始められないから
		- もしテストが動作しなければ、「テスト環境の構築が完了していない」ということがはじめにわかる
		- まずはテストが動作する状況を作りましょう

- 前準備、実行、検証、後片付け
	- Given, When, Then
	- Arrange, Act, Assert
	- (before, after, setUp, tearDown)

- テストを書く順序
	- ゴール(Assertion)から書き始める
	- ゴールに必要なものを作る

- それXcodeの前でも同じこと言えんの
	- リッチなIDEが欲しい

- TDDを支えるテクニック
	- 仮実装
		- 期待する結果をそのまま返す実装をするテクニック
		- !!!まずテストが通る状況を作る!!!
	- 三角測量
		- 仮実装をして、ベタ書きの結果を返すようにしていると、テストにならない
		- ので、複数のテストケースを書いて、一般化を促したりする

- 一つのテストメソッドに複数のアサーションがあるテスト
	- どこでテストが失敗したかわからん！！！
		- アンチパターン
		- Assertion Roulette Pattern
	- ただし許される場合がある
		- Soft Assert/Hard Assert
		- 複数のアサーションがあっても、どこでコケたか教えてくれるテストフレームワークの場合、やってもよい

- TDDを支えるテクニック
	- 明白な実装
		- もう実装の仕方が見えているものは仮実装のステップを踏まずにそのまま書いちゃう
		- TDDはこの仮実装と明白な実装を行き来する
		- 仮実装をするか、明白な実装をするかは、実装するものに対する自信の度合いで切り分ける
		- 明白な実装でやろうと思って、なんかうまくいかなかったら、仮実装に切り替えて実装する
		- ステップを踏みかえる、歩幅を切り替えながら実装していく

- テストの書き方
	- TDD Style
		- テストメソッド名に全て記述する
		- test_数字2を渡した場合に文字列2を返す
	- BDD Style
		- 入れ子構造を使って、状況ごとに書いていく
		- FizzBuzzのテスト(describe)
			- 数字の場合(context)
				- 1を渡した場合(context)
					- 文字列1を返すこと(it)
				- 2を渡した場合(context)
					- 文字列2を返すこと(it)
			- Fizzの場合(context)
				- 3を渡した場合(context)
					- 文字列Fizzを返すこと(it)

- 最重要項目: リファクタリング
	- リファクタリングでやることは「重複の削除」
	- 不要なものを削除したりまとめたりして、綺麗にしておく

**Comment by ara-ta3** [comment]
FizzBuzzの設計で盛り上がれたの楽しかったｗ
@ktanaka117 氏に感謝 🙏 

そしてLive Share便利そうだった
https://www.visualstudio.com/ja/services/live-share/

**Comment by mrtry** [comment]
めも1692円

**Comment by mrtry** [comment]
今日の飲み代、ここから払ってください！！！
https://kyash.me/payments/gThEnFqYpiGu5yRCpotVcuj7gcRd

**Comment by ktanaka117** [comment]
Swift組のコード。

https://gist.github.com/ktanaka117/1c7270b7a8f8bcd44d45c6a83550d59b

**Comment by ara-ta3** [comment]
ブログもついでに貼っておこう
http://tanakalivesinsendai.hatenablog.com/entry/2018/05/29/023441

**Comment by ara-ta3** [comment]
結構前に終わってた
