### ISSUE TITLE
設計談義

### ISSUE THREAD

**Issue by iga-yamaguchi** [ngineerxiv/dark#83]
## 概要
[お前らがModelと呼ぶアレをなんと呼ぶべきか。近辺の用語(EntityとかVOとかDTOとか)について整理しつつ考える](https://qiita.com/takasek/items/70ab5a61756ee620aee6)

この記事を元にDAO、DTO、Service、Repositoryなど雑多に語る会
各社、個人でこんな感じにしているよとか聞きたい

## スケジュール
~調整中~ 調整完了
https://chouseisan.com/s?h=064cf63beb054c2e902c61d82433899f
6/27(水) 19:00～

## 場所
未定
多分うちも貸せる

**Comment by iga-yamaguchi** [comment]
スケジュール、一番多いのは6/27(水)かな？

**Comment by ktanaka117** [comment]
27日で！

**Comment by iga-yamaguchi** [comment]
27日に開催で！
場所はうち交渉してみます
ダメなら会場貸せる方お願いします 🙏

**Comment by iga-yamaguchi** [comment]
27日だったのですが諸事で延期します。
また調整さんとかたつ建てると思うのでよろしくお願いします。

**Comment by iga-yamaguchi** [comment]
#88
