### ISSUE TITLE
Belgian Beer Weekend @ 日比谷

### ISSUE THREAD

**Issue by yamitzky** [ngineerxiv/dark#85]
https://belgianbeerweekend.jp/2018/ja/hibiya

8/9-12開催です！！！！！

**Comment by rnitame** [comment]
いきたーーーーーーーーい
11 か 12！

**Comment by Omega014** [comment]
そういやこれ今日明日だった
たみー氏とやみつきー氏いけたら行こう

**Comment by rnitame** [comment]
たのしかったね〜〜〜

**Comment by yamitzky** [comment]
楽しかったのでCloseします！
