### ISSUE TITLE
ご飯を食べて歓談するイベント

### ISSUE THREAD

**Issue by Omega014** [ngineerxiv/dark#86]
# 概要
ストレス発散したいのでキッチン広めのスペースを借りて料理します.
参加者はでてくる料理を食べてワイワイしててください.
ゲームをやるも良し, ノリでLTし始めても良し, とにかく楽しそうにご飯囲んでる姿を見れればいいなと思ってます.
当日はプロジェクタとスクリーンを用意してあるので, なんか喋りたいことどんどん発表すると良いと思う.

# 日時・場所
**日時**
7/16(月) 12:30-16:00 

**場所**
https://spacemarket.com/spaces/smire_table/rooms/XU4a5kPPY5w6Hb0W
東京都渋谷区代々木5-65-4

- 参加人数は私を除外して最大9名募集してます. 5人集まったら開催.
- 参加費用はキッチンスペース料金と飲み物/人数分で, ご飯代は僕が好きなものを作りたいので自分が払います.
- 飲み物は自分が飲みたいだけ買ってきてね.

# 参加方法
参加できる日と参加するよってコメントをこのIssueに書く
食材を前日に揃えるのでドダキャンはなるべく無し
まだ空きがあるので他の人が良ければコミュニティメンバー以外の人も誘っても可

# 参加者
omega, rnitame, iga-yamaguchi, yamitzky, stefafafan, mihyaeru21, ktanaka117, acchanAlexander, ara-ta3, natsumican63

# 当日
12:30からオープンします. 私は準備やらなにやらで12:00からいますが, ご飯が出るのは12:30以降です. 
DARKの皆なら大丈夫だとは思うけど, レンタルスペースなので綺麗に使ってください. 上にレンタルスペースを貸してくれた業者の人がいるので, 治安の悪い音とかが聞こえたら怒られると思います. いつもどおり普通にわいわいすればok.

# その他
嫌いなものとかアレルギーあれば以下のdocsに書いてください
https://docs.google.com/document/d/1tZ57G3e9n4YsFWrIhiPjuUdWYvJizj1M5Wkq7BkV1jw/edit?usp=sharing

**Comment by rnitame** [comment]
14 か 16 🙋

**Comment by iga-yamaguchi** [comment]
行きたい！
自分も14か16！

**Comment by yamitzky** [comment]
14か16なら行きたい！

**Comment by stefafafan** [comment]
15か16で🙋

**Comment by Omega014** [comment]
16日 12:00-16:00開催でいきやす

**Comment by mihyaeru21** [comment]
16参戦します！

**Comment by ktanaka117** [comment]
16行く民

**Comment by ara-ta3** [comment]
16行くンゴ

**Comment by acchanAlexander** [comment]
16マン

**Comment by ytgch** [comment]
|дﾟ)

**Comment by natsumican63** [comment]
16行きたいです！！

**Comment by Omega014** [comment]
10人集まったので締切ります. taguchi氏はちょっと参加できるのかしたいのかコメントから分からなかったので, なつみかん氏をいれますた.
前日の夕方に材料を買うので, 不参加表明は前日の12:00まででお願いします. 
食品アレルギーや, どうしても食べられない物があれば以下のドキュメントに書いてください. これも前日の12:00までに書いてね. 
https://docs.google.com/document/d/1tZ57G3e9n4YsFWrIhiPjuUdWYvJizj1M5Wkq7BkV1jw/edit

**Comment by yutaguchi** [comment]
確かにあのコメントじゃ分からないっすよね、ごめんなさい
気をつけます

**Comment by stefafafan** [comment]
@Omega014 

> イベントスペースを予約できるか承認待ち！
https://github.com/ngineerxiv/dark/issues/86#issuecomment-402141755

とあるけどその後承認されなかったみたいなコメントはないので大丈夫ということで良いですかっ

> 東京都渋谷区代々木5-65-4
> 12:30からオープン
https://github.com/ngineerxiv/dark/issues/86#issue-337576425

であれば明日(16日)、12時半にこの場所に到着する感じで向かおうと思います。

**Comment by Omega014** [comment]
参加ありがとうございました！ひたすら料理できて楽しかった
Issueに書いてあるとおり, レンタルスペース代金だけいただきます 🙏
スペース代 14,175円
参加者 9人
一人あたり 1575円でした.

Kyashとか送金してもらえるとお互い楽だと思います！
Kyash ID: omega014
