### ISSUE TITLE
リアルスプラトゥーン

### ISSUE THREAD

**Issue by jp-taku2** [ngineerxiv/dark#89]
暑いので、リアルスプラトゥーンやりましょう

※全て自然に還るものを使用します
https://www.amazon.co.jp/dp/B00A6LH8GW?tag=aajg-1298-22&linkCode=as1&creative=6339
https://www.amazon.co.jp/dp/B06XVY33FF/ref=psdc_2189337051_t5_B079BQ9GFP
http://amzn.asia/8SRCluc

出欠確認
https://chouseisan.com/s?h=abd72e0581da487599b0e65243bee3f8

**Comment by ara-ta3** [comment]
暖かくなってきたけどやりたくなったら行こうな！
