### ISSUE TITLE
よなよなエールの超宴 @ お台場

### ISSUE THREAD

**Issue by rnitame** [ngineerxiv/dark#90]
ビールを飲もう
https://yohobrewing.com/cho_utage/

4人で行くとちょっとお得っぽい
https://yohobrewing.com/cho_utage/ticket.html

当日チケットなくて、なくなり次第終了なのでいきたい人いたら早めに決めたい

**Comment by Omega014** [comment]
自分いれて4人集まりそうなら行こうかなという感じ！

**Comment by mrtry** [comment]
🍻

**Comment by nasa9084** [comment]
微妙に予定立たない感あるけど希望ということで :beers:

**Comment by rnitame** [comment]
あつまった

**Comment by rnitame** [comment]
良いビールでした 🍺
