### ISSUE TITLE
多摩川あたりにチェアリングしにいく

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#91]
外でストロングゼロ（その他の缶チューハイやビール）を飲むだけのイベントです

発端
https://ngineerxiv.slack.com/archives/C0RQJM2HE/p1540887274011400

たみー氏おすすめのアウトドアチェア
https://www.amazon.co.jp/gp/product/B07CNPHK2W/ref=oh_aui_detailpage_o08_s00?ie=UTF8&psc=1
曰く、「折り畳み傘の一回り大きいくらいのサイズ感でございます」
https://ngineerxiv.slack.com/archives/C0RQJM2HE/p1540888889019400

**Comment by rnitame** [comment]
うぇいうぇーーい

**Comment by yamitzky** [comment]
お椅子買ったよ

![images 2ftest 2fthumb 2f95f28552-45f3-4049-938f-fc1997e53b77-b7e7b28b-ac33-4d48-9f49-499fe1d4a6d9](https://user-images.githubusercontent.com/623449/47890016-2f003600-de90-11e8-84cd-ae0c8012f16f.jpg)

**Comment by ara-ta3** [comment]
ばーん！
https://chouseisan.com/s?h=eb782b6d33424ddf86b00b08f6a13c57

**Comment by ara-ta3** [comment]
時間ミスったので作り直した

**Comment by ara-ta3** [comment]
あとあと必要になるんじゃないかと思ってテーブルまで買ってしまった私はYAGNI原則を理解できない愚か者です

![image](https://user-images.githubusercontent.com/2089153/47948972-2ab24680-df7e-11e8-8bcb-df4b8db8aadc.png)

**Comment by ara-ta3** [comment]
17日の13時か14時くらいの予定です

```
tummy [15:18]
設計話が盛り上がってしまったので DM ににげる
https://github.com/ngineerxiv/dark/issues/91#issuecomment-435564895
GitHub
多摩川あたりにチェアリングしにいく · Issue #91 · ngineerxiv/dark
外でストロングゼロ（その他の缶チューハイやビール）を飲むだけのイベントです 発端 https://ngineerxiv.slack.com/archives/C0RQJM2HE/p1540887274011400 たみー氏おすすめのアウトドアチェア https://www.amazon.co.jp/gp/product/B07CNPHK2W/ref=oh_aui_detailpage_o08...
17 or 18

ara_ta3 [15:18]
w
17でいいんじゃないかな

tummy [15:19]
チェアリングは何時ぐらいが最高なんですか！！ @yamitzky

ara_ta3 [15:19]
問題は今風邪を引き始めてる点

tummy [15:19]
割と重大w

yamitzky [15:27]
チェアリングやったことないけど、
・寒さ
・ギルティーさ
を考えると明るいお時間がよろしいかと思います

ara_ta3 [15:27]
13時から14時あたりかな

tummy [15:27]
どっかで昼食ってそのままキメに行くか
ギルティーさマシマシ
```

**Comment by ara-ta3** [comment]
また行こうな
