### ISSUE TITLE
設計について語る会やります

### ISSUE THREAD

**Issue by ktanaka117** [ngineerxiv/dark#92]
[設計本](https://peaks.cc/iOS_architecture)の執筆も落ち着いて着たので、**設計についてざっくばらんに話す会**をします。

「設計」というと「怖い」という語がうしろにきがちなテーマなので、見知った人を集めて小規模に、心理的安全性を高めつつやろうと思います。
合ってる、間違ってるとかは気にせず、気軽にYATTEIKI。

## 経緯
danbo-tanaka [12:58 PM]
> そういえば
> `MVC, MVP, MVVM, CleanArchitecture, Flux, Redux, etc…のアーキテクチャパターンって、若干の適用> 方法の違いはあれど、プラットフォームを問わず同じ理解で通用する。`
> と思っているので聞くのですが、それぞれの認知度ってみなさまどんな感じなんでしょう？（興味本位）
> これはあまり知らないとかあれば聞いてみたい👀

https://ngineerxiv.slack.com/archives/C034QSSPA/p1541649529175700

nasa9084 [1:42 PM]
> アーキテクチャとかデザインパターンとか解説する会が欲しい・・・

https://ngineerxiv.slack.com/archives/C034QSSPA/p1541652016187500

### 設計について話すパート（登壇）
  - 自分が思っている「設計とは？」
  - 「今こう捉えていて、ここがわからん」
  - 「今現場で使ってるアーキテクチャパターン」
  - etc
### 設計について語るパート（雑談）
  - せっかく人が集まるので、ざっくばらんにわいわいする
    - 「この単語ってこういう意味ですよね？」とか
    - 「今こういうことで困ってるんだけど、どうするべき？」とか

**Comment by ktanaka117** [comment]
田中は以下について話してみます。

『GUIアーキテクチャの源流をたどる〜MVC, MVP, MVVMの動機と特徴〜』（仮）

**Comment by ktanaka117** [comment]
## 調整さん
https://chouseisan.com/s?h=0fd60bf02069425a8a2783d5f830f372

**Comment by rnitame** [comment]
行けたら「複雑な状態管理を MVVM+Flux でやろうとしてるけどしんどい」って話をしたい

**Comment by ktanaka117** [comment]
土日が厳しい民もいたため、平日の部も立ててみた。
https://chouseisan.com/s?h=01d1d98c20324f3c85a39dcf8caa7a14

**Comment by ktanaka117** [comment]
## 開催要項
### 設計について語る会（土日の部）
- 開催日: 12月1日
- 場所: nasa氏の会社
- 時間: 調整中

### 設計について語る会（平日の部）
- 開催日: 12月7日
- 場所: Ajito
- 時間: 調整中

**Comment by nasa9084** [comment]
LINEです

**Comment by ktanaka117** [comment]
直しました！LINEです！

**Comment by ktanaka117** [comment]
## 開催要項（あっぷでーと）
ふるってご参加ください。

### 設計について語る会（土日の部）
- 開催日: 12月1日
- 場所: LINE（予定）
- 時間: 13:30〜15:30

### 設計について語る会（平日の部）
- 開催日: 12月7日
- 場所: Ajito
- 時間: 19:30〜21:30

**Comment by nasa9084** [comment]
弊社セミナールーム無事(?)予約できました。
@ktanaka117 さんが来客筆頭となっております

**Comment by nasa9084** [comment]
資料が間に合えば並行処理デザインパターンの紹介します

**Comment by iga-yamaguchi** [comment]
時間作れたらなんか書いていってレビューしてもらいたい
サーバーアプリケーションと、フロントのVuex（Flux）周り

**Comment by ktanaka117** [comment]
ちょっとご相談。
iOS設計本を一緒に書いた[takasek](https://twitter.com/takasek)さんをこの会にお呼びしたいと思っているのですが、いかがでしょう？

`「見知った人を集めて小規模に、心理的安全性を高めつつ」` というコンセプトを掲げているので、みなさんがよければ招待しようかなと思っています。
takasekさんは物腰柔らかで怖くはないし、iOS以外でも物知りでつよつよな人なので、来てもらえれば楽しくなるはずです。

**Comment by nasa9084** [comment]
LGTM

**Comment by ktanaka117** [comment]
じゃー、takasek先生お呼びしちゃいまーす！

いべんとの　のうどが　たかまった！

**Comment by takasek** [comment]
ヒュー！
お呼ばれしましたtakasekです。
趣味はマサカリです。嘘です。
よろしくおねがいします。

**Comment by ktanaka117** [comment]
### こんな進行はやってみたい
- nasa氏、Line様会場提供ありがとう
- Youtube限定配信
- 自己紹介

### TODO
- 名前とメインのプラットフォームを書いておく名札的Something
- リモート民のための配信機材
  - Macbook Air && マイク
  - or iPad Pro
- あとでブログにまとめるための集音機材(↑があればおk)

**Comment by takasek** [comment]
https://workflowy.com/s/e855f4aae21/okowbWlvDEWaSg9g

**Comment by ktanaka117** [comment]
資料できた
![2018-12-07 11 54 09 2](https://user-images.githubusercontent.com/4278711/49625071-5a3dee00-fa17-11e8-84b8-f6f9cd6b5f6d.png)
