### ISSUE TITLE
ごましと飲もう 2/15, 2/16

### ISSUE THREAD

**Issue by gomayumax** [ngineerxiv/dark#95]
# 概要
東京にごましがやって来る!!!!
飲みましょう

# 日時
2/15(金) 19:00~
2/16(土) 19:00~

調整さん↓↓
https://chouseisan.com/s?h=c2eed98c5090476282dbbcdfd9c248fc

# 店/場所
考え中....

# 注意
泥酔はできません

**Comment by gomayumax** [comment]
## 開催日詳細
日時: 2/15(金) 19:30
場所: 目黒の雑な居酒屋 https://tabelog.com/tokyo/A1316/A131601/13127424/party/25442447

欠席連絡2/13(水)までに

**Comment by gomayumax** [comment]
https://ngineerxiv.slack.com/archives/C1G9NUU2D/p1549434979235100

> GomaConf tokyo 2019
> ネーミング好きなので、当日ハッシュタグにしよう

**Comment by yamitzky** [comment]
定時 19:00 なので、急ぐけど遅れます・・・！ :bow:

**Comment by isaoeka** [comment]
楽しみ ![たのしげ](http://livedoor.blogimg.jp/nanjstu/imgs/d/1/d167a573.gif)

**Comment by ara-ta3** [comment]
トゥギャりました
https://togetter.com/li/1319658

**Comment by gomayumax** [comment]
最高のカンファレンス体験でした！ありがとうございました😊また次回の開催を楽しみにしていてください！次はちゃんと基調講演するよ！！

**Comment by gomayumax** [comment]
最高のカンファレンス体験でした！ありがとうございました😊また次回の開催を楽しみにしていてください！次はちゃんと基調講演するよ！！
