### ISSUE TITLE
「エンジニアリング組織論への招待」の輪読会やっていき

### ISSUE THREAD

**Issue by haze-it** [ngineerxiv/dark#96]
経緯: https://twitter.com/noa_design51/status/1096080052985290752

本: https://gihyo.jp/book/2018/978-4-7741-9605-3

特に直接顔を合わせないといけないものでもないし、土 or 日の午前どっか1時間固定にして枠の内容について話す　とかで良いと思う
（毎週日曜日朝11:00~12:00 みたいな）

Captureは5つ。2回で1Capture進むぐらいのスピード感で良いかなーって考えてるけどどうだろうか

**初回: ~~2/24(日)~~ 3/3(日) JST 11:00-**

Milanote: https://app.milanote.com/1GUuZq1IZyLB78/

**Comment by noainoue** [comment]
hazeさん、完全にLGTMです。

> 2回で1Capture進むぐらいのスピード感で良いかなー
同意。完全にLGTMです。

> 特に直接顔を合わせないといけないものでもない
同意。完全にLGTMです。
日曜日までに決められた部分を読んでおいて
「p.〇〇のここの文章ささったわ〜〜」みたいな会話を
ハングアウトとか使ってできればいいかな？と思っている

とりあえず参加者募りたい

**Comment by haze-it** [comment]
参加者募るか〜〜
**とりあえず初回参加予定の人はここのissueに適当にコメント書いてくださいな**

--


> 日曜日までに決められた部分を読んでおいて
「p.〇〇のここの文章ささったわ〜〜」みたいな会話を
ハングアウトとか使ってできればいいかな？と思っている

:yosasou: :yaritai:

**Comment by acchanAlexander** [comment]
:akeome:

**Comment by butaosuinu** [comment]
参加したいけど当日寝坊する確率は50%です( ˘ω˘)ｽﾔｧ

**Comment by mihyaeru21** [comment]
👀

**Comment by ktanaka117** [comment]
:waiwai:

**Comment by acchanAlexander** [comment]
行きたい人生だったけど、その日予定入ってた
事前に感想をどっかに書くなりしようかな

**Comment by haze-it** [comment]
@acchanAlexander お、感想先に書いてもらっても良いし、多分議事録みたいなのは軽く作るからそれを見て後でうぇいうぇいするのでも良いと思う

**Comment by noainoue** [comment]
そうだな〜〜！
Milanoteとか使ってみようかなと思ってたので
あっちゃんもこんな感じでコメント残すといいかも！
そしたら第二回からでも寝坊しても参加できるし！

<img width="457" alt="2019-02-15 13 01 28" src="https://user-images.githubusercontent.com/32755075/52833786-02f88000-3122-11e9-9989-2eeadcb7d747.png">

**Comment by papix** [comment]
👀

**Comment by papix** [comment]
ちょうど買ったところなので, きっかけづくりとして参加しようかな. ただ最近本を取捨選択して読んでみたいという気持ちがあって, 途中で抜けたりするかも. それでよければ〜

**Comment by haze-it** [comment]
出入りは特に気にしないので大丈夫ですよー、こっちもそこまで管理するの大変なので

**Comment by noainoue** [comment]
ガッチガチに縛ってやりたくはないので、途中参加も途中退出も自由で同意です！

完全にLGTMです！

**Comment by noainoue** [comment]
https://app.milanote.com/1GUuUS1IZytioY/home

ここに第〇回っての置いていきます！
雑に使ってみてくれ〜〜(見れるかな？👀)

**Comment by noainoue** [comment]
# 輪読会Milanote
https://app.milanote.com/1GUuZq1IZyLB78/

# Milanote
編集権限を与えるために、参加者はメールアドレスを個別に教えてください！

**Comment by Udomomo** [comment]
参加したいです
(当日の副業の忙しさ次第ですが)

**Comment by haze-it** [comment]
### 1回目（2/24）の範囲
 - Capture1 1-1 〜 1-4  ( `~ P.33` )　迄かな

**Comment by noainoue** [comment]
雑にテンプレ貼ってみた、こんな感じで使うといいよみたいな！

<img width="941" alt="2019-02-17 0 45 19" src="https://user-images.githubusercontent.com/32755075/52901949-721ec300-324d-11e9-8b95-f5ac585cf52e.png">

**Comment by isaoeka** [comment]
👀

**Comment by noainoue** [comment]
@各位

明日のこの時間、副業の打ち合わせが入ってしまって参加できそうにないという...すみません
みんなの都合ずらしてもらうの申し訳ないので初回不参加で...

**Comment by haze-it** [comment]
そんなわけで人数少なくなりそうだったので初回を **3/3(日) 11:00-** に変更しますのでよろしゅう、直前でごめんよ @さんかよていしゃ
https://ngineerxiv.slack.com/archives/C1G9NUU2D/p1550922939036800

**Comment by haze-it** [comment]
## 次回は3/10(日) 11:00- です。範囲はCapture 1の最後まで。

感想はMilanoteへ。
書き方は前回同様。

進行、一人一人が話すと結構時間かかることがわかったので、小節ごとに各々が思ったことを話していく流れにしようかなと思います。当日調整とかするかも。意見あったらください

**Comment by haze-it** [comment]
↑ 〜Capture 1 最後までの会、人が集まってないので来週に移します。（3/17）
みんな読んでね！！！！

**Comment by haze-it** [comment]
#reading_circle_inv_e つくった。
Milanoteに一回以上書いてた人をとりあえず最初にjoinさせたけど他に入りたい人いたら適当にどうぞ

**Comment by noainoue** [comment]
次回: 3/24(日) 11:00- 〜Capture.2 2-1, 2-2

**Comment by haze-it** [comment]
https://ngineerxiv.slack.com/messages/CGV3PRGQ3
