### ISSUE TITLE
DARK 花見 2019

### ISSUE THREAD

**Issue by Omega014** [ngineerxiv/dark#97]
# 概要
東京の花見スポットで各自寝たり酒のんだりジャグリングとかする会です.
雨天だったら解散 or その辺の居酒屋で飯食いましょう

# 日時・場所
4/7(日) 11:00〜
場所は広いから代々木公園にします
omegaが11時くらいに行って適当にブルーシート敷いて場所取りする予定（起きれたら）

予報では夕方から降水確率が40%くらいらしいんで、その時は解散orどっか飲み行くかしましょう。

日程調整済みだけど参加したい人は自由に来るといいと思う（ただし座るスペースの保証はできない）

# 持ち物
各自持ってきたいものを持ってきて下さい！
以下参考物品
- 飲食物
- 防寒具（日が落ちると寒くなるので）
- 折りたたみ椅子
- おもちゃ（ジャグリング等）
- ノートパソコン

# 参加者
ara_ta3 | haze | danbo-tanaka | たみーさん | 泥酔太郎（is 誰） | おめが | いがにん | みひゃえる
nasa, suzutaku, udayan

# その他
omegaは1.8m x 2.7mのブルーシートを一枚買って持っていきます。
当初より参加者が増えたので一枚だと足りないです。追加で誰か持ってきてもらえると助かります。

**Comment by rnitame** [comment]
4/7 が濃厚

**Comment by Omega014** [comment]
4/7(日) に決定したのでみなさん予定空けといてくだしあ

**Comment by mihyaeru21** [comment]
完全に見逃してた！参加したい！

**Comment by Omega014** [comment]
ほいー、参加者リストに入れとく！

**Comment by nasa9084** [comment]
参加したいです！

**Comment by takumi-suzuki** [comment]
曖昧性のある参加表明は可能でしょうか？

**Comment by Omega014** [comment]
suzutaku> モーマンタイ！

**Comment by Omega014** [comment]
今週の日曜は花見です
日程と場所と持ち物確認してねん

**Comment by haze-it** [comment]
シート持っていくね

**Comment by Omega014** [comment]
また来年
