### ISSUE TITLE
イカセンターに行くよ！！！！！

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark#98]
https://ngineerxiv.slack.com/archives/C034QSSPA/p1553672904373900
https://www.hotpepper.jp/mesitsu/entry/rika-nakui/19-00063

日にちは4/3な！
今の所たみー氏はぜ氏なさ氏わい氏の4人かな

**Comment by haze-it** [comment]
場所: 渋谷イカセンター
 - 〒150-0043 東京都渋谷区道玄坂２丁目１０−１２ 新大宗ビル3号館B1

参加者はコメントしていく感じかな

時間はたぶん19:00-か20:00-くらい

**Comment by butaosuinu** [comment]
行くぜ

**Comment by udayan28** [comment]
行くぅ！！！うぇいうぇい

**Comment by rnitame** [comment]
19 時半からだよ〜

**Comment by ara-ta3** [comment]
記憶をなくしたり、プラベに間に合わなかったり、次の日に吐き気がしてたり、遅刻したりなどの被害を出して無事致命傷で事なきを得ました
https://ngineerxiv.slack.com/archives/C0RQJM2HE/p1554308033007200
