### ISSUE TITLE
DARK 麻雀 2019

### ISSUE THREAD

**Issue by urataku** [ngineerxiv/dark#99]
# 概要
- 10連休中に麻雀したい人この指とまれ
- 最低人数4人

# 日程
- とりあえず調整さん↓(19時〜になってるのは無視してクレメンス)
- https://chouseisan.com/s?h=2b9bea4f2b1e407988d91115e88c49e6

# ルール
- ネット麻雀「天鳳」と一緒(めんどいのでローカルルールなし)

**Comment by isaoeka** [comment]
nice

**Comment by isaoeka** [comment]
2日になりました
https://ngineerxiv.slack.com/archives/C3QR1F1LN/p1554544992033500

**Comment by isaoeka** [comment]
これCloseして良いかも @urataku
